/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_System_Root, cmd_System_Root, AUTO)


PB_BIND(cmd_System_StartALl, cmd_System_StartALl, AUTO)


PB_BIND(cmd_System_StopALl, cmd_System_StopALl, AUTO)


PB_BIND(cmd_System_Reboot, cmd_System_Reboot, AUTO)


PB_BIND(cmd_System_PowerOff, cmd_System_PowerOff, AUTO)


PB_BIND(cmd_System_ResetConfigs, cmd_System_ResetConfigs, AUTO)


PB_BIND(cmd_System_SaveFactoryDefaults, cmd_System_SaveFactoryDefaults, AUTO)


PB_BIND(cmd_System_WipeUserData, cmd_System_WipeUserData, AUTO)


PB_BIND(cmd_System_StartRec, cmd_System_StartRec, AUTO)


PB_BIND(cmd_System_StopRec, cmd_System_StopRec, AUTO)


PB_BIND(cmd_System_MarkRecImportant, cmd_System_MarkRecImportant, AUTO)


PB_BIND(cmd_System_UnmarkRecImportant, cmd_System_UnmarkRecImportant, AUTO)


PB_BIND(cmd_System_EnterTransport, cmd_System_EnterTransport, AUTO)


PB_BIND(cmd_System_EnableGeodesicMode, cmd_System_EnableGeodesicMode, AUTO)


PB_BIND(cmd_System_DisableGeodesicMode, cmd_System_DisableGeodesicMode, AUTO)


PB_BIND(cmd_System_SetLocalization, cmd_System_SetLocalization, AUTO)


PB_BIND(cmd_System_StepYear, cmd_System_StepYear, AUTO)


PB_BIND(cmd_System_StepMonth, cmd_System_StepMonth, AUTO)


PB_BIND(cmd_System_StepDay, cmd_System_StepDay, AUTO)


PB_BIND(cmd_System_StepHour, cmd_System_StepHour, AUTO)


PB_BIND(cmd_System_StepMinute, cmd_System_StepMinute, AUTO)


PB_BIND(cmd_System_StepSecond, cmd_System_StepSecond, AUTO)


PB_BIND(cmd_System_EnableManualTime, cmd_System_EnableManualTime, AUTO)


PB_BIND(cmd_System_DisableManualTime, cmd_System_DisableManualTime, AUTO)


PB_BIND(cmd_System_SetTimeZone, cmd_System_SetTimeZone, AUTO)


PB_BIND(cmd_System_StepTimeZone, cmd_System_StepTimeZone, AUTO)


PB_BIND(cmd_System_SetTimeAndZone, cmd_System_SetTimeAndZone, AUTO)



