/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_day_camera.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_DayCamera_SetValue, cmd_DayCamera_SetValue, AUTO)


PB_BIND(cmd_DayCamera_Move, cmd_DayCamera_Move, AUTO)


PB_BIND(cmd_DayCamera_Offset, cmd_DayCamera_Offset, AUTO)


PB_BIND(cmd_DayCamera_SetClaheLevel, cmd_DayCamera_SetClaheLevel, AUTO)


PB_BIND(cmd_DayCamera_ShiftClaheLevel, cmd_DayCamera_ShiftClaheLevel, AUTO)


PB_BIND(cmd_DayCamera_Root, cmd_DayCamera_Root, AUTO)


PB_BIND(cmd_DayCamera_GetPos, cmd_DayCamera_GetPos, AUTO)


PB_BIND(cmd_DayCamera_NextFxMode, cmd_DayCamera_NextFxMode, AUTO)


PB_BIND(cmd_DayCamera_PrevFxMode, cmd_DayCamera_PrevFxMode, AUTO)


PB_BIND(cmd_DayCamera_RefreshFxMode, cmd_DayCamera_RefreshFxMode, AUTO)


PB_BIND(cmd_DayCamera_HaltAll, cmd_DayCamera_HaltAll, AUTO)


PB_BIND(cmd_DayCamera_SetFxMode, cmd_DayCamera_SetFxMode, AUTO)


PB_BIND(cmd_DayCamera_SetDigitalZoomLevel, cmd_DayCamera_SetDigitalZoomLevel, AUTO)


PB_BIND(cmd_DayCamera_Focus, cmd_DayCamera_Focus, AUTO)


PB_BIND(cmd_DayCamera_Zoom, cmd_DayCamera_Zoom, AUTO)


PB_BIND(cmd_DayCamera_NextZoomTablePos, cmd_DayCamera_NextZoomTablePos, AUTO)


PB_BIND(cmd_DayCamera_PrevZoomTablePos, cmd_DayCamera_PrevZoomTablePos, AUTO)


PB_BIND(cmd_DayCamera_SetIris, cmd_DayCamera_SetIris, AUTO)


PB_BIND(cmd_DayCamera_SetInfraRedFilter, cmd_DayCamera_SetInfraRedFilter, AUTO)


PB_BIND(cmd_DayCamera_SetAutoIris, cmd_DayCamera_SetAutoIris, AUTO)


PB_BIND(cmd_DayCamera_SetAutoGain, cmd_DayCamera_SetAutoGain, AUTO)


PB_BIND(cmd_DayCamera_SetZoomTableValue, cmd_DayCamera_SetZoomTableValue, AUTO)


PB_BIND(cmd_DayCamera_Stop, cmd_DayCamera_Stop, AUTO)


PB_BIND(cmd_DayCamera_Start, cmd_DayCamera_Start, AUTO)


PB_BIND(cmd_DayCamera_Photo, cmd_DayCamera_Photo, AUTO)


PB_BIND(cmd_DayCamera_Halt, cmd_DayCamera_Halt, AUTO)


PB_BIND(cmd_DayCamera_GetMeteo, cmd_DayCamera_GetMeteo, AUTO)


PB_BIND(cmd_DayCamera_ResetZoom, cmd_DayCamera_ResetZoom, AUTO)


PB_BIND(cmd_DayCamera_ResetFocus, cmd_DayCamera_ResetFocus, AUTO)


PB_BIND(cmd_DayCamera_SaveToTable, cmd_DayCamera_SaveToTable, AUTO)


PB_BIND(cmd_DayCamera_SaveToTableFocus, cmd_DayCamera_SaveToTableFocus, AUTO)


PB_BIND(cmd_DayCamera_FocusROI, cmd_DayCamera_FocusROI, AUTO)


PB_BIND(cmd_DayCamera_TrackROI, cmd_DayCamera_TrackROI, AUTO)


PB_BIND(cmd_DayCamera_ZoomROI, cmd_DayCamera_ZoomROI, AUTO)


PB_BIND(cmd_DayCamera_FxROI, cmd_DayCamera_FxROI, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

