/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_gps.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_Gps_Root, cmd_Gps_Root, AUTO)


PB_BIND(cmd_Gps_Start, cmd_Gps_Start, AUTO)


PB_BIND(cmd_Gps_Stop, cmd_Gps_Stop, AUTO)


PB_BIND(cmd_Gps_GetMeteo, cmd_Gps_GetMeteo, AUTO)


PB_BIND(cmd_Gps_SetUseManualPosition, cmd_Gps_SetUseManualPosition, AUTO)


PB_BIND(cmd_Gps_SetManualPosition, cmd_Gps_SetManualPosition, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

