/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_day_cam_glass_heater.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_DayCamGlassHeater_Root, cmd_DayCamGlassHeater_Root, AUTO)


PB_BIND(cmd_DayCamGlassHeater_Start, cmd_DayCamGlassHeater_Start, AUTO)


PB_BIND(cmd_DayCamGlassHeater_Stop, cmd_DayCamGlassHeater_Stop, AUTO)


PB_BIND(cmd_DayCamGlassHeater_TurnOn, cmd_DayCamGlassHeater_TurnOn, AUTO)


PB_BIND(cmd_DayCamGlassHeater_TurnOff, cmd_DayCamGlassHeater_TurnOff, AUTO)


PB_BIND(cmd_DayCamGlassHeater_GetMeteo, cmd_DayCamGlassHeater_GetMeteo, AUTO)



