/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_COMPASS_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_COMPASS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ser_JonGuiDataCompass
{
  double azimuth;
  double elevation;
  double bank;
  double offsetAzimuth;
  double offsetElevation;
  double magneticDeclination;
  bool calibrating;
  bool is_started;
} ser_JonGuiDataCompass;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataCompass_init_default { 0, 0, 0, 0, 0, 0, 0, 0 }
#define ser_JonGuiDataCompass_init_zero { 0, 0, 0, 0, 0, 0, 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataCompass_azimuth_tag 1
#define ser_JonGuiDataCompass_elevation_tag 2
#define ser_JonGuiDataCompass_bank_tag 3
#define ser_JonGuiDataCompass_offsetAzimuth_tag 4
#define ser_JonGuiDataCompass_offsetElevation_tag 5
#define ser_JonGuiDataCompass_magneticDeclination_tag 6
#define ser_JonGuiDataCompass_calibrating_tag 7
#define ser_JonGuiDataCompass_is_started_tag 8

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataCompass_FIELDLIST(X, a)            \
  X(a, STATIC, SINGULAR, DOUBLE, azimuth, 1)             \
  X(a, STATIC, SINGULAR, DOUBLE, elevation, 2)           \
  X(a, STATIC, SINGULAR, DOUBLE, bank, 3)                \
  X(a, STATIC, SINGULAR, DOUBLE, offsetAzimuth, 4)       \
  X(a, STATIC, SINGULAR, DOUBLE, offsetElevation, 5)     \
  X(a, STATIC, SINGULAR, DOUBLE, magneticDeclination, 6) \
  X(a, STATIC, SINGULAR, BOOL, calibrating, 7)           \
  X(a, STATIC, SINGULAR, BOOL, is_started, 8)
#define ser_JonGuiDataCompass_CALLBACK NULL
#define ser_JonGuiDataCompass_DEFAULT NULL

  extern const pb_msgdesc_t ser_JonGuiDataCompass_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataCompass_fields &ser_JonGuiDataCompass_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_COMPASS_PB_H_MAX_SIZE ser_JonGuiDataCompass_size
#define ser_JonGuiDataCompass_size 58

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
