/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_heat_camera.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_HeatCamera_Root, cmd_HeatCamera_Root, AUTO)


PB_BIND(cmd_HeatCamera_SetFxMode, cmd_HeatCamera_SetFxMode, AUTO)


PB_BIND(cmd_HeatCamera_SetClaheLevel, cmd_HeatCamera_SetClaheLevel, AUTO)


PB_BIND(cmd_HeatCamera_ShiftClaheLevel, cmd_HeatCamera_ShiftClaheLevel, AUTO)


PB_BIND(cmd_HeatCamera_NextFxMode, cmd_HeatCamera_NextFxMode, AUTO)


PB_BIND(cmd_HeatCamera_PrevFxMode, cmd_HeatCamera_PrevFxMode, AUTO)


PB_BIND(cmd_HeatCamera_RefreshFxMode, cmd_HeatCamera_RefreshFxMode, AUTO)


PB_BIND(cmd_HeatCamera_EnableDDE, cmd_HeatCamera_EnableDDE, AUTO)


PB_BIND(cmd_HeatCamera_DisableDDE, cmd_HeatCamera_DisableDDE, AUTO)


PB_BIND(cmd_HeatCamera_SetValue, cmd_HeatCamera_SetValue, AUTO)


PB_BIND(cmd_HeatCamera_SetDDELevel, cmd_HeatCamera_SetDDELevel, AUTO)


PB_BIND(cmd_HeatCamera_SetDigitalZoomLevel,
        cmd_HeatCamera_SetDigitalZoomLevel,
        AUTO)


PB_BIND(cmd_HeatCamera_ShiftDDE, cmd_HeatCamera_ShiftDDE, AUTO)


PB_BIND(cmd_HeatCamera_ZoomIn, cmd_HeatCamera_ZoomIn, AUTO)


PB_BIND(cmd_HeatCamera_ZoomOut, cmd_HeatCamera_ZoomOut, AUTO)


PB_BIND(cmd_HeatCamera_ZoomStop, cmd_HeatCamera_ZoomStop, AUTO)


PB_BIND(cmd_HeatCamera_FocusIn, cmd_HeatCamera_FocusIn, AUTO)


PB_BIND(cmd_HeatCamera_FocusOut, cmd_HeatCamera_FocusOut, AUTO)


PB_BIND(cmd_HeatCamera_FocusStop, cmd_HeatCamera_FocusStop, AUTO)


PB_BIND(cmd_HeatCamera_FocusStepPlus, cmd_HeatCamera_FocusStepPlus, AUTO)


PB_BIND(cmd_HeatCamera_FocusStepMinus, cmd_HeatCamera_FocusStepMinus, AUTO)


PB_BIND(cmd_HeatCamera_Calibrate, cmd_HeatCamera_Calibrate, AUTO)


PB_BIND(cmd_HeatCamera_Zoom, cmd_HeatCamera_Zoom, AUTO)


PB_BIND(cmd_HeatCamera_NextZoomTablePos, cmd_HeatCamera_NextZoomTablePos, AUTO)


PB_BIND(cmd_HeatCamera_PrevZoomTablePos, cmd_HeatCamera_PrevZoomTablePos, AUTO)


PB_BIND(cmd_HeatCamera_SetCalibMode, cmd_HeatCamera_SetCalibMode, AUTO)


PB_BIND(cmd_HeatCamera_SetZoomTableValue,
        cmd_HeatCamera_SetZoomTableValue,
        AUTO)


PB_BIND(cmd_HeatCamera_SetAGC, cmd_HeatCamera_SetAGC, AUTO)


PB_BIND(cmd_HeatCamera_SetFilters, cmd_HeatCamera_SetFilters, AUTO)


PB_BIND(cmd_HeatCamera_Start, cmd_HeatCamera_Start, AUTO)


PB_BIND(cmd_HeatCamera_Stop, cmd_HeatCamera_Stop, AUTO)


PB_BIND(cmd_HeatCamera_Halt, cmd_HeatCamera_Halt, AUTO)


PB_BIND(cmd_HeatCamera_Photo, cmd_HeatCamera_Photo, AUTO)


PB_BIND(cmd_HeatCamera_GetMeteo, cmd_HeatCamera_GetMeteo, AUTO)


PB_BIND(cmd_HeatCamera_SetAutoFocus, cmd_HeatCamera_SetAutoFocus, AUTO)


PB_BIND(cmd_HeatCamera_ResetZoom, cmd_HeatCamera_ResetZoom, AUTO)


PB_BIND(cmd_HeatCamera_SaveToTable, cmd_HeatCamera_SaveToTable, AUTO)


PB_BIND(cmd_HeatCamera_FocusROI, cmd_HeatCamera_FocusROI, AUTO)


PB_BIND(cmd_HeatCamera_TrackROI, cmd_HeatCamera_TrackROI, AUTO)


PB_BIND(cmd_HeatCamera_ZoomROI, cmd_HeatCamera_ZoomROI, AUTO)


PB_BIND(cmd_HeatCamera_FxROI, cmd_HeatCamera_FxROI, AUTO)


#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
