/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_LIRA_JON_SHARED_CMD_LIRA_PB_H_INCLUDED
#define PB_CMD_LIRA_JON_SHARED_CMD_LIRA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_Lira_JonGuiDataLiraTarget
{
  int64_t timestamp;
  double target_longitude;
  double target_latitude;
  double target_altitude;
  double target_azimuth;
  double target_elevation;
  double distance;
  /* UUID as four fixed32 values (128 bits total) */
  int32_t uuid_part1;
  int32_t uuid_part2;
  int32_t uuid_part3;
  int32_t uuid_part4;
} cmd_Lira_JonGuiDataLiraTarget;

typedef struct _cmd_Lira_Refine_target
{
  bool has_target;
  cmd_Lira_JonGuiDataLiraTarget target;
} cmd_Lira_Refine_target;

typedef struct _cmd_Lira_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_Lira_Refine_target refine_target;
  } cmd;
} cmd_Lira_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_Lira_Root_init_default        \
  {                                       \
    0,                                    \
    {                                     \
      cmd_Lira_Refine_target_init_default \
    }                                     \
  }
#define cmd_Lira_Refine_target_init_default           \
  {                                                   \
    false, cmd_Lira_JonGuiDataLiraTarget_init_default \
  }
#define cmd_Lira_JonGuiDataLiraTarget_init_default \
  {                                                \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0                \
  }
#define cmd_Lira_Root_init_zero        \
  {                                    \
    0,                                 \
    {                                  \
      cmd_Lira_Refine_target_init_zero \
    }                                  \
  }
#define cmd_Lira_Refine_target_init_zero           \
  {                                                \
    false, cmd_Lira_JonGuiDataLiraTarget_init_zero \
  }
#define cmd_Lira_JonGuiDataLiraTarget_init_zero \
  {                                             \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0             \
  }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_Lira_JonGuiDataLiraTarget_timestamp_tag 1
#define cmd_Lira_JonGuiDataLiraTarget_target_longitude_tag 2
#define cmd_Lira_JonGuiDataLiraTarget_target_latitude_tag 3
#define cmd_Lira_JonGuiDataLiraTarget_target_altitude_tag 4
#define cmd_Lira_JonGuiDataLiraTarget_target_azimuth_tag 5
#define cmd_Lira_JonGuiDataLiraTarget_target_elevation_tag 6
#define cmd_Lira_JonGuiDataLiraTarget_distance_tag 7
#define cmd_Lira_JonGuiDataLiraTarget_uuid_part1_tag 8
#define cmd_Lira_JonGuiDataLiraTarget_uuid_part2_tag 9
#define cmd_Lira_JonGuiDataLiraTarget_uuid_part3_tag 10
#define cmd_Lira_JonGuiDataLiraTarget_uuid_part4_tag 11
#define cmd_Lira_Refine_target_target_tag 1
#define cmd_Lira_Root_refine_target_tag 1

/* Struct field encoding specification for nanopb */
#define cmd_Lira_Root_FIELDLIST(X, a) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, refine_target, cmd.refine_target), 1)
#define cmd_Lira_Root_CALLBACK NULL
#define cmd_Lira_Root_DEFAULT NULL
#define cmd_Lira_Root_cmd_refine_target_MSGTYPE cmd_Lira_Refine_target

#define cmd_Lira_Refine_target_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, target, 1)
#define cmd_Lira_Refine_target_CALLBACK NULL
#define cmd_Lira_Refine_target_DEFAULT NULL
#define cmd_Lira_Refine_target_target_MSGTYPE cmd_Lira_JonGuiDataLiraTarget

#define cmd_Lira_JonGuiDataLiraTarget_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT64, timestamp, 1)         \
  X(a, STATIC, SINGULAR, DOUBLE, target_longitude, 2) \
  X(a, STATIC, SINGULAR, DOUBLE, target_latitude, 3)  \
  X(a, STATIC, SINGULAR, DOUBLE, target_altitude, 4)  \
  X(a, STATIC, SINGULAR, DOUBLE, target_azimuth, 5)   \
  X(a, STATIC, SINGULAR, DOUBLE, target_elevation, 6) \
  X(a, STATIC, SINGULAR, DOUBLE, distance, 7)         \
  X(a, STATIC, SINGULAR, INT32, uuid_part1, 8)        \
  X(a, STATIC, SINGULAR, INT32, uuid_part2, 9)        \
  X(a, STATIC, SINGULAR, INT32, uuid_part3, 10)       \
  X(a, STATIC, SINGULAR, INT32, uuid_part4, 11)
#define cmd_Lira_JonGuiDataLiraTarget_CALLBACK NULL
#define cmd_Lira_JonGuiDataLiraTarget_DEFAULT NULL

  extern const pb_msgdesc_t cmd_Lira_Root_msg;
  extern const pb_msgdesc_t cmd_Lira_Refine_target_msg;
  extern const pb_msgdesc_t cmd_Lira_JonGuiDataLiraTarget_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_Lira_Root_fields &cmd_Lira_Root_msg
#define cmd_Lira_Refine_target_fields &cmd_Lira_Refine_target_msg
#define cmd_Lira_JonGuiDataLiraTarget_fields &cmd_Lira_JonGuiDataLiraTarget_msg

/* Maximum encoded size of messages (where known) */
#define CMD_LIRA_JON_SHARED_CMD_LIRA_PB_H_MAX_SIZE cmd_Lira_Root_size
#define cmd_Lira_JonGuiDataLiraTarget_size 109
#define cmd_Lira_Refine_target_size 111
#define cmd_Lira_Root_size 113

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
