/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_JON_ARCHIVE_JON_SYCH_ARCHIVE_PB_H_INCLUDED
#define PB_JON_ARCHIVE_JON_SYCH_ARCHIVE_PB_H_INCLUDED
#include "jon_video_meta.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Entry in the archive file index, used for direct seeking to files */
typedef struct _jon_archive_ArchiveEntry
{
  /* Path within tar (e.g., "videos/001_abc.mp4") */
  pb_callback_t path;
  /* Byte offset of tar header in archive */
  uint64_t header_offset;
  /* Byte offset of file content (header_offset + 512) */
  uint64_t data_offset;
  /* File size in bytes */
  uint64_t size;
} jon_archive_ArchiveEntry;

/* Timeline index containing video entries with embedded metadata */
typedef struct _jon_archive_TimelineIndex
{
  /* Total frame count across all videos */
  uint32_t total_frames;
  /* Total duration in milliseconds */
  uint32_t total_duration_ms;
  /* Video entries in playback order */
  pb_callback_t videos;
} jon_archive_TimelineIndex;

/* Video entry with embedded metadata from jon_video_meta.proto */
typedef struct _jon_archive_VideoEntry
{
  /* Original video ID (video:session:uuid format) */
  pb_callback_t id;
  /* Path in archive (e.g., "videos/001_abc.mp4") */
  pb_callback_t archive_path;
  /* Thumbnail path in archive (optional, e.g., "thumbnails/001_abc.png") */
  pb_callback_t thumbnail_path;
  /* Start frame in global timeline */
  uint32_t global_frame_start;
  /* Embedded video metadata including sample table for frame-accurate seeking
   */
  bool has_meta;
  jon_video_VideoMeta meta;
} jon_archive_VideoEntry;

/* Reference to OSD package and config within the archive */
typedef struct _jon_archive_OSDReference
{
  /* Path to OSD package tar within archive (e.g., "osd/package.tar") */
  pb_callback_t package_path;
  /* Path to OSD config JSON within archive (e.g., "osd/config.json") */
  pb_callback_t config_path;
  /* Package metadata */
  pb_callback_t package_name;
  pb_callback_t package_version;
  /* Package variant (only recording_day supported for offline playback) */
  pb_callback_t package_variant;
} jon_archive_OSDReference;

/* Archive index - always the last entry in .sych_video tar file.
 The archive ends with an 8-byte footer:
 where block count indicates how many 1MB blocks contain the index. */
typedef struct _jon_archive_SychArchiveIndex
{
  /* Format version (currently 1) */
  uint32_t version;
  /* Unix timestamp when archive was created */
  uint64_t created_at;
  /* Origin URL for "go online" link (e.g., "https://sych.local") */
  pb_callback_t exported_from;
  /* File index with byte offsets for direct seeking */
  pb_callback_t files;
  /* Timeline data with embedded video metadata */
  bool has_timeline;
  jon_archive_TimelineIndex timeline;
  /* OSD reference (paths within archive) - optional */
  bool has_osd;
  jon_archive_OSDReference osd;
} jon_archive_SychArchiveIndex;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define jon_archive_SychArchiveIndex_init_default        \
  {                                                      \
    0, 0, { { NULL }, NULL }, { { NULL }, NULL }, false, \
      jon_archive_TimelineIndex_init_default, false,     \
      jon_archive_OSDReference_init_default              \
  }
#define jon_archive_ArchiveEntry_init_default \
  {                                           \
    { { NULL }, NULL }, 0, 0, 0               \
  }
#define jon_archive_TimelineIndex_init_default \
  {                                            \
    0, 0,                                      \
    {                                          \
      { NULL }, NULL                           \
    }                                          \
  }
#define jon_archive_VideoEntry_init_default                               \
  {                                                                       \
    { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, 0, false, \
      jon_video_VideoMeta_init_default                                    \
  }
#define jon_archive_OSDReference_init_default                   \
  {                                                             \
    { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
      { { NULL }, NULL },                                       \
    {                                                           \
      { NULL }, NULL                                            \
    }                                                           \
  }
#define jon_archive_SychArchiveIndex_init_zero           \
  {                                                      \
    0, 0, { { NULL }, NULL }, { { NULL }, NULL }, false, \
      jon_archive_TimelineIndex_init_zero, false,        \
      jon_archive_OSDReference_init_zero                 \
  }
#define jon_archive_ArchiveEntry_init_zero \
  {                                        \
    { { NULL }, NULL }, 0, 0, 0            \
  }
#define jon_archive_TimelineIndex_init_zero \
  {                                         \
    0, 0,                                   \
    {                                       \
      { NULL }, NULL                        \
    }                                       \
  }
#define jon_archive_VideoEntry_init_zero                                  \
  {                                                                       \
    { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, 0, false, \
      jon_video_VideoMeta_init_zero                                       \
  }
#define jon_archive_OSDReference_init_zero                      \
  {                                                             \
    { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
      { { NULL }, NULL },                                       \
    {                                                           \
      { NULL }, NULL                                            \
    }                                                           \
  }

/* Field tags (for use in manual encoding/decoding) */
#define jon_archive_ArchiveEntry_path_tag 1
#define jon_archive_ArchiveEntry_header_offset_tag 2
#define jon_archive_ArchiveEntry_data_offset_tag 3
#define jon_archive_ArchiveEntry_size_tag 4
#define jon_archive_TimelineIndex_total_frames_tag 1
#define jon_archive_TimelineIndex_total_duration_ms_tag 2
#define jon_archive_TimelineIndex_videos_tag 3
#define jon_archive_VideoEntry_id_tag 1
#define jon_archive_VideoEntry_archive_path_tag 2
#define jon_archive_VideoEntry_thumbnail_path_tag 3
#define jon_archive_VideoEntry_global_frame_start_tag 4
#define jon_archive_VideoEntry_meta_tag 5
#define jon_archive_OSDReference_package_path_tag 1
#define jon_archive_OSDReference_config_path_tag 2
#define jon_archive_OSDReference_package_name_tag 3
#define jon_archive_OSDReference_package_version_tag 4
#define jon_archive_OSDReference_package_variant_tag 5
#define jon_archive_SychArchiveIndex_version_tag 1
#define jon_archive_SychArchiveIndex_created_at_tag 2
#define jon_archive_SychArchiveIndex_exported_from_tag 3
#define jon_archive_SychArchiveIndex_files_tag 4
#define jon_archive_SychArchiveIndex_timeline_tag 5
#define jon_archive_SychArchiveIndex_osd_tag 6

/* Struct field encoding specification for nanopb */
#define jon_archive_SychArchiveIndex_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UINT32, version, 1)         \
  X(a, STATIC, SINGULAR, UINT64, created_at, 2)      \
  X(a, CALLBACK, SINGULAR, STRING, exported_from, 3) \
  X(a, CALLBACK, REPEATED, MESSAGE, files, 4)        \
  X(a, STATIC, OPTIONAL, MESSAGE, timeline, 5)       \
  X(a, STATIC, OPTIONAL, MESSAGE, osd, 6)
#define jon_archive_SychArchiveIndex_CALLBACK pb_default_field_callback
#define jon_archive_SychArchiveIndex_DEFAULT NULL
#define jon_archive_SychArchiveIndex_files_MSGTYPE jon_archive_ArchiveEntry
#define jon_archive_SychArchiveIndex_timeline_MSGTYPE jon_archive_TimelineIndex
#define jon_archive_SychArchiveIndex_osd_MSGTYPE jon_archive_OSDReference

#define jon_archive_ArchiveEntry_FIELDLIST(X, a)   \
  X(a, CALLBACK, SINGULAR, STRING, path, 1)        \
  X(a, STATIC, SINGULAR, UINT64, header_offset, 2) \
  X(a, STATIC, SINGULAR, UINT64, data_offset, 3)   \
  X(a, STATIC, SINGULAR, UINT64, size, 4)
#define jon_archive_ArchiveEntry_CALLBACK pb_default_field_callback
#define jon_archive_ArchiveEntry_DEFAULT NULL

#define jon_archive_TimelineIndex_FIELDLIST(X, a)      \
  X(a, STATIC, SINGULAR, UINT32, total_frames, 1)      \
  X(a, STATIC, SINGULAR, UINT32, total_duration_ms, 2) \
  X(a, CALLBACK, REPEATED, MESSAGE, videos, 3)
#define jon_archive_TimelineIndex_CALLBACK pb_default_field_callback
#define jon_archive_TimelineIndex_DEFAULT NULL
#define jon_archive_TimelineIndex_videos_MSGTYPE jon_archive_VideoEntry

#define jon_archive_VideoEntry_FIELDLIST(X, a)          \
  X(a, CALLBACK, SINGULAR, STRING, id, 1)               \
  X(a, CALLBACK, SINGULAR, STRING, archive_path, 2)     \
  X(a, CALLBACK, OPTIONAL, STRING, thumbnail_path, 3)   \
  X(a, STATIC, SINGULAR, UINT32, global_frame_start, 4) \
  X(a, STATIC, OPTIONAL, MESSAGE, meta, 5)
#define jon_archive_VideoEntry_CALLBACK pb_default_field_callback
#define jon_archive_VideoEntry_DEFAULT NULL
#define jon_archive_VideoEntry_meta_MSGTYPE jon_video_VideoMeta

#define jon_archive_OSDReference_FIELDLIST(X, a)       \
  X(a, CALLBACK, SINGULAR, STRING, package_path, 1)    \
  X(a, CALLBACK, SINGULAR, STRING, config_path, 2)     \
  X(a, CALLBACK, SINGULAR, STRING, package_name, 3)    \
  X(a, CALLBACK, SINGULAR, STRING, package_version, 4) \
  X(a, CALLBACK, SINGULAR, STRING, package_variant, 5)
#define jon_archive_OSDReference_CALLBACK pb_default_field_callback
#define jon_archive_OSDReference_DEFAULT NULL

  extern const pb_msgdesc_t jon_archive_SychArchiveIndex_msg;
  extern const pb_msgdesc_t jon_archive_ArchiveEntry_msg;
  extern const pb_msgdesc_t jon_archive_TimelineIndex_msg;
  extern const pb_msgdesc_t jon_archive_VideoEntry_msg;
  extern const pb_msgdesc_t jon_archive_OSDReference_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jon_archive_SychArchiveIndex_fields &jon_archive_SychArchiveIndex_msg
#define jon_archive_ArchiveEntry_fields &jon_archive_ArchiveEntry_msg
#define jon_archive_TimelineIndex_fields &jon_archive_TimelineIndex_msg
#define jon_archive_VideoEntry_fields &jon_archive_VideoEntry_msg
#define jon_archive_OSDReference_fields &jon_archive_OSDReference_msg

  /* Maximum encoded size of messages (where known) */
  /* jon_archive_SychArchiveIndex_size depends on runtime parameters */
  /* jon_archive_ArchiveEntry_size depends on runtime parameters */
  /* jon_archive_TimelineIndex_size depends on runtime parameters */
  /* jon_archive_VideoEntry_size depends on runtime parameters */
  /* jon_archive_OSDReference_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
