/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_can_stream.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jon_can_CANFrame, jon_can_CANFrame, AUTO)


PB_BIND(jon_can_CANFrameBatch, jon_can_CANFrameBatch, AUTO)


PB_BIND(jon_can_CANStreamConnected, jon_can_CANStreamConnected, AUTO)



