/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_video_meta.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jon_video_VideoMetaRequest, jon_video_VideoMetaRequest, AUTO)


PB_BIND(jon_video_VideoIdList, jon_video_VideoIdList, AUTO)


PB_BIND(jon_video_VideoRangeQuery, jon_video_VideoRangeQuery, AUTO)


PB_BIND(jon_video_VideoMetaResponse, jon_video_VideoMetaResponse, AUTO)


PB_BIND(jon_video_VideoMeta, jon_video_VideoMeta, AUTO)


PB_BIND(jon_video_SampleTable, jon_video_SampleTable, AUTO)


PB_BIND(jon_video_SampleToChunk, jon_video_SampleToChunk, AUTO)


PB_BIND(jon_video_VideoError, jon_video_VideoError, AUTO)





