/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_LRF_JON_SHARED_CMD_LRF_PB_H_INCLUDED
#define PB_CMD_LRF_JON_SHARED_CMD_LRF_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_Lrf_GetMeteo
{
  char dummy_field;
} cmd_Lrf_GetMeteo;

typedef struct _cmd_Lrf_Start
{
  char dummy_field;
} cmd_Lrf_Start;

typedef struct _cmd_Lrf_Stop
{
  char dummy_field;
} cmd_Lrf_Stop;

typedef struct _cmd_Lrf_Measure
{
  char dummy_field;
} cmd_Lrf_Measure;

typedef struct _cmd_Lrf_ScanOn
{
  char dummy_field;
} cmd_Lrf_ScanOn;

typedef struct _cmd_Lrf_ScanOff
{
  char dummy_field;
} cmd_Lrf_ScanOff;

typedef struct _cmd_Lrf_RefineOff
{
  char dummy_field;
} cmd_Lrf_RefineOff;

typedef struct _cmd_Lrf_RefineOn
{
  char dummy_field;
} cmd_Lrf_RefineOn;

typedef struct _cmd_Lrf_TargetDesignatorOff
{
  char dummy_field;
} cmd_Lrf_TargetDesignatorOff;

typedef struct _cmd_Lrf_TargetDesignatorOnModeA
{
  char dummy_field;
} cmd_Lrf_TargetDesignatorOnModeA;

typedef struct _cmd_Lrf_TargetDesignatorOnModeB
{
  char dummy_field;
} cmd_Lrf_TargetDesignatorOnModeB;

typedef struct _cmd_Lrf_EnableFogMode
{
  char dummy_field;
} cmd_Lrf_EnableFogMode;

typedef struct _cmd_Lrf_DisableFogMode
{
  char dummy_field;
} cmd_Lrf_DisableFogMode;

typedef struct _cmd_Lrf_SetScanMode
{
  ser_JonGuiDataLrfScanModes mode;
} cmd_Lrf_SetScanMode;

typedef struct _cmd_Lrf_NewSession
{
  char dummy_field;
} cmd_Lrf_NewSession;

typedef struct _cmd_Lrf_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_Lrf_Measure measure;
    cmd_Lrf_ScanOn scan_on;
    cmd_Lrf_ScanOff scan_off;
    cmd_Lrf_Start start;
    cmd_Lrf_Stop stop;
    cmd_Lrf_TargetDesignatorOff target_designator_off;
    cmd_Lrf_TargetDesignatorOnModeA target_designator_on_mode_a;
    cmd_Lrf_TargetDesignatorOnModeB target_designator_on_mode_b;
    cmd_Lrf_EnableFogMode enable_fog_mode;
    cmd_Lrf_DisableFogMode disable_fog_mode;
    cmd_Lrf_SetScanMode set_scan_mode;
    cmd_Lrf_NewSession new_session;
    cmd_Lrf_GetMeteo get_meteo;
    cmd_Lrf_RefineOn refine_on;
    cmd_Lrf_RefineOff refine_off;
  } cmd;
} cmd_Lrf_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_Lrf_Root_init_default  \
  {                                \
    0,                             \
    {                              \
      cmd_Lrf_Measure_init_default \
    }                              \
  }
#define cmd_Lrf_GetMeteo_init_default \
  {                                   \
    0                                 \
  }
#define cmd_Lrf_Start_init_default \
  {                                \
    0                              \
  }
#define cmd_Lrf_Stop_init_default \
  {                               \
    0                             \
  }
#define cmd_Lrf_Measure_init_default \
  {                                  \
    0                                \
  }
#define cmd_Lrf_ScanOn_init_default \
  {                                 \
    0                               \
  }
#define cmd_Lrf_ScanOff_init_default \
  {                                  \
    0                                \
  }
#define cmd_Lrf_RefineOff_init_default \
  {                                    \
    0                                  \
  }
#define cmd_Lrf_RefineOn_init_default \
  {                                   \
    0                                 \
  }
#define cmd_Lrf_TargetDesignatorOff_init_default \
  {                                              \
    0                                            \
  }
#define cmd_Lrf_TargetDesignatorOnModeA_init_default \
  {                                                  \
    0                                                \
  }
#define cmd_Lrf_TargetDesignatorOnModeB_init_default \
  {                                                  \
    0                                                \
  }
#define cmd_Lrf_EnableFogMode_init_default \
  {                                        \
    0                                      \
  }
#define cmd_Lrf_DisableFogMode_init_default \
  {                                         \
    0                                       \
  }
#define cmd_Lrf_SetScanMode_init_default \
  {                                      \
    _ser_JonGuiDataLrfScanModes_MIN      \
  }
#define cmd_Lrf_NewSession_init_default \
  {                                     \
    0                                   \
  }
#define cmd_Lrf_Root_init_zero  \
  {                             \
    0,                          \
    {                           \
      cmd_Lrf_Measure_init_zero \
    }                           \
  }
#define cmd_Lrf_GetMeteo_init_zero \
  {                                \
    0                              \
  }
#define cmd_Lrf_Start_init_zero \
  {                             \
    0                           \
  }
#define cmd_Lrf_Stop_init_zero \
  {                            \
    0                          \
  }
#define cmd_Lrf_Measure_init_zero \
  {                               \
    0                             \
  }
#define cmd_Lrf_ScanOn_init_zero \
  {                              \
    0                            \
  }
#define cmd_Lrf_ScanOff_init_zero \
  {                               \
    0                             \
  }
#define cmd_Lrf_RefineOff_init_zero \
  {                                 \
    0                               \
  }
#define cmd_Lrf_RefineOn_init_zero \
  {                                \
    0                              \
  }
#define cmd_Lrf_TargetDesignatorOff_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_Lrf_TargetDesignatorOnModeA_init_zero \
  {                                               \
    0                                             \
  }
#define cmd_Lrf_TargetDesignatorOnModeB_init_zero \
  {                                               \
    0                                             \
  }
#define cmd_Lrf_EnableFogMode_init_zero \
  {                                     \
    0                                   \
  }
#define cmd_Lrf_DisableFogMode_init_zero \
  {                                      \
    0                                    \
  }
#define cmd_Lrf_SetScanMode_init_zero \
  {                                   \
    _ser_JonGuiDataLrfScanModes_MIN   \
  }
#define cmd_Lrf_NewSession_init_zero \
  {                                  \
    0                                \
  }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_Lrf_SetScanMode_mode_tag 1
#define cmd_Lrf_Root_measure_tag 1
#define cmd_Lrf_Root_scan_on_tag 2
#define cmd_Lrf_Root_scan_off_tag 3
#define cmd_Lrf_Root_start_tag 4
#define cmd_Lrf_Root_stop_tag 5
#define cmd_Lrf_Root_target_designator_off_tag 6
#define cmd_Lrf_Root_target_designator_on_mode_a_tag 7
#define cmd_Lrf_Root_target_designator_on_mode_b_tag 8
#define cmd_Lrf_Root_enable_fog_mode_tag 9
#define cmd_Lrf_Root_disable_fog_mode_tag 10
#define cmd_Lrf_Root_set_scan_mode_tag 11
#define cmd_Lrf_Root_new_session_tag 12
#define cmd_Lrf_Root_get_meteo_tag 13
#define cmd_Lrf_Root_refine_on_tag 14
#define cmd_Lrf_Root_refine_off_tag 15

/* Struct field encoding specification for nanopb */
#define cmd_Lrf_Root_FIELDLIST(X, a)                                           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, measure, cmd.measure), 1)                 \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_on, cmd.scan_on), 2)                 \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_off, cmd.scan_off), 3)               \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start, cmd.start), 4)                     \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop, cmd.stop), 5)                       \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, target_designator_off, cmd.target_designator_off), 6)                \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, target_designator_on_mode_a, cmd.target_designator_on_mode_a), 7)    \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, target_designator_on_mode_b, cmd.target_designator_on_mode_b), 8)    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, enable_fog_mode, cmd.enable_fog_mode), 9) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, disable_fog_mode, cmd.disable_fog_mode),  \
    10)                                                                        \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_scan_mode, cmd.set_scan_mode), 11)    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, new_session, cmd.new_session), 12)        \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, get_meteo, cmd.get_meteo), 13)            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, refine_on, cmd.refine_on), 14)            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, refine_off, cmd.refine_off), 15)
#define cmd_Lrf_Root_CALLBACK NULL
#define cmd_Lrf_Root_DEFAULT NULL
#define cmd_Lrf_Root_cmd_measure_MSGTYPE cmd_Lrf_Measure
#define cmd_Lrf_Root_cmd_scan_on_MSGTYPE cmd_Lrf_ScanOn
#define cmd_Lrf_Root_cmd_scan_off_MSGTYPE cmd_Lrf_ScanOff
#define cmd_Lrf_Root_cmd_start_MSGTYPE cmd_Lrf_Start
#define cmd_Lrf_Root_cmd_stop_MSGTYPE cmd_Lrf_Stop
#define cmd_Lrf_Root_cmd_target_designator_off_MSGTYPE \
  cmd_Lrf_TargetDesignatorOff
#define cmd_Lrf_Root_cmd_target_designator_on_mode_a_MSGTYPE \
  cmd_Lrf_TargetDesignatorOnModeA
#define cmd_Lrf_Root_cmd_target_designator_on_mode_b_MSGTYPE \
  cmd_Lrf_TargetDesignatorOnModeB
#define cmd_Lrf_Root_cmd_enable_fog_mode_MSGTYPE cmd_Lrf_EnableFogMode
#define cmd_Lrf_Root_cmd_disable_fog_mode_MSGTYPE cmd_Lrf_DisableFogMode
#define cmd_Lrf_Root_cmd_set_scan_mode_MSGTYPE cmd_Lrf_SetScanMode
#define cmd_Lrf_Root_cmd_new_session_MSGTYPE cmd_Lrf_NewSession
#define cmd_Lrf_Root_cmd_get_meteo_MSGTYPE cmd_Lrf_GetMeteo
#define cmd_Lrf_Root_cmd_refine_on_MSGTYPE cmd_Lrf_RefineOn
#define cmd_Lrf_Root_cmd_refine_off_MSGTYPE cmd_Lrf_RefineOff

#define cmd_Lrf_GetMeteo_FIELDLIST(X, a)

#define cmd_Lrf_GetMeteo_CALLBACK NULL
#define cmd_Lrf_GetMeteo_DEFAULT NULL

#define cmd_Lrf_Start_FIELDLIST(X, a)

#define cmd_Lrf_Start_CALLBACK NULL
#define cmd_Lrf_Start_DEFAULT NULL

#define cmd_Lrf_Stop_FIELDLIST(X, a)

#define cmd_Lrf_Stop_CALLBACK NULL
#define cmd_Lrf_Stop_DEFAULT NULL

#define cmd_Lrf_Measure_FIELDLIST(X, a)

#define cmd_Lrf_Measure_CALLBACK NULL
#define cmd_Lrf_Measure_DEFAULT NULL

#define cmd_Lrf_ScanOn_FIELDLIST(X, a)

#define cmd_Lrf_ScanOn_CALLBACK NULL
#define cmd_Lrf_ScanOn_DEFAULT NULL

#define cmd_Lrf_ScanOff_FIELDLIST(X, a)

#define cmd_Lrf_ScanOff_CALLBACK NULL
#define cmd_Lrf_ScanOff_DEFAULT NULL

#define cmd_Lrf_RefineOff_FIELDLIST(X, a)

#define cmd_Lrf_RefineOff_CALLBACK NULL
#define cmd_Lrf_RefineOff_DEFAULT NULL

#define cmd_Lrf_RefineOn_FIELDLIST(X, a)

#define cmd_Lrf_RefineOn_CALLBACK NULL
#define cmd_Lrf_RefineOn_DEFAULT NULL

#define cmd_Lrf_TargetDesignatorOff_FIELDLIST(X, a)

#define cmd_Lrf_TargetDesignatorOff_CALLBACK NULL
#define cmd_Lrf_TargetDesignatorOff_DEFAULT NULL

#define cmd_Lrf_TargetDesignatorOnModeA_FIELDLIST(X, a)

#define cmd_Lrf_TargetDesignatorOnModeA_CALLBACK NULL
#define cmd_Lrf_TargetDesignatorOnModeA_DEFAULT NULL

#define cmd_Lrf_TargetDesignatorOnModeB_FIELDLIST(X, a)

#define cmd_Lrf_TargetDesignatorOnModeB_CALLBACK NULL
#define cmd_Lrf_TargetDesignatorOnModeB_DEFAULT NULL

#define cmd_Lrf_EnableFogMode_FIELDLIST(X, a)

#define cmd_Lrf_EnableFogMode_CALLBACK NULL
#define cmd_Lrf_EnableFogMode_DEFAULT NULL

#define cmd_Lrf_DisableFogMode_FIELDLIST(X, a)

#define cmd_Lrf_DisableFogMode_CALLBACK NULL
#define cmd_Lrf_DisableFogMode_DEFAULT NULL

#define cmd_Lrf_SetScanMode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, mode, 1)
#define cmd_Lrf_SetScanMode_CALLBACK NULL
#define cmd_Lrf_SetScanMode_DEFAULT NULL

#define cmd_Lrf_NewSession_FIELDLIST(X, a)

#define cmd_Lrf_NewSession_CALLBACK NULL
#define cmd_Lrf_NewSession_DEFAULT NULL

  extern const pb_msgdesc_t cmd_Lrf_Root_msg;
  extern const pb_msgdesc_t cmd_Lrf_GetMeteo_msg;
  extern const pb_msgdesc_t cmd_Lrf_Start_msg;
  extern const pb_msgdesc_t cmd_Lrf_Stop_msg;
  extern const pb_msgdesc_t cmd_Lrf_Measure_msg;
  extern const pb_msgdesc_t cmd_Lrf_ScanOn_msg;
  extern const pb_msgdesc_t cmd_Lrf_ScanOff_msg;
  extern const pb_msgdesc_t cmd_Lrf_RefineOff_msg;
  extern const pb_msgdesc_t cmd_Lrf_RefineOn_msg;
  extern const pb_msgdesc_t cmd_Lrf_TargetDesignatorOff_msg;
  extern const pb_msgdesc_t cmd_Lrf_TargetDesignatorOnModeA_msg;
  extern const pb_msgdesc_t cmd_Lrf_TargetDesignatorOnModeB_msg;
  extern const pb_msgdesc_t cmd_Lrf_EnableFogMode_msg;
  extern const pb_msgdesc_t cmd_Lrf_DisableFogMode_msg;
  extern const pb_msgdesc_t cmd_Lrf_SetScanMode_msg;
  extern const pb_msgdesc_t cmd_Lrf_NewSession_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_Lrf_Root_fields &cmd_Lrf_Root_msg
#define cmd_Lrf_GetMeteo_fields &cmd_Lrf_GetMeteo_msg
#define cmd_Lrf_Start_fields &cmd_Lrf_Start_msg
#define cmd_Lrf_Stop_fields &cmd_Lrf_Stop_msg
#define cmd_Lrf_Measure_fields &cmd_Lrf_Measure_msg
#define cmd_Lrf_ScanOn_fields &cmd_Lrf_ScanOn_msg
#define cmd_Lrf_ScanOff_fields &cmd_Lrf_ScanOff_msg
#define cmd_Lrf_RefineOff_fields &cmd_Lrf_RefineOff_msg
#define cmd_Lrf_RefineOn_fields &cmd_Lrf_RefineOn_msg
#define cmd_Lrf_TargetDesignatorOff_fields &cmd_Lrf_TargetDesignatorOff_msg
#define cmd_Lrf_TargetDesignatorOnModeA_fields \
  &cmd_Lrf_TargetDesignatorOnModeA_msg
#define cmd_Lrf_TargetDesignatorOnModeB_fields \
  &cmd_Lrf_TargetDesignatorOnModeB_msg
#define cmd_Lrf_EnableFogMode_fields &cmd_Lrf_EnableFogMode_msg
#define cmd_Lrf_DisableFogMode_fields &cmd_Lrf_DisableFogMode_msg
#define cmd_Lrf_SetScanMode_fields &cmd_Lrf_SetScanMode_msg
#define cmd_Lrf_NewSession_fields &cmd_Lrf_NewSession_msg

/* Maximum encoded size of messages (where known) */
#define CMD_LRF_JON_SHARED_CMD_LRF_PB_H_MAX_SIZE cmd_Lrf_Root_size
#define cmd_Lrf_DisableFogMode_size 0
#define cmd_Lrf_EnableFogMode_size 0
#define cmd_Lrf_GetMeteo_size 0
#define cmd_Lrf_Measure_size 0
#define cmd_Lrf_NewSession_size 0
#define cmd_Lrf_RefineOff_size 0
#define cmd_Lrf_RefineOn_size 0
#define cmd_Lrf_Root_size 4
#define cmd_Lrf_ScanOff_size 0
#define cmd_Lrf_ScanOn_size 0
#define cmd_Lrf_SetScanMode_size 2
#define cmd_Lrf_Start_size 0
#define cmd_Lrf_Stop_size 0
#define cmd_Lrf_TargetDesignatorOff_size 0
#define cmd_Lrf_TargetDesignatorOnModeA_size 0
#define cmd_Lrf_TargetDesignatorOnModeB_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
