/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_COMPASS_JON_SHARED_CMD_COMPASS_PB_H_INCLUDED
#define PB_CMD_COMPASS_JON_SHARED_CMD_COMPASS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_Compass_Start
{
  char dummy_field;
} cmd_Compass_Start;

typedef struct _cmd_Compass_Stop
{
  char dummy_field;
} cmd_Compass_Stop;

typedef struct _cmd_Compass_Next
{
  char dummy_field;
} cmd_Compass_Next;

typedef struct _cmd_Compass_CalibrateStartLong
{
  char dummy_field;
} cmd_Compass_CalibrateStartLong;

typedef struct _cmd_Compass_CalibrateStartShort
{
  char dummy_field;
} cmd_Compass_CalibrateStartShort;

typedef struct _cmd_Compass_CalibrateNext
{
  char dummy_field;
} cmd_Compass_CalibrateNext;

typedef struct _cmd_Compass_CalibrateCencel
{
  char dummy_field;
} cmd_Compass_CalibrateCencel;

typedef struct _cmd_Compass_GetMeteo
{
  char dummy_field;
} cmd_Compass_GetMeteo;

typedef struct _cmd_Compass_SetMagneticDeclination
{
  double value;
} cmd_Compass_SetMagneticDeclination;

typedef struct _cmd_Compass_SetOffsetAngleAzimuth
{
  double value;
} cmd_Compass_SetOffsetAngleAzimuth;

typedef struct _cmd_Compass_SetOffsetAngleElevation
{
  double value;
} cmd_Compass_SetOffsetAngleElevation;

typedef struct _cmd_Compass_SetUseRotaryPosition
{
  bool flag;
} cmd_Compass_SetUseRotaryPosition;

typedef struct _cmd_Compass_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_Compass_Start start;
    cmd_Compass_Stop stop;
    cmd_Compass_SetMagneticDeclination set_magnetic_declination;
    cmd_Compass_SetOffsetAngleAzimuth set_offset_angle_azimuth;
    cmd_Compass_SetOffsetAngleElevation set_offset_angle_elevation;
    cmd_Compass_SetUseRotaryPosition set_use_rotary_position;
    cmd_Compass_CalibrateStartLong start_calibrate_long;
    cmd_Compass_CalibrateStartShort start_calibrate_short;
    cmd_Compass_CalibrateNext calibrate_next;
    cmd_Compass_CalibrateCencel calibrate_cencel;
    cmd_Compass_GetMeteo get_meteo;
  } cmd;
} cmd_Compass_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_Compass_Root_init_default \
  {                                   \
    0,                                \
    {                                 \
      cmd_Compass_Start_init_default  \
    }                                 \
  }
#define cmd_Compass_Start_init_default \
  {                                    \
    0                                  \
  }
#define cmd_Compass_Stop_init_default \
  {                                   \
    0                                 \
  }
#define cmd_Compass_Next_init_default \
  {                                   \
    0                                 \
  }
#define cmd_Compass_CalibrateStartLong_init_default \
  {                                                 \
    0                                               \
  }
#define cmd_Compass_CalibrateStartShort_init_default \
  {                                                  \
    0                                                \
  }
#define cmd_Compass_CalibrateNext_init_default \
  {                                            \
    0                                          \
  }
#define cmd_Compass_CalibrateCencel_init_default \
  {                                              \
    0                                            \
  }
#define cmd_Compass_GetMeteo_init_default \
  {                                       \
    0                                     \
  }
#define cmd_Compass_SetMagneticDeclination_init_default \
  {                                                     \
    0                                                   \
  }
#define cmd_Compass_SetOffsetAngleAzimuth_init_default \
  {                                                    \
    0                                                  \
  }
#define cmd_Compass_SetOffsetAngleElevation_init_default \
  {                                                      \
    0                                                    \
  }
#define cmd_Compass_SetUseRotaryPosition_init_default \
  {                                                   \
    0                                                 \
  }
#define cmd_Compass_Root_init_zero \
  {                                \
    0,                             \
    {                              \
      cmd_Compass_Start_init_zero  \
    }                              \
  }
#define cmd_Compass_Start_init_zero \
  {                                 \
    0                               \
  }
#define cmd_Compass_Stop_init_zero \
  {                                \
    0                              \
  }
#define cmd_Compass_Next_init_zero \
  {                                \
    0                              \
  }
#define cmd_Compass_CalibrateStartLong_init_zero \
  {                                              \
    0                                            \
  }
#define cmd_Compass_CalibrateStartShort_init_zero \
  {                                               \
    0                                             \
  }
#define cmd_Compass_CalibrateNext_init_zero \
  {                                         \
    0                                       \
  }
#define cmd_Compass_CalibrateCencel_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_Compass_GetMeteo_init_zero \
  {                                    \
    0                                  \
  }
#define cmd_Compass_SetMagneticDeclination_init_zero \
  {                                                  \
    0                                                \
  }
#define cmd_Compass_SetOffsetAngleAzimuth_init_zero \
  {                                                 \
    0                                               \
  }
#define cmd_Compass_SetOffsetAngleElevation_init_zero \
  {                                                   \
    0                                                 \
  }
#define cmd_Compass_SetUseRotaryPosition_init_zero \
  {                                                \
    0                                              \
  }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_Compass_SetMagneticDeclination_value_tag 1
#define cmd_Compass_SetOffsetAngleAzimuth_value_tag 1
#define cmd_Compass_SetOffsetAngleElevation_value_tag 1
#define cmd_Compass_SetUseRotaryPosition_flag_tag 1
#define cmd_Compass_Root_start_tag 1
#define cmd_Compass_Root_stop_tag 2
#define cmd_Compass_Root_set_magnetic_declination_tag 3
#define cmd_Compass_Root_set_offset_angle_azimuth_tag 4
#define cmd_Compass_Root_set_offset_angle_elevation_tag 5
#define cmd_Compass_Root_set_use_rotary_position_tag 6
#define cmd_Compass_Root_start_calibrate_long_tag 7
#define cmd_Compass_Root_start_calibrate_short_tag 8
#define cmd_Compass_Root_calibrate_next_tag 9
#define cmd_Compass_Root_calibrate_cencel_tag 10
#define cmd_Compass_Root_get_meteo_tag 11

/* Struct field encoding specification for nanopb */
#define cmd_Compass_Root_FIELDLIST(X, a)                                      \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start, cmd.start), 1)                    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop, cmd.stop), 2)                      \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_magnetic_declination, cmd.set_magnetic_declination), 3)         \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_offset_angle_azimuth, cmd.set_offset_angle_azimuth), 4)         \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_offset_angle_elevation, cmd.set_offset_angle_elevation), 5)     \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_use_rotary_position, cmd.set_use_rotary_position), 6)           \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, start_calibrate_long, cmd.start_calibrate_long), 7)                 \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, start_calibrate_short, cmd.start_calibrate_short), 8)               \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, calibrate_next, cmd.calibrate_next), 9)  \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, calibrate_cencel, cmd.calibrate_cencel), \
    10)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, get_meteo, cmd.get_meteo), 11)
#define cmd_Compass_Root_CALLBACK NULL
#define cmd_Compass_Root_DEFAULT NULL
#define cmd_Compass_Root_cmd_start_MSGTYPE cmd_Compass_Start
#define cmd_Compass_Root_cmd_stop_MSGTYPE cmd_Compass_Stop
#define cmd_Compass_Root_cmd_set_magnetic_declination_MSGTYPE \
  cmd_Compass_SetMagneticDeclination
#define cmd_Compass_Root_cmd_set_offset_angle_azimuth_MSGTYPE \
  cmd_Compass_SetOffsetAngleAzimuth
#define cmd_Compass_Root_cmd_set_offset_angle_elevation_MSGTYPE \
  cmd_Compass_SetOffsetAngleElevation
#define cmd_Compass_Root_cmd_set_use_rotary_position_MSGTYPE \
  cmd_Compass_SetUseRotaryPosition
#define cmd_Compass_Root_cmd_start_calibrate_long_MSGTYPE \
  cmd_Compass_CalibrateStartLong
#define cmd_Compass_Root_cmd_start_calibrate_short_MSGTYPE \
  cmd_Compass_CalibrateStartShort
#define cmd_Compass_Root_cmd_calibrate_next_MSGTYPE cmd_Compass_CalibrateNext
#define cmd_Compass_Root_cmd_calibrate_cencel_MSGTYPE \
  cmd_Compass_CalibrateCencel
#define cmd_Compass_Root_cmd_get_meteo_MSGTYPE cmd_Compass_GetMeteo

#define cmd_Compass_Start_FIELDLIST(X, a)

#define cmd_Compass_Start_CALLBACK NULL
#define cmd_Compass_Start_DEFAULT NULL

#define cmd_Compass_Stop_FIELDLIST(X, a)

#define cmd_Compass_Stop_CALLBACK NULL
#define cmd_Compass_Stop_DEFAULT NULL

#define cmd_Compass_Next_FIELDLIST(X, a)

#define cmd_Compass_Next_CALLBACK NULL
#define cmd_Compass_Next_DEFAULT NULL

#define cmd_Compass_CalibrateStartLong_FIELDLIST(X, a)

#define cmd_Compass_CalibrateStartLong_CALLBACK NULL
#define cmd_Compass_CalibrateStartLong_DEFAULT NULL

#define cmd_Compass_CalibrateStartShort_FIELDLIST(X, a)

#define cmd_Compass_CalibrateStartShort_CALLBACK NULL
#define cmd_Compass_CalibrateStartShort_DEFAULT NULL

#define cmd_Compass_CalibrateNext_FIELDLIST(X, a)

#define cmd_Compass_CalibrateNext_CALLBACK NULL
#define cmd_Compass_CalibrateNext_DEFAULT NULL

#define cmd_Compass_CalibrateCencel_FIELDLIST(X, a)

#define cmd_Compass_CalibrateCencel_CALLBACK NULL
#define cmd_Compass_CalibrateCencel_DEFAULT NULL

#define cmd_Compass_GetMeteo_FIELDLIST(X, a)

#define cmd_Compass_GetMeteo_CALLBACK NULL
#define cmd_Compass_GetMeteo_DEFAULT NULL

#define cmd_Compass_SetMagneticDeclination_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_Compass_SetMagneticDeclination_CALLBACK NULL
#define cmd_Compass_SetMagneticDeclination_DEFAULT NULL

#define cmd_Compass_SetOffsetAngleAzimuth_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_Compass_SetOffsetAngleAzimuth_CALLBACK NULL
#define cmd_Compass_SetOffsetAngleAzimuth_DEFAULT NULL

#define cmd_Compass_SetOffsetAngleElevation_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_Compass_SetOffsetAngleElevation_CALLBACK NULL
#define cmd_Compass_SetOffsetAngleElevation_DEFAULT NULL

#define cmd_Compass_SetUseRotaryPosition_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, BOOL, flag, 1)
#define cmd_Compass_SetUseRotaryPosition_CALLBACK NULL
#define cmd_Compass_SetUseRotaryPosition_DEFAULT NULL

  extern const pb_msgdesc_t cmd_Compass_Root_msg;
  extern const pb_msgdesc_t cmd_Compass_Start_msg;
  extern const pb_msgdesc_t cmd_Compass_Stop_msg;
  extern const pb_msgdesc_t cmd_Compass_Next_msg;
  extern const pb_msgdesc_t cmd_Compass_CalibrateStartLong_msg;
  extern const pb_msgdesc_t cmd_Compass_CalibrateStartShort_msg;
  extern const pb_msgdesc_t cmd_Compass_CalibrateNext_msg;
  extern const pb_msgdesc_t cmd_Compass_CalibrateCencel_msg;
  extern const pb_msgdesc_t cmd_Compass_GetMeteo_msg;
  extern const pb_msgdesc_t cmd_Compass_SetMagneticDeclination_msg;
  extern const pb_msgdesc_t cmd_Compass_SetOffsetAngleAzimuth_msg;
  extern const pb_msgdesc_t cmd_Compass_SetOffsetAngleElevation_msg;
  extern const pb_msgdesc_t cmd_Compass_SetUseRotaryPosition_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_Compass_Root_fields &cmd_Compass_Root_msg
#define cmd_Compass_Start_fields &cmd_Compass_Start_msg
#define cmd_Compass_Stop_fields &cmd_Compass_Stop_msg
#define cmd_Compass_Next_fields &cmd_Compass_Next_msg
#define cmd_Compass_CalibrateStartLong_fields \
  &cmd_Compass_CalibrateStartLong_msg
#define cmd_Compass_CalibrateStartShort_fields \
  &cmd_Compass_CalibrateStartShort_msg
#define cmd_Compass_CalibrateNext_fields &cmd_Compass_CalibrateNext_msg
#define cmd_Compass_CalibrateCencel_fields &cmd_Compass_CalibrateCencel_msg
#define cmd_Compass_GetMeteo_fields &cmd_Compass_GetMeteo_msg
#define cmd_Compass_SetMagneticDeclination_fields \
  &cmd_Compass_SetMagneticDeclination_msg
#define cmd_Compass_SetOffsetAngleAzimuth_fields \
  &cmd_Compass_SetOffsetAngleAzimuth_msg
#define cmd_Compass_SetOffsetAngleElevation_fields \
  &cmd_Compass_SetOffsetAngleElevation_msg
#define cmd_Compass_SetUseRotaryPosition_fields \
  &cmd_Compass_SetUseRotaryPosition_msg

/* Maximum encoded size of messages (where known) */
#define CMD_COMPASS_JON_SHARED_CMD_COMPASS_PB_H_MAX_SIZE cmd_Compass_Root_size
#define cmd_Compass_CalibrateCencel_size 0
#define cmd_Compass_CalibrateNext_size 0
#define cmd_Compass_CalibrateStartLong_size 0
#define cmd_Compass_CalibrateStartShort_size 0
#define cmd_Compass_GetMeteo_size 0
#define cmd_Compass_Next_size 0
#define cmd_Compass_Root_size 11
#define cmd_Compass_SetMagneticDeclination_size 9
#define cmd_Compass_SetOffsetAngleAzimuth_size 9
#define cmd_Compass_SetOffsetAngleElevation_size 9
#define cmd_Compass_SetUseRotaryPosition_size 2
#define cmd_Compass_Start_size 0
#define cmd_Compass_Stop_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
