/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_JON_SHARED_CMD_PB_H_INCLUDED
#define PB_CMD_JON_SHARED_CMD_PB_H_INCLUDED
#include <pb.h>
#include "jon_shared_cmd_compass.pb.h"
#include "jon_shared_cmd_gps.pb.h"
#include "jon_shared_cmd_lrf.pb.h"
#include "jon_shared_cmd_day_camera.pb.h"
#include "jon_shared_cmd_heat_camera.pb.h"
#include "jon_shared_cmd_rotary.pb.h"
#include "jon_shared_cmd_osd.pb.h"
#include "jon_shared_cmd_lrf_align.pb.h"
#include "jon_shared_cmd_system.pb.h"
#include "jon_shared_cmd_cv.pb.h"
#include "jon_shared_cmd_day_cam_glass_heater.pb.h"
#include "jon_shared_cmd_lira.pb.h"
#include "jon_shared_cmd_power.pb.h"
#include "jon_shared_data_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_Ping {
    char dummy_field;
} cmd_Ping;

typedef struct _cmd_Noop {
    char dummy_field;
} cmd_Noop;

typedef struct _cmd_Frozen {
    char dummy_field;
} cmd_Frozen;

typedef struct _cmd_Root {
    uint32_t protocol_version;
    uint32_t session_id;
    bool important;
    bool from_cv_subsystem;
    ser_JonGuiDataClientType client_type;
    /* Frame timestamps (PTS) from video streams when command was issued */
    uint64_t frame_time_day; /* Day camera frame timestamp (nanoseconds) */
    uint64_t frame_time_heat; /* Thermal camera frame timestamp (nanoseconds) */
    /* System monotonic time when user performed action */
    uint64_t state_time; /* System monotonic time (nanoseconds) */
    /* Client wall-clock time when command was issued */
    uint64_t client_time_ms; /* Client epoch time in milliseconds (from performance.timeOrigin + performance.now()) */
    ser_JonGuiDataClientApp client_app;
    /* Opaque payloads for subsystem-specific extensions */
    pb_callback_t opaque_payloads;
    pb_size_t which_payload;
    union {
        cmd_DayCamera_Root day_camera;
        cmd_HeatCamera_Root heat_camera;
        cmd_Gps_Root gps;
        cmd_Compass_Root compass;
        cmd_Lrf_Root lrf;
        cmd_Lrf_calib_Root lrf_calib;
        cmd_RotaryPlatform_Root rotary;
        cmd_OSD_Root osd;
        cmd_Ping ping;
        cmd_Noop noop;
        cmd_Frozen frozen;
        cmd_System_Root system;
        cmd_CV_Root cv;
        cmd_DayCamGlassHeater_Root day_cam_glass_heater;
        cmd_Lira_Root lira;
        cmd_Power_Root power;
    } payload;
} cmd_Root;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cmd_Root_init_default                    {0, 0, 0, 0, _ser_JonGuiDataClientType_MIN, 0, 0, 0, 0, _ser_JonGuiDataClientApp_MIN, {{NULL}, NULL}, 0, {cmd_DayCamera_Root_init_default}}
#define cmd_Ping_init_default                    {0}
#define cmd_Noop_init_default                    {0}
#define cmd_Frozen_init_default                  {0}
#define cmd_Root_init_zero                       {0, 0, 0, 0, _ser_JonGuiDataClientType_MIN, 0, 0, 0, 0, _ser_JonGuiDataClientApp_MIN, {{NULL}, NULL}, 0, {cmd_DayCamera_Root_init_zero}}
#define cmd_Ping_init_zero                       {0}
#define cmd_Noop_init_zero                       {0}
#define cmd_Frozen_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define cmd_Root_protocol_version_tag            1
#define cmd_Root_session_id_tag                  2
#define cmd_Root_important_tag                   3
#define cmd_Root_from_cv_subsystem_tag           4
#define cmd_Root_client_type_tag                 5
#define cmd_Root_frame_time_day_tag              6
#define cmd_Root_frame_time_heat_tag             7
#define cmd_Root_state_time_tag                  8
#define cmd_Root_client_time_ms_tag              9
#define cmd_Root_client_app_tag                  10
#define cmd_Root_opaque_payloads_tag             11
#define cmd_Root_day_camera_tag                  20
#define cmd_Root_heat_camera_tag                 21
#define cmd_Root_gps_tag                         22
#define cmd_Root_compass_tag                     23
#define cmd_Root_lrf_tag                         24
#define cmd_Root_lrf_calib_tag                   25
#define cmd_Root_rotary_tag                      26
#define cmd_Root_osd_tag                         27
#define cmd_Root_ping_tag                        28
#define cmd_Root_noop_tag                        29
#define cmd_Root_frozen_tag                      30
#define cmd_Root_system_tag                      31
#define cmd_Root_cv_tag                          32
#define cmd_Root_day_cam_glass_heater_tag        33
#define cmd_Root_lira_tag                        34
#define cmd_Root_power_tag                       35

/* Struct field encoding specification for nanopb */
#define cmd_Root_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        2) \
X(a, STATIC,   SINGULAR, BOOL,     important,         3) \
X(a, STATIC,   SINGULAR, BOOL,     from_cv_subsystem,   4) \
X(a, STATIC,   SINGULAR, UENUM,    client_type,       5) \
X(a, STATIC,   SINGULAR, UINT64,   frame_time_day,    6) \
X(a, STATIC,   SINGULAR, UINT64,   frame_time_heat,   7) \
X(a, STATIC,   SINGULAR, UINT64,   state_time,        8) \
X(a, STATIC,   SINGULAR, UINT64,   client_time_ms,    9) \
X(a, STATIC,   SINGULAR, UENUM,    client_app,       10) \
X(a, CALLBACK, REPEATED, MESSAGE,  opaque_payloads,  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,day_camera,payload.day_camera),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heat_camera,payload.heat_camera),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gps,payload.gps),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,compass,payload.compass),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,lrf,payload.lrf),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,lrf_calib,payload.lrf_calib),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rotary,payload.rotary),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,osd,payload.osd),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ping,payload.ping),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,noop,payload.noop),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,frozen,payload.frozen),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system,payload.system),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cv,payload.cv),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,day_cam_glass_heater,payload.day_cam_glass_heater),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,lira,payload.lira),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,power,payload.power),  35)
#define cmd_Root_CALLBACK pb_default_field_callback
#define cmd_Root_DEFAULT NULL
#define cmd_Root_opaque_payloads_MSGTYPE ser_JonOpaquePayload
#define cmd_Root_payload_day_camera_MSGTYPE cmd_DayCamera_Root
#define cmd_Root_payload_heat_camera_MSGTYPE cmd_HeatCamera_Root
#define cmd_Root_payload_gps_MSGTYPE cmd_Gps_Root
#define cmd_Root_payload_compass_MSGTYPE cmd_Compass_Root
#define cmd_Root_payload_lrf_MSGTYPE cmd_Lrf_Root
#define cmd_Root_payload_lrf_calib_MSGTYPE cmd_Lrf_calib_Root
#define cmd_Root_payload_rotary_MSGTYPE cmd_RotaryPlatform_Root
#define cmd_Root_payload_osd_MSGTYPE cmd_OSD_Root
#define cmd_Root_payload_ping_MSGTYPE cmd_Ping
#define cmd_Root_payload_noop_MSGTYPE cmd_Noop
#define cmd_Root_payload_frozen_MSGTYPE cmd_Frozen
#define cmd_Root_payload_system_MSGTYPE cmd_System_Root
#define cmd_Root_payload_cv_MSGTYPE cmd_CV_Root
#define cmd_Root_payload_day_cam_glass_heater_MSGTYPE cmd_DayCamGlassHeater_Root
#define cmd_Root_payload_lira_MSGTYPE cmd_Lira_Root
#define cmd_Root_payload_power_MSGTYPE cmd_Power_Root

#define cmd_Ping_FIELDLIST(X, a) \

#define cmd_Ping_CALLBACK NULL
#define cmd_Ping_DEFAULT NULL

#define cmd_Noop_FIELDLIST(X, a) \

#define cmd_Noop_CALLBACK NULL
#define cmd_Noop_DEFAULT NULL

#define cmd_Frozen_FIELDLIST(X, a) \

#define cmd_Frozen_CALLBACK NULL
#define cmd_Frozen_DEFAULT NULL

extern const pb_msgdesc_t cmd_Root_msg;
extern const pb_msgdesc_t cmd_Ping_msg;
extern const pb_msgdesc_t cmd_Noop_msg;
extern const pb_msgdesc_t cmd_Frozen_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_Root_fields &cmd_Root_msg
#define cmd_Ping_fields &cmd_Ping_msg
#define cmd_Noop_fields &cmd_Noop_msg
#define cmd_Frozen_fields &cmd_Frozen_msg

/* Maximum encoded size of messages (where known) */
/* cmd_Root_size depends on runtime parameters */
#define cmd_Frozen_size                          0
#define cmd_Noop_size                            0
#define cmd_Ping_size                            0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
