/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_REC_OSD_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_REC_OSD_PB_H_INCLUDED
#include <pb.h>
#include "jon_shared_data_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ser_JonGuiDataRecOsd {
    ser_JonGuiDataRecOsdScreen screen;
    bool heat_osd_enabled;
    bool day_osd_enabled;
    int32_t heat_crosshair_offset_horizontal;
    int32_t heat_crosshair_offset_vertical;
    int32_t day_crosshair_offset_horizontal;
    int32_t day_crosshair_offset_vertical;
} ser_JonGuiDataRecOsd;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataRecOsd_init_default        {_ser_JonGuiDataRecOsdScreen_MIN, 0, 0, 0, 0, 0, 0}
#define ser_JonGuiDataRecOsd_init_zero           {_ser_JonGuiDataRecOsdScreen_MIN, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataRecOsd_screen_tag          1
#define ser_JonGuiDataRecOsd_heat_osd_enabled_tag 2
#define ser_JonGuiDataRecOsd_day_osd_enabled_tag 3
#define ser_JonGuiDataRecOsd_heat_crosshair_offset_horizontal_tag 4
#define ser_JonGuiDataRecOsd_heat_crosshair_offset_vertical_tag 5
#define ser_JonGuiDataRecOsd_day_crosshair_offset_horizontal_tag 6
#define ser_JonGuiDataRecOsd_day_crosshair_offset_vertical_tag 7

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataRecOsd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    screen,            1) \
X(a, STATIC,   SINGULAR, BOOL,     heat_osd_enabled,   2) \
X(a, STATIC,   SINGULAR, BOOL,     day_osd_enabled,   3) \
X(a, STATIC,   SINGULAR, INT32,    heat_crosshair_offset_horizontal,   4) \
X(a, STATIC,   SINGULAR, INT32,    heat_crosshair_offset_vertical,   5) \
X(a, STATIC,   SINGULAR, INT32,    day_crosshair_offset_horizontal,   6) \
X(a, STATIC,   SINGULAR, INT32,    day_crosshair_offset_vertical,   7)
#define ser_JonGuiDataRecOsd_CALLBACK NULL
#define ser_JonGuiDataRecOsd_DEFAULT NULL

extern const pb_msgdesc_t ser_JonGuiDataRecOsd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataRecOsd_fields &ser_JonGuiDataRecOsd_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_REC_OSD_PB_H_MAX_SIZE ser_JonGuiDataRecOsd_size
#define ser_JonGuiDataRecOsd_size                50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
