/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_HEATCAMERA_JON_SHARED_CMD_HEAT_CAMERA_PB_H_INCLUDED
#define PB_CMD_HEATCAMERA_JON_SHARED_CMD_HEAT_CAMERA_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_HeatCamera_SetFxMode
{
  ser_JonGuiDataFxModeHeat mode;
} cmd_HeatCamera_SetFxMode;

typedef struct _cmd_HeatCamera_SetClaheLevel
{
  double value;
} cmd_HeatCamera_SetClaheLevel;

typedef struct _cmd_HeatCamera_ShiftClaheLevel
{
  double value;
} cmd_HeatCamera_ShiftClaheLevel;

typedef struct _cmd_HeatCamera_NextFxMode
{
  char dummy_field;
} cmd_HeatCamera_NextFxMode;

typedef struct _cmd_HeatCamera_PrevFxMode
{
  char dummy_field;
} cmd_HeatCamera_PrevFxMode;

typedef struct _cmd_HeatCamera_RefreshFxMode
{
  char dummy_field;
} cmd_HeatCamera_RefreshFxMode;

typedef struct _cmd_HeatCamera_EnableDDE
{
  char dummy_field;
} cmd_HeatCamera_EnableDDE;

typedef struct _cmd_HeatCamera_DisableDDE
{
  char dummy_field;
} cmd_HeatCamera_DisableDDE;

typedef struct _cmd_HeatCamera_SetValue
{
  double value;
} cmd_HeatCamera_SetValue;

typedef struct _cmd_HeatCamera_SetDDELevel
{
  int32_t value;
} cmd_HeatCamera_SetDDELevel;

typedef struct _cmd_HeatCamera_SetDigitalZoomLevel
{
  double value;
} cmd_HeatCamera_SetDigitalZoomLevel;

typedef struct _cmd_HeatCamera_ShiftDDE
{
  int32_t value;
} cmd_HeatCamera_ShiftDDE;

typedef struct _cmd_HeatCamera_ZoomIn
{
  char dummy_field;
} cmd_HeatCamera_ZoomIn;

typedef struct _cmd_HeatCamera_ZoomOut
{
  char dummy_field;
} cmd_HeatCamera_ZoomOut;

typedef struct _cmd_HeatCamera_ZoomStop
{
  char dummy_field;
} cmd_HeatCamera_ZoomStop;

typedef struct _cmd_HeatCamera_FocusIn
{
  char dummy_field;
} cmd_HeatCamera_FocusIn;

typedef struct _cmd_HeatCamera_FocusOut
{
  char dummy_field;
} cmd_HeatCamera_FocusOut;

typedef struct _cmd_HeatCamera_FocusStop
{
  char dummy_field;
} cmd_HeatCamera_FocusStop;

typedef struct _cmd_HeatCamera_FocusStepPlus
{
  char dummy_field;
} cmd_HeatCamera_FocusStepPlus;

typedef struct _cmd_HeatCamera_FocusStepMinus
{
  char dummy_field;
} cmd_HeatCamera_FocusStepMinus;

typedef struct _cmd_HeatCamera_Calibrate
{
  char dummy_field;
} cmd_HeatCamera_Calibrate;

typedef struct _cmd_HeatCamera_NextZoomTablePos
{
  char dummy_field;
} cmd_HeatCamera_NextZoomTablePos;

typedef struct _cmd_HeatCamera_PrevZoomTablePos
{
  char dummy_field;
} cmd_HeatCamera_PrevZoomTablePos;

typedef struct _cmd_HeatCamera_SetCalibMode
{
  char dummy_field;
} cmd_HeatCamera_SetCalibMode;

typedef struct _cmd_HeatCamera_SetZoomTableValue
{
  int32_t value;
} cmd_HeatCamera_SetZoomTableValue;

typedef struct _cmd_HeatCamera_Zoom
{
  pb_size_t which_cmd;
  union
  {
    cmd_HeatCamera_SetZoomTableValue set_zoom_table_value;
    cmd_HeatCamera_NextZoomTablePos next_zoom_table_pos;
    cmd_HeatCamera_PrevZoomTablePos prev_zoom_table_pos;
  } cmd;
} cmd_HeatCamera_Zoom;

typedef struct _cmd_HeatCamera_SetAGC
{
  ser_JonGuiDataVideoChannelHeatAGCModes value;
} cmd_HeatCamera_SetAGC;

typedef struct _cmd_HeatCamera_SetFilters
{
  ser_JonGuiDataVideoChannelHeatFilters value;
} cmd_HeatCamera_SetFilters;

typedef struct _cmd_HeatCamera_Start
{
  char dummy_field;
} cmd_HeatCamera_Start;

typedef struct _cmd_HeatCamera_Stop
{
  char dummy_field;
} cmd_HeatCamera_Stop;

typedef struct _cmd_HeatCamera_Halt
{
  char dummy_field;
} cmd_HeatCamera_Halt;

typedef struct _cmd_HeatCamera_Photo
{
  char dummy_field;
} cmd_HeatCamera_Photo;

typedef struct _cmd_HeatCamera_GetMeteo
{
  char dummy_field;
} cmd_HeatCamera_GetMeteo;

typedef struct _cmd_HeatCamera_SetAutoFocus
{
  bool value;
} cmd_HeatCamera_SetAutoFocus;

typedef struct _cmd_HeatCamera_ResetZoom
{
  char dummy_field;
} cmd_HeatCamera_ResetZoom;

typedef struct _cmd_HeatCamera_SaveToTable
{
  char dummy_field;
} cmd_HeatCamera_SaveToTable;

typedef struct _cmd_HeatCamera_FocusROI
{
  double x1;
  double y1;
  double x2;
  double y2;
  /* TODO: Remove these fields after migration - now in Root message (fields
   * 6-8) */
  uint64_t frame_time;
  uint64_t state_time; /* System monotonic time from state when user performed
                          action */
} cmd_HeatCamera_FocusROI;

typedef struct _cmd_HeatCamera_TrackROI
{
  double x1;
  double y1;
  double x2;
  double y2;
  /* TODO: Remove these fields after migration - now in Root message (fields
   * 6-8) */
  uint64_t frame_time;
  uint64_t state_time; /* System monotonic time from state when user performed
                          action */
} cmd_HeatCamera_TrackROI;

typedef struct _cmd_HeatCamera_ZoomROI
{
  double x1;
  double y1;
  double x2;
  double y2;
  /* TODO: Remove these fields after migration - now in Root message (fields
   * 6-8) */
  uint64_t frame_time;
  uint64_t state_time; /* System monotonic time from state when user performed
                          action */
} cmd_HeatCamera_ZoomROI;

typedef struct _cmd_HeatCamera_FxROI
{
  double x1;
  double y1;
  double x2;
  double y2;
  /* TODO: Remove these fields after migration - now in Root message (fields
   * 6-8) */
  uint64_t frame_time;
  uint64_t state_time; /* System monotonic time from state when user performed
                          action */
} cmd_HeatCamera_FxROI;

typedef struct _cmd_HeatCamera_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_HeatCamera_Zoom zoom;
    cmd_HeatCamera_SetAGC set_agc;
    cmd_HeatCamera_SetFilters set_filter;
    cmd_HeatCamera_Start start;
    cmd_HeatCamera_Stop stop;
    cmd_HeatCamera_Photo photo;
    cmd_HeatCamera_ZoomIn zoom_in;
    cmd_HeatCamera_ZoomOut zoom_out;
    cmd_HeatCamera_ZoomStop zoom_stop;
    cmd_HeatCamera_FocusIn focus_in;
    cmd_HeatCamera_FocusOut focus_out;
    cmd_HeatCamera_FocusStop focus_stop;
    cmd_HeatCamera_Calibrate calibrate;
    cmd_HeatCamera_SetDDELevel set_dde_level;
    cmd_HeatCamera_EnableDDE enable_dde;
    cmd_HeatCamera_DisableDDE disable_dde;
    cmd_HeatCamera_SetAutoFocus set_auto_focus;
    cmd_HeatCamera_FocusStepPlus focus_step_plus;
    cmd_HeatCamera_FocusStepMinus focus_step_minus;
    cmd_HeatCamera_SetFxMode set_fx_mode;
    cmd_HeatCamera_NextFxMode next_fx_mode;
    cmd_HeatCamera_PrevFxMode prev_fx_mode;
    cmd_HeatCamera_GetMeteo get_meteo;
    cmd_HeatCamera_ShiftDDE shift_dde;
    cmd_HeatCamera_RefreshFxMode refresh_fx_mode;
    cmd_HeatCamera_ResetZoom reset_zoom;
    cmd_HeatCamera_SaveToTable save_to_table;
    cmd_HeatCamera_SetCalibMode set_calib_mode;
    cmd_HeatCamera_SetDigitalZoomLevel set_digital_zoom_level;
    cmd_HeatCamera_SetClaheLevel set_clahe_level;
    cmd_HeatCamera_ShiftClaheLevel shift_clahe_level;
    cmd_HeatCamera_FocusROI focus_roi;
    cmd_HeatCamera_TrackROI track_roi;
    cmd_HeatCamera_ZoomROI zoom_roi;
    cmd_HeatCamera_FxROI fx_roi;
  } cmd;
} cmd_HeatCamera_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_HeatCamera_Root_init_default \
  {                                      \
    0,                                   \
    {                                    \
      cmd_HeatCamera_Zoom_init_default   \
    }                                    \
  }
#define cmd_HeatCamera_SetFxMode_init_default \
  {                                           \
    _ser_JonGuiDataFxModeHeat_MIN             \
  }
#define cmd_HeatCamera_SetClaheLevel_init_default \
  {                                               \
    0                                             \
  }
#define cmd_HeatCamera_ShiftClaheLevel_init_default \
  {                                                 \
    0                                               \
  }
#define cmd_HeatCamera_NextFxMode_init_default \
  {                                            \
    0                                          \
  }
#define cmd_HeatCamera_PrevFxMode_init_default \
  {                                            \
    0                                          \
  }
#define cmd_HeatCamera_RefreshFxMode_init_default \
  {                                               \
    0                                             \
  }
#define cmd_HeatCamera_EnableDDE_init_default \
  {                                           \
    0                                         \
  }
#define cmd_HeatCamera_DisableDDE_init_default \
  {                                            \
    0                                          \
  }
#define cmd_HeatCamera_SetValue_init_default \
  {                                          \
    0                                        \
  }
#define cmd_HeatCamera_SetDDELevel_init_default \
  {                                             \
    0                                           \
  }
#define cmd_HeatCamera_SetDigitalZoomLevel_init_default \
  {                                                     \
    0                                                   \
  }
#define cmd_HeatCamera_ShiftDDE_init_default \
  {                                          \
    0                                        \
  }
#define cmd_HeatCamera_ZoomIn_init_default \
  {                                        \
    0                                      \
  }
#define cmd_HeatCamera_ZoomOut_init_default \
  {                                         \
    0                                       \
  }
#define cmd_HeatCamera_ZoomStop_init_default \
  {                                          \
    0                                        \
  }
#define cmd_HeatCamera_FocusIn_init_default \
  {                                         \
    0                                       \
  }
#define cmd_HeatCamera_FocusOut_init_default \
  {                                          \
    0                                        \
  }
#define cmd_HeatCamera_FocusStop_init_default \
  {                                           \
    0                                         \
  }
#define cmd_HeatCamera_FocusStepPlus_init_default \
  {                                               \
    0                                             \
  }
#define cmd_HeatCamera_FocusStepMinus_init_default \
  {                                                \
    0                                              \
  }
#define cmd_HeatCamera_Calibrate_init_default \
  {                                           \
    0                                         \
  }
#define cmd_HeatCamera_Zoom_init_default            \
  {                                                 \
    0,                                              \
    {                                               \
      cmd_HeatCamera_SetZoomTableValue_init_default \
    }                                               \
  }
#define cmd_HeatCamera_NextZoomTablePos_init_default \
  {                                                  \
    0                                                \
  }
#define cmd_HeatCamera_PrevZoomTablePos_init_default \
  {                                                  \
    0                                                \
  }
#define cmd_HeatCamera_SetCalibMode_init_default \
  {                                              \
    0                                            \
  }
#define cmd_HeatCamera_SetZoomTableValue_init_default \
  {                                                   \
    0                                                 \
  }
#define cmd_HeatCamera_SetAGC_init_default      \
  {                                             \
    _ser_JonGuiDataVideoChannelHeatAGCModes_MIN \
  }
#define cmd_HeatCamera_SetFilters_init_default \
  {                                            \
    _ser_JonGuiDataVideoChannelHeatFilters_MIN \
  }
#define cmd_HeatCamera_Start_init_default \
  {                                       \
    0                                     \
  }
#define cmd_HeatCamera_Stop_init_default \
  {                                      \
    0                                    \
  }
#define cmd_HeatCamera_Halt_init_default \
  {                                      \
    0                                    \
  }
#define cmd_HeatCamera_Photo_init_default \
  {                                       \
    0                                     \
  }
#define cmd_HeatCamera_GetMeteo_init_default \
  {                                          \
    0                                        \
  }
#define cmd_HeatCamera_SetAutoFocus_init_default \
  {                                              \
    0                                            \
  }
#define cmd_HeatCamera_ResetZoom_init_default \
  {                                           \
    0                                         \
  }
#define cmd_HeatCamera_SaveToTable_init_default \
  {                                             \
    0                                           \
  }
#define cmd_HeatCamera_FocusROI_init_default \
  {                                          \
    0, 0, 0, 0, 0, 0                         \
  }
#define cmd_HeatCamera_TrackROI_init_default \
  {                                          \
    0, 0, 0, 0, 0, 0                         \
  }
#define cmd_HeatCamera_ZoomROI_init_default \
  {                                         \
    0, 0, 0, 0, 0, 0                        \
  }
#define cmd_HeatCamera_FxROI_init_default \
  {                                       \
    0, 0, 0, 0, 0, 0                      \
  }
#define cmd_HeatCamera_Root_init_zero \
  {                                   \
    0,                                \
    {                                 \
      cmd_HeatCamera_Zoom_init_zero   \
    }                                 \
  }
#define cmd_HeatCamera_SetFxMode_init_zero \
  {                                        \
    _ser_JonGuiDataFxModeHeat_MIN          \
  }
#define cmd_HeatCamera_SetClaheLevel_init_zero \
  {                                            \
    0                                          \
  }
#define cmd_HeatCamera_ShiftClaheLevel_init_zero \
  {                                              \
    0                                            \
  }
#define cmd_HeatCamera_NextFxMode_init_zero \
  {                                         \
    0                                       \
  }
#define cmd_HeatCamera_PrevFxMode_init_zero \
  {                                         \
    0                                       \
  }
#define cmd_HeatCamera_RefreshFxMode_init_zero \
  {                                            \
    0                                          \
  }
#define cmd_HeatCamera_EnableDDE_init_zero \
  {                                        \
    0                                      \
  }
#define cmd_HeatCamera_DisableDDE_init_zero \
  {                                         \
    0                                       \
  }
#define cmd_HeatCamera_SetValue_init_zero \
  {                                       \
    0                                     \
  }
#define cmd_HeatCamera_SetDDELevel_init_zero \
  {                                          \
    0                                        \
  }
#define cmd_HeatCamera_SetDigitalZoomLevel_init_zero \
  {                                                  \
    0                                                \
  }
#define cmd_HeatCamera_ShiftDDE_init_zero \
  {                                       \
    0                                     \
  }
#define cmd_HeatCamera_ZoomIn_init_zero \
  {                                     \
    0                                   \
  }
#define cmd_HeatCamera_ZoomOut_init_zero \
  {                                      \
    0                                    \
  }
#define cmd_HeatCamera_ZoomStop_init_zero \
  {                                       \
    0                                     \
  }
#define cmd_HeatCamera_FocusIn_init_zero \
  {                                      \
    0                                    \
  }
#define cmd_HeatCamera_FocusOut_init_zero \
  {                                       \
    0                                     \
  }
#define cmd_HeatCamera_FocusStop_init_zero \
  {                                        \
    0                                      \
  }
#define cmd_HeatCamera_FocusStepPlus_init_zero \
  {                                            \
    0                                          \
  }
#define cmd_HeatCamera_FocusStepMinus_init_zero \
  {                                             \
    0                                           \
  }
#define cmd_HeatCamera_Calibrate_init_zero \
  {                                        \
    0                                      \
  }
#define cmd_HeatCamera_Zoom_init_zero            \
  {                                              \
    0,                                           \
    {                                            \
      cmd_HeatCamera_SetZoomTableValue_init_zero \
    }                                            \
  }
#define cmd_HeatCamera_NextZoomTablePos_init_zero \
  {                                               \
    0                                             \
  }
#define cmd_HeatCamera_PrevZoomTablePos_init_zero \
  {                                               \
    0                                             \
  }
#define cmd_HeatCamera_SetCalibMode_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_HeatCamera_SetZoomTableValue_init_zero \
  {                                                \
    0                                              \
  }
#define cmd_HeatCamera_SetAGC_init_zero         \
  {                                             \
    _ser_JonGuiDataVideoChannelHeatAGCModes_MIN \
  }
#define cmd_HeatCamera_SetFilters_init_zero    \
  {                                            \
    _ser_JonGuiDataVideoChannelHeatFilters_MIN \
  }
#define cmd_HeatCamera_Start_init_zero \
  {                                    \
    0                                  \
  }
#define cmd_HeatCamera_Stop_init_zero \
  {                                   \
    0                                 \
  }
#define cmd_HeatCamera_Halt_init_zero \
  {                                   \
    0                                 \
  }
#define cmd_HeatCamera_Photo_init_zero \
  {                                    \
    0                                  \
  }
#define cmd_HeatCamera_GetMeteo_init_zero \
  {                                       \
    0                                     \
  }
#define cmd_HeatCamera_SetAutoFocus_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_HeatCamera_ResetZoom_init_zero \
  {                                        \
    0                                      \
  }
#define cmd_HeatCamera_SaveToTable_init_zero \
  {                                          \
    0                                        \
  }
#define cmd_HeatCamera_FocusROI_init_zero \
  {                                       \
    0, 0, 0, 0, 0, 0                      \
  }
#define cmd_HeatCamera_TrackROI_init_zero \
  {                                       \
    0, 0, 0, 0, 0, 0                      \
  }
#define cmd_HeatCamera_ZoomROI_init_zero \
  {                                      \
    0, 0, 0, 0, 0, 0                     \
  }
#define cmd_HeatCamera_FxROI_init_zero \
  {                                    \
    0, 0, 0, 0, 0, 0                   \
  }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_HeatCamera_SetFxMode_mode_tag 1
#define cmd_HeatCamera_SetClaheLevel_value_tag 1
#define cmd_HeatCamera_ShiftClaheLevel_value_tag 1
#define cmd_HeatCamera_SetValue_value_tag 1
#define cmd_HeatCamera_SetDDELevel_value_tag 1
#define cmd_HeatCamera_SetDigitalZoomLevel_value_tag 1
#define cmd_HeatCamera_ShiftDDE_value_tag 1
#define cmd_HeatCamera_SetZoomTableValue_value_tag 1
#define cmd_HeatCamera_Zoom_set_zoom_table_value_tag 1
#define cmd_HeatCamera_Zoom_next_zoom_table_pos_tag 2
#define cmd_HeatCamera_Zoom_prev_zoom_table_pos_tag 3
#define cmd_HeatCamera_SetAGC_value_tag 1
#define cmd_HeatCamera_SetFilters_value_tag 1
#define cmd_HeatCamera_SetAutoFocus_value_tag 1
#define cmd_HeatCamera_FocusROI_x1_tag 1
#define cmd_HeatCamera_FocusROI_y1_tag 2
#define cmd_HeatCamera_FocusROI_x2_tag 3
#define cmd_HeatCamera_FocusROI_y2_tag 4
#define cmd_HeatCamera_FocusROI_frame_time_tag 5
#define cmd_HeatCamera_FocusROI_state_time_tag 6
#define cmd_HeatCamera_TrackROI_x1_tag 1
#define cmd_HeatCamera_TrackROI_y1_tag 2
#define cmd_HeatCamera_TrackROI_x2_tag 3
#define cmd_HeatCamera_TrackROI_y2_tag 4
#define cmd_HeatCamera_TrackROI_frame_time_tag 5
#define cmd_HeatCamera_TrackROI_state_time_tag 6
#define cmd_HeatCamera_ZoomROI_x1_tag 1
#define cmd_HeatCamera_ZoomROI_y1_tag 2
#define cmd_HeatCamera_ZoomROI_x2_tag 3
#define cmd_HeatCamera_ZoomROI_y2_tag 4
#define cmd_HeatCamera_ZoomROI_frame_time_tag 5
#define cmd_HeatCamera_ZoomROI_state_time_tag 6
#define cmd_HeatCamera_FxROI_x1_tag 1
#define cmd_HeatCamera_FxROI_y1_tag 2
#define cmd_HeatCamera_FxROI_x2_tag 3
#define cmd_HeatCamera_FxROI_y2_tag 4
#define cmd_HeatCamera_FxROI_frame_time_tag 5
#define cmd_HeatCamera_FxROI_state_time_tag 6
#define cmd_HeatCamera_Root_zoom_tag 1
#define cmd_HeatCamera_Root_set_agc_tag 2
#define cmd_HeatCamera_Root_set_filter_tag 3
#define cmd_HeatCamera_Root_start_tag 4
#define cmd_HeatCamera_Root_stop_tag 5
#define cmd_HeatCamera_Root_photo_tag 6
#define cmd_HeatCamera_Root_zoom_in_tag 10
#define cmd_HeatCamera_Root_zoom_out_tag 11
#define cmd_HeatCamera_Root_zoom_stop_tag 12
#define cmd_HeatCamera_Root_focus_in_tag 13
#define cmd_HeatCamera_Root_focus_out_tag 14
#define cmd_HeatCamera_Root_focus_stop_tag 15
#define cmd_HeatCamera_Root_calibrate_tag 16
#define cmd_HeatCamera_Root_set_dde_level_tag 17
#define cmd_HeatCamera_Root_enable_dde_tag 18
#define cmd_HeatCamera_Root_disable_dde_tag 19
#define cmd_HeatCamera_Root_set_auto_focus_tag 20
#define cmd_HeatCamera_Root_focus_step_plus_tag 21
#define cmd_HeatCamera_Root_focus_step_minus_tag 22
#define cmd_HeatCamera_Root_set_fx_mode_tag 23
#define cmd_HeatCamera_Root_next_fx_mode_tag 24
#define cmd_HeatCamera_Root_prev_fx_mode_tag 25
#define cmd_HeatCamera_Root_get_meteo_tag 26
#define cmd_HeatCamera_Root_shift_dde_tag 27
#define cmd_HeatCamera_Root_refresh_fx_mode_tag 28
#define cmd_HeatCamera_Root_reset_zoom_tag 29
#define cmd_HeatCamera_Root_save_to_table_tag 30
#define cmd_HeatCamera_Root_set_calib_mode_tag 31
#define cmd_HeatCamera_Root_set_digital_zoom_level_tag 32
#define cmd_HeatCamera_Root_set_clahe_level_tag 33
#define cmd_HeatCamera_Root_shift_clahe_level_tag 34
#define cmd_HeatCamera_Root_focus_roi_tag 35
#define cmd_HeatCamera_Root_track_roi_tag 36
#define cmd_HeatCamera_Root_zoom_roi_tag 37
#define cmd_HeatCamera_Root_fx_roi_tag 38

/* Struct field encoding specification for nanopb */
#define cmd_HeatCamera_Root_FIELDLIST(X, a)                                   \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, zoom, cmd.zoom), 1)                      \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_agc, cmd.set_agc), 2)                \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_filter, cmd.set_filter), 3)          \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start, cmd.start), 4)                    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop, cmd.stop), 5)                      \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, photo, cmd.photo), 6)                    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, zoom_in, cmd.zoom_in), 10)               \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, zoom_out, cmd.zoom_out), 11)             \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, zoom_stop, cmd.zoom_stop), 12)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, focus_in, cmd.focus_in), 13)             \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, focus_out, cmd.focus_out), 14)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, focus_stop, cmd.focus_stop), 15)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, calibrate, cmd.calibrate), 16)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_dde_level, cmd.set_dde_level), 17)   \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, enable_dde, cmd.enable_dde), 18)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, disable_dde, cmd.disable_dde), 19)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_auto_focus, cmd.set_auto_focus), 20) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, focus_step_plus, cmd.focus_step_plus),   \
    21)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, focus_step_minus, cmd.focus_step_minus), \
    22)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_fx_mode, cmd.set_fx_mode), 23)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, next_fx_mode, cmd.next_fx_mode), 24)     \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, prev_fx_mode, cmd.prev_fx_mode), 25)     \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, get_meteo, cmd.get_meteo), 26)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, shift_dde, cmd.shift_dde), 27)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, refresh_fx_mode, cmd.refresh_fx_mode),   \
    28)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, reset_zoom, cmd.reset_zoom), 29)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, save_to_table, cmd.save_to_table), 30)   \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_calib_mode, cmd.set_calib_mode), 31) \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_digital_zoom_level, cmd.set_digital_zoom_level), 32)            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_clahe_level, cmd.set_clahe_level),   \
    33)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, shift_clahe_level, cmd.shift_clahe_level), 34)                      \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, focus_roi, cmd.focus_roi), 35)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, track_roi, cmd.track_roi), 36)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, zoom_roi, cmd.zoom_roi), 37)             \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, fx_roi, cmd.fx_roi), 38)
#define cmd_HeatCamera_Root_CALLBACK NULL
#define cmd_HeatCamera_Root_DEFAULT NULL
#define cmd_HeatCamera_Root_cmd_zoom_MSGTYPE cmd_HeatCamera_Zoom
#define cmd_HeatCamera_Root_cmd_set_agc_MSGTYPE cmd_HeatCamera_SetAGC
#define cmd_HeatCamera_Root_cmd_set_filter_MSGTYPE cmd_HeatCamera_SetFilters
#define cmd_HeatCamera_Root_cmd_start_MSGTYPE cmd_HeatCamera_Start
#define cmd_HeatCamera_Root_cmd_stop_MSGTYPE cmd_HeatCamera_Stop
#define cmd_HeatCamera_Root_cmd_photo_MSGTYPE cmd_HeatCamera_Photo
#define cmd_HeatCamera_Root_cmd_zoom_in_MSGTYPE cmd_HeatCamera_ZoomIn
#define cmd_HeatCamera_Root_cmd_zoom_out_MSGTYPE cmd_HeatCamera_ZoomOut
#define cmd_HeatCamera_Root_cmd_zoom_stop_MSGTYPE cmd_HeatCamera_ZoomStop
#define cmd_HeatCamera_Root_cmd_focus_in_MSGTYPE cmd_HeatCamera_FocusIn
#define cmd_HeatCamera_Root_cmd_focus_out_MSGTYPE cmd_HeatCamera_FocusOut
#define cmd_HeatCamera_Root_cmd_focus_stop_MSGTYPE cmd_HeatCamera_FocusStop
#define cmd_HeatCamera_Root_cmd_calibrate_MSGTYPE cmd_HeatCamera_Calibrate
#define cmd_HeatCamera_Root_cmd_set_dde_level_MSGTYPE cmd_HeatCamera_SetDDELevel
#define cmd_HeatCamera_Root_cmd_enable_dde_MSGTYPE cmd_HeatCamera_EnableDDE
#define cmd_HeatCamera_Root_cmd_disable_dde_MSGTYPE cmd_HeatCamera_DisableDDE
#define cmd_HeatCamera_Root_cmd_set_auto_focus_MSGTYPE \
  cmd_HeatCamera_SetAutoFocus
#define cmd_HeatCamera_Root_cmd_focus_step_plus_MSGTYPE \
  cmd_HeatCamera_FocusStepPlus
#define cmd_HeatCamera_Root_cmd_focus_step_minus_MSGTYPE \
  cmd_HeatCamera_FocusStepMinus
#define cmd_HeatCamera_Root_cmd_set_fx_mode_MSGTYPE cmd_HeatCamera_SetFxMode
#define cmd_HeatCamera_Root_cmd_next_fx_mode_MSGTYPE cmd_HeatCamera_NextFxMode
#define cmd_HeatCamera_Root_cmd_prev_fx_mode_MSGTYPE cmd_HeatCamera_PrevFxMode
#define cmd_HeatCamera_Root_cmd_get_meteo_MSGTYPE cmd_HeatCamera_GetMeteo
#define cmd_HeatCamera_Root_cmd_shift_dde_MSGTYPE cmd_HeatCamera_ShiftDDE
#define cmd_HeatCamera_Root_cmd_refresh_fx_mode_MSGTYPE \
  cmd_HeatCamera_RefreshFxMode
#define cmd_HeatCamera_Root_cmd_reset_zoom_MSGTYPE cmd_HeatCamera_ResetZoom
#define cmd_HeatCamera_Root_cmd_save_to_table_MSGTYPE cmd_HeatCamera_SaveToTable
#define cmd_HeatCamera_Root_cmd_set_calib_mode_MSGTYPE \
  cmd_HeatCamera_SetCalibMode
#define cmd_HeatCamera_Root_cmd_set_digital_zoom_level_MSGTYPE \
  cmd_HeatCamera_SetDigitalZoomLevel
#define cmd_HeatCamera_Root_cmd_set_clahe_level_MSGTYPE \
  cmd_HeatCamera_SetClaheLevel
#define cmd_HeatCamera_Root_cmd_shift_clahe_level_MSGTYPE \
  cmd_HeatCamera_ShiftClaheLevel
#define cmd_HeatCamera_Root_cmd_focus_roi_MSGTYPE cmd_HeatCamera_FocusROI
#define cmd_HeatCamera_Root_cmd_track_roi_MSGTYPE cmd_HeatCamera_TrackROI
#define cmd_HeatCamera_Root_cmd_zoom_roi_MSGTYPE cmd_HeatCamera_ZoomROI
#define cmd_HeatCamera_Root_cmd_fx_roi_MSGTYPE cmd_HeatCamera_FxROI

#define cmd_HeatCamera_SetFxMode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, mode, 1)
#define cmd_HeatCamera_SetFxMode_CALLBACK NULL
#define cmd_HeatCamera_SetFxMode_DEFAULT NULL

#define cmd_HeatCamera_SetClaheLevel_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_HeatCamera_SetClaheLevel_CALLBACK NULL
#define cmd_HeatCamera_SetClaheLevel_DEFAULT NULL

#define cmd_HeatCamera_ShiftClaheLevel_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_HeatCamera_ShiftClaheLevel_CALLBACK NULL
#define cmd_HeatCamera_ShiftClaheLevel_DEFAULT NULL

#define cmd_HeatCamera_NextFxMode_FIELDLIST(X, a)

#define cmd_HeatCamera_NextFxMode_CALLBACK NULL
#define cmd_HeatCamera_NextFxMode_DEFAULT NULL

#define cmd_HeatCamera_PrevFxMode_FIELDLIST(X, a)

#define cmd_HeatCamera_PrevFxMode_CALLBACK NULL
#define cmd_HeatCamera_PrevFxMode_DEFAULT NULL

#define cmd_HeatCamera_RefreshFxMode_FIELDLIST(X, a)

#define cmd_HeatCamera_RefreshFxMode_CALLBACK NULL
#define cmd_HeatCamera_RefreshFxMode_DEFAULT NULL

#define cmd_HeatCamera_EnableDDE_FIELDLIST(X, a)

#define cmd_HeatCamera_EnableDDE_CALLBACK NULL
#define cmd_HeatCamera_EnableDDE_DEFAULT NULL

#define cmd_HeatCamera_DisableDDE_FIELDLIST(X, a)

#define cmd_HeatCamera_DisableDDE_CALLBACK NULL
#define cmd_HeatCamera_DisableDDE_DEFAULT NULL

#define cmd_HeatCamera_SetValue_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_HeatCamera_SetValue_CALLBACK NULL
#define cmd_HeatCamera_SetValue_DEFAULT NULL

#define cmd_HeatCamera_SetDDELevel_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, value, 1)
#define cmd_HeatCamera_SetDDELevel_CALLBACK NULL
#define cmd_HeatCamera_SetDDELevel_DEFAULT NULL

#define cmd_HeatCamera_SetDigitalZoomLevel_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_HeatCamera_SetDigitalZoomLevel_CALLBACK NULL
#define cmd_HeatCamera_SetDigitalZoomLevel_DEFAULT NULL

#define cmd_HeatCamera_ShiftDDE_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, value, 1)
#define cmd_HeatCamera_ShiftDDE_CALLBACK NULL
#define cmd_HeatCamera_ShiftDDE_DEFAULT NULL

#define cmd_HeatCamera_ZoomIn_FIELDLIST(X, a)

#define cmd_HeatCamera_ZoomIn_CALLBACK NULL
#define cmd_HeatCamera_ZoomIn_DEFAULT NULL

#define cmd_HeatCamera_ZoomOut_FIELDLIST(X, a)

#define cmd_HeatCamera_ZoomOut_CALLBACK NULL
#define cmd_HeatCamera_ZoomOut_DEFAULT NULL

#define cmd_HeatCamera_ZoomStop_FIELDLIST(X, a)

#define cmd_HeatCamera_ZoomStop_CALLBACK NULL
#define cmd_HeatCamera_ZoomStop_DEFAULT NULL

#define cmd_HeatCamera_FocusIn_FIELDLIST(X, a)

#define cmd_HeatCamera_FocusIn_CALLBACK NULL
#define cmd_HeatCamera_FocusIn_DEFAULT NULL

#define cmd_HeatCamera_FocusOut_FIELDLIST(X, a)

#define cmd_HeatCamera_FocusOut_CALLBACK NULL
#define cmd_HeatCamera_FocusOut_DEFAULT NULL

#define cmd_HeatCamera_FocusStop_FIELDLIST(X, a)

#define cmd_HeatCamera_FocusStop_CALLBACK NULL
#define cmd_HeatCamera_FocusStop_DEFAULT NULL

#define cmd_HeatCamera_FocusStepPlus_FIELDLIST(X, a)

#define cmd_HeatCamera_FocusStepPlus_CALLBACK NULL
#define cmd_HeatCamera_FocusStepPlus_DEFAULT NULL

#define cmd_HeatCamera_FocusStepMinus_FIELDLIST(X, a)

#define cmd_HeatCamera_FocusStepMinus_CALLBACK NULL
#define cmd_HeatCamera_FocusStepMinus_DEFAULT NULL

#define cmd_HeatCamera_Calibrate_FIELDLIST(X, a)

#define cmd_HeatCamera_Calibrate_CALLBACK NULL
#define cmd_HeatCamera_Calibrate_DEFAULT NULL

#define cmd_HeatCamera_Zoom_FIELDLIST(X, a)                   \
  X(a, STATIC, ONEOF, MESSAGE,                                \
    (cmd, set_zoom_table_value, cmd.set_zoom_table_value), 1) \
  X(a, STATIC, ONEOF, MESSAGE,                                \
    (cmd, next_zoom_table_pos, cmd.next_zoom_table_pos), 2)   \
  X(a, STATIC, ONEOF, MESSAGE,                                \
    (cmd, prev_zoom_table_pos, cmd.prev_zoom_table_pos), 3)
#define cmd_HeatCamera_Zoom_CALLBACK NULL
#define cmd_HeatCamera_Zoom_DEFAULT NULL
#define cmd_HeatCamera_Zoom_cmd_set_zoom_table_value_MSGTYPE \
  cmd_HeatCamera_SetZoomTableValue
#define cmd_HeatCamera_Zoom_cmd_next_zoom_table_pos_MSGTYPE \
  cmd_HeatCamera_NextZoomTablePos
#define cmd_HeatCamera_Zoom_cmd_prev_zoom_table_pos_MSGTYPE \
  cmd_HeatCamera_PrevZoomTablePos

#define cmd_HeatCamera_NextZoomTablePos_FIELDLIST(X, a)

#define cmd_HeatCamera_NextZoomTablePos_CALLBACK NULL
#define cmd_HeatCamera_NextZoomTablePos_DEFAULT NULL

#define cmd_HeatCamera_PrevZoomTablePos_FIELDLIST(X, a)

#define cmd_HeatCamera_PrevZoomTablePos_CALLBACK NULL
#define cmd_HeatCamera_PrevZoomTablePos_DEFAULT NULL

#define cmd_HeatCamera_SetCalibMode_FIELDLIST(X, a)

#define cmd_HeatCamera_SetCalibMode_CALLBACK NULL
#define cmd_HeatCamera_SetCalibMode_DEFAULT NULL

#define cmd_HeatCamera_SetZoomTableValue_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, value, 1)
#define cmd_HeatCamera_SetZoomTableValue_CALLBACK NULL
#define cmd_HeatCamera_SetZoomTableValue_DEFAULT NULL

#define cmd_HeatCamera_SetAGC_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, value, 1)
#define cmd_HeatCamera_SetAGC_CALLBACK NULL
#define cmd_HeatCamera_SetAGC_DEFAULT NULL

#define cmd_HeatCamera_SetFilters_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, value, 1)
#define cmd_HeatCamera_SetFilters_CALLBACK NULL
#define cmd_HeatCamera_SetFilters_DEFAULT NULL

#define cmd_HeatCamera_Start_FIELDLIST(X, a)

#define cmd_HeatCamera_Start_CALLBACK NULL
#define cmd_HeatCamera_Start_DEFAULT NULL

#define cmd_HeatCamera_Stop_FIELDLIST(X, a)

#define cmd_HeatCamera_Stop_CALLBACK NULL
#define cmd_HeatCamera_Stop_DEFAULT NULL

#define cmd_HeatCamera_Halt_FIELDLIST(X, a)

#define cmd_HeatCamera_Halt_CALLBACK NULL
#define cmd_HeatCamera_Halt_DEFAULT NULL

#define cmd_HeatCamera_Photo_FIELDLIST(X, a)

#define cmd_HeatCamera_Photo_CALLBACK NULL
#define cmd_HeatCamera_Photo_DEFAULT NULL

#define cmd_HeatCamera_GetMeteo_FIELDLIST(X, a)

#define cmd_HeatCamera_GetMeteo_CALLBACK NULL
#define cmd_HeatCamera_GetMeteo_DEFAULT NULL

#define cmd_HeatCamera_SetAutoFocus_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, BOOL, value, 1)
#define cmd_HeatCamera_SetAutoFocus_CALLBACK NULL
#define cmd_HeatCamera_SetAutoFocus_DEFAULT NULL

#define cmd_HeatCamera_ResetZoom_FIELDLIST(X, a)

#define cmd_HeatCamera_ResetZoom_CALLBACK NULL
#define cmd_HeatCamera_ResetZoom_DEFAULT NULL

#define cmd_HeatCamera_SaveToTable_FIELDLIST(X, a)

#define cmd_HeatCamera_SaveToTable_CALLBACK NULL
#define cmd_HeatCamera_SaveToTable_DEFAULT NULL

#define cmd_HeatCamera_FocusROI_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, x1, 1)         \
  X(a, STATIC, SINGULAR, DOUBLE, y1, 2)         \
  X(a, STATIC, SINGULAR, DOUBLE, x2, 3)         \
  X(a, STATIC, SINGULAR, DOUBLE, y2, 4)         \
  X(a, STATIC, SINGULAR, UINT64, frame_time, 5) \
  X(a, STATIC, SINGULAR, UINT64, state_time, 6)
#define cmd_HeatCamera_FocusROI_CALLBACK NULL
#define cmd_HeatCamera_FocusROI_DEFAULT NULL

#define cmd_HeatCamera_TrackROI_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, x1, 1)         \
  X(a, STATIC, SINGULAR, DOUBLE, y1, 2)         \
  X(a, STATIC, SINGULAR, DOUBLE, x2, 3)         \
  X(a, STATIC, SINGULAR, DOUBLE, y2, 4)         \
  X(a, STATIC, SINGULAR, UINT64, frame_time, 5) \
  X(a, STATIC, SINGULAR, UINT64, state_time, 6)
#define cmd_HeatCamera_TrackROI_CALLBACK NULL
#define cmd_HeatCamera_TrackROI_DEFAULT NULL

#define cmd_HeatCamera_ZoomROI_FIELDLIST(X, a)  \
  X(a, STATIC, SINGULAR, DOUBLE, x1, 1)         \
  X(a, STATIC, SINGULAR, DOUBLE, y1, 2)         \
  X(a, STATIC, SINGULAR, DOUBLE, x2, 3)         \
  X(a, STATIC, SINGULAR, DOUBLE, y2, 4)         \
  X(a, STATIC, SINGULAR, UINT64, frame_time, 5) \
  X(a, STATIC, SINGULAR, UINT64, state_time, 6)
#define cmd_HeatCamera_ZoomROI_CALLBACK NULL
#define cmd_HeatCamera_ZoomROI_DEFAULT NULL

#define cmd_HeatCamera_FxROI_FIELDLIST(X, a)    \
  X(a, STATIC, SINGULAR, DOUBLE, x1, 1)         \
  X(a, STATIC, SINGULAR, DOUBLE, y1, 2)         \
  X(a, STATIC, SINGULAR, DOUBLE, x2, 3)         \
  X(a, STATIC, SINGULAR, DOUBLE, y2, 4)         \
  X(a, STATIC, SINGULAR, UINT64, frame_time, 5) \
  X(a, STATIC, SINGULAR, UINT64, state_time, 6)
#define cmd_HeatCamera_FxROI_CALLBACK NULL
#define cmd_HeatCamera_FxROI_DEFAULT NULL

  extern const pb_msgdesc_t cmd_HeatCamera_Root_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetFxMode_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetClaheLevel_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_ShiftClaheLevel_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_NextFxMode_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_PrevFxMode_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_RefreshFxMode_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_EnableDDE_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_DisableDDE_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetValue_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetDDELevel_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetDigitalZoomLevel_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_ShiftDDE_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_ZoomIn_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_ZoomOut_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_ZoomStop_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_FocusIn_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_FocusOut_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_FocusStop_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_FocusStepPlus_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_FocusStepMinus_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_Calibrate_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_Zoom_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_NextZoomTablePos_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_PrevZoomTablePos_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetCalibMode_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetZoomTableValue_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetAGC_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetFilters_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_Start_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_Stop_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_Halt_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_Photo_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_GetMeteo_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SetAutoFocus_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_ResetZoom_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_SaveToTable_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_FocusROI_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_TrackROI_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_ZoomROI_msg;
  extern const pb_msgdesc_t cmd_HeatCamera_FxROI_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_HeatCamera_Root_fields &cmd_HeatCamera_Root_msg
#define cmd_HeatCamera_SetFxMode_fields &cmd_HeatCamera_SetFxMode_msg
#define cmd_HeatCamera_SetClaheLevel_fields &cmd_HeatCamera_SetClaheLevel_msg
#define cmd_HeatCamera_ShiftClaheLevel_fields \
  &cmd_HeatCamera_ShiftClaheLevel_msg
#define cmd_HeatCamera_NextFxMode_fields &cmd_HeatCamera_NextFxMode_msg
#define cmd_HeatCamera_PrevFxMode_fields &cmd_HeatCamera_PrevFxMode_msg
#define cmd_HeatCamera_RefreshFxMode_fields &cmd_HeatCamera_RefreshFxMode_msg
#define cmd_HeatCamera_EnableDDE_fields &cmd_HeatCamera_EnableDDE_msg
#define cmd_HeatCamera_DisableDDE_fields &cmd_HeatCamera_DisableDDE_msg
#define cmd_HeatCamera_SetValue_fields &cmd_HeatCamera_SetValue_msg
#define cmd_HeatCamera_SetDDELevel_fields &cmd_HeatCamera_SetDDELevel_msg
#define cmd_HeatCamera_SetDigitalZoomLevel_fields \
  &cmd_HeatCamera_SetDigitalZoomLevel_msg
#define cmd_HeatCamera_ShiftDDE_fields &cmd_HeatCamera_ShiftDDE_msg
#define cmd_HeatCamera_ZoomIn_fields &cmd_HeatCamera_ZoomIn_msg
#define cmd_HeatCamera_ZoomOut_fields &cmd_HeatCamera_ZoomOut_msg
#define cmd_HeatCamera_ZoomStop_fields &cmd_HeatCamera_ZoomStop_msg
#define cmd_HeatCamera_FocusIn_fields &cmd_HeatCamera_FocusIn_msg
#define cmd_HeatCamera_FocusOut_fields &cmd_HeatCamera_FocusOut_msg
#define cmd_HeatCamera_FocusStop_fields &cmd_HeatCamera_FocusStop_msg
#define cmd_HeatCamera_FocusStepPlus_fields &cmd_HeatCamera_FocusStepPlus_msg
#define cmd_HeatCamera_FocusStepMinus_fields &cmd_HeatCamera_FocusStepMinus_msg
#define cmd_HeatCamera_Calibrate_fields &cmd_HeatCamera_Calibrate_msg
#define cmd_HeatCamera_Zoom_fields &cmd_HeatCamera_Zoom_msg
#define cmd_HeatCamera_NextZoomTablePos_fields \
  &cmd_HeatCamera_NextZoomTablePos_msg
#define cmd_HeatCamera_PrevZoomTablePos_fields \
  &cmd_HeatCamera_PrevZoomTablePos_msg
#define cmd_HeatCamera_SetCalibMode_fields &cmd_HeatCamera_SetCalibMode_msg
#define cmd_HeatCamera_SetZoomTableValue_fields \
  &cmd_HeatCamera_SetZoomTableValue_msg
#define cmd_HeatCamera_SetAGC_fields &cmd_HeatCamera_SetAGC_msg
#define cmd_HeatCamera_SetFilters_fields &cmd_HeatCamera_SetFilters_msg
#define cmd_HeatCamera_Start_fields &cmd_HeatCamera_Start_msg
#define cmd_HeatCamera_Stop_fields &cmd_HeatCamera_Stop_msg
#define cmd_HeatCamera_Halt_fields &cmd_HeatCamera_Halt_msg
#define cmd_HeatCamera_Photo_fields &cmd_HeatCamera_Photo_msg
#define cmd_HeatCamera_GetMeteo_fields &cmd_HeatCamera_GetMeteo_msg
#define cmd_HeatCamera_SetAutoFocus_fields &cmd_HeatCamera_SetAutoFocus_msg
#define cmd_HeatCamera_ResetZoom_fields &cmd_HeatCamera_ResetZoom_msg
#define cmd_HeatCamera_SaveToTable_fields &cmd_HeatCamera_SaveToTable_msg
#define cmd_HeatCamera_FocusROI_fields &cmd_HeatCamera_FocusROI_msg
#define cmd_HeatCamera_TrackROI_fields &cmd_HeatCamera_TrackROI_msg
#define cmd_HeatCamera_ZoomROI_fields &cmd_HeatCamera_ZoomROI_msg
#define cmd_HeatCamera_FxROI_fields &cmd_HeatCamera_FxROI_msg

/* Maximum encoded size of messages (where known) */
#define CMD_HEATCAMERA_JON_SHARED_CMD_HEAT_CAMERA_PB_H_MAX_SIZE \
  cmd_HeatCamera_Root_size
#define cmd_HeatCamera_Calibrate_size 0
#define cmd_HeatCamera_DisableDDE_size 0
#define cmd_HeatCamera_EnableDDE_size 0
#define cmd_HeatCamera_FocusIn_size 0
#define cmd_HeatCamera_FocusOut_size 0
#define cmd_HeatCamera_FocusROI_size 58
#define cmd_HeatCamera_FocusStepMinus_size 0
#define cmd_HeatCamera_FocusStepPlus_size 0
#define cmd_HeatCamera_FocusStop_size 0
#define cmd_HeatCamera_FxROI_size 58
#define cmd_HeatCamera_GetMeteo_size 0
#define cmd_HeatCamera_Halt_size 0
#define cmd_HeatCamera_NextFxMode_size 0
#define cmd_HeatCamera_NextZoomTablePos_size 0
#define cmd_HeatCamera_Photo_size 0
#define cmd_HeatCamera_PrevFxMode_size 0
#define cmd_HeatCamera_PrevZoomTablePos_size 0
#define cmd_HeatCamera_RefreshFxMode_size 0
#define cmd_HeatCamera_ResetZoom_size 0
#define cmd_HeatCamera_Root_size 61
#define cmd_HeatCamera_SaveToTable_size 0
#define cmd_HeatCamera_SetAGC_size 2
#define cmd_HeatCamera_SetAutoFocus_size 2
#define cmd_HeatCamera_SetCalibMode_size 0
#define cmd_HeatCamera_SetClaheLevel_size 9
#define cmd_HeatCamera_SetDDELevel_size 11
#define cmd_HeatCamera_SetDigitalZoomLevel_size 9
#define cmd_HeatCamera_SetFilters_size 2
#define cmd_HeatCamera_SetFxMode_size 2
#define cmd_HeatCamera_SetValue_size 9
#define cmd_HeatCamera_SetZoomTableValue_size 11
#define cmd_HeatCamera_ShiftClaheLevel_size 9
#define cmd_HeatCamera_ShiftDDE_size 11
#define cmd_HeatCamera_Start_size 0
#define cmd_HeatCamera_Stop_size 0
#define cmd_HeatCamera_TrackROI_size 58
#define cmd_HeatCamera_ZoomIn_size 0
#define cmd_HeatCamera_ZoomOut_size 0
#define cmd_HeatCamera_ZoomROI_size 58
#define cmd_HeatCamera_ZoomStop_size 0
#define cmd_HeatCamera_Zoom_size 13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
