/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_compass.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_Compass_Root, cmd_Compass_Root, AUTO)


PB_BIND(cmd_Compass_Start, cmd_Compass_Start, AUTO)


PB_BIND(cmd_Compass_Stop, cmd_Compass_Stop, AUTO)


PB_BIND(cmd_Compass_Next, cmd_Compass_Next, AUTO)


PB_BIND(cmd_Compass_CalibrateStartLong, cmd_Compass_CalibrateStartLong, AUTO)


PB_BIND(cmd_Compass_CalibrateStartShort, cmd_Compass_CalibrateStartShort, AUTO)


PB_BIND(cmd_Compass_CalibrateNext, cmd_Compass_CalibrateNext, AUTO)


PB_BIND(cmd_Compass_CalibrateCencel, cmd_Compass_CalibrateCencel, AUTO)


PB_BIND(cmd_Compass_GetMeteo, cmd_Compass_GetMeteo, AUTO)


PB_BIND(cmd_Compass_SetMagneticDeclination,
        cmd_Compass_SetMagneticDeclination,
        AUTO)


PB_BIND(cmd_Compass_SetOffsetAngleAzimuth,
        cmd_Compass_SetOffsetAngleAzimuth,
        AUTO)


PB_BIND(cmd_Compass_SetOffsetAngleElevation,
        cmd_Compass_SetOffsetAngleElevation,
        AUTO)


PB_BIND(cmd_Compass_SetUseRotaryPosition,
        cmd_Compass_SetUseRotaryPosition,
        AUTO)


#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
