/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_GPS_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_GPS_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ser_JonGuiDataGps
{
  double longitude;
  double latitude;
  double altitude;
  double manual_longitude;
  double manual_latitude;
  double manual_altitude;
  ser_JonGuiDataGpsFixType fix_type;
  bool use_manual;
  int64_t timestamp; /* GPS timestamp from satellite (Unix time in seconds) */
  bool is_started;
} ser_JonGuiDataGps;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataGps_init_default                       \
  {                                                          \
    0, 0, 0, 0, 0, 0, _ser_JonGuiDataGpsFixType_MIN, 0, 0, 0 \
  }
#define ser_JonGuiDataGps_init_zero                          \
  {                                                          \
    0, 0, 0, 0, 0, 0, _ser_JonGuiDataGpsFixType_MIN, 0, 0, 0 \
  }

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataGps_longitude_tag 1
#define ser_JonGuiDataGps_latitude_tag 2
#define ser_JonGuiDataGps_altitude_tag 3
#define ser_JonGuiDataGps_manual_longitude_tag 4
#define ser_JonGuiDataGps_manual_latitude_tag 5
#define ser_JonGuiDataGps_manual_altitude_tag 6
#define ser_JonGuiDataGps_fix_type_tag 7
#define ser_JonGuiDataGps_use_manual_tag 8
#define ser_JonGuiDataGps_timestamp_tag 9
#define ser_JonGuiDataGps_is_started_tag 10

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataGps_FIELDLIST(X, a)             \
  X(a, STATIC, SINGULAR, DOUBLE, longitude, 1)        \
  X(a, STATIC, SINGULAR, DOUBLE, latitude, 2)         \
  X(a, STATIC, SINGULAR, DOUBLE, altitude, 3)         \
  X(a, STATIC, SINGULAR, DOUBLE, manual_longitude, 4) \
  X(a, STATIC, SINGULAR, DOUBLE, manual_latitude, 5)  \
  X(a, STATIC, SINGULAR, DOUBLE, manual_altitude, 6)  \
  X(a, STATIC, SINGULAR, UENUM, fix_type, 7)          \
  X(a, STATIC, SINGULAR, BOOL, use_manual, 8)         \
  X(a, STATIC, SINGULAR, INT64, timestamp, 9)         \
  X(a, STATIC, SINGULAR, BOOL, is_started, 10)
#define ser_JonGuiDataGps_CALLBACK NULL
#define ser_JonGuiDataGps_DEFAULT NULL

  extern const pb_msgdesc_t ser_JonGuiDataGps_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataGps_fields &ser_JonGuiDataGps_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_GPS_PB_H_MAX_SIZE ser_JonGuiDataGps_size
#define ser_JonGuiDataGps_size 71

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
