/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_GPS_JON_SHARED_CMD_GPS_PB_H_INCLUDED
#define PB_CMD_GPS_JON_SHARED_CMD_GPS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_Gps_Start
{
  char dummy_field;
} cmd_Gps_Start;

typedef struct _cmd_Gps_Stop
{
  char dummy_field;
} cmd_Gps_Stop;

typedef struct _cmd_Gps_GetMeteo
{
  char dummy_field;
} cmd_Gps_GetMeteo;

typedef struct _cmd_Gps_SetUseManualPosition
{
  bool flag;
} cmd_Gps_SetUseManualPosition;

typedef struct _cmd_Gps_SetManualPosition
{
  double latitude;
  double longitude;
  double altitude;
} cmd_Gps_SetManualPosition;

typedef struct _cmd_Gps_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_Gps_Start start;
    cmd_Gps_Stop stop;
    cmd_Gps_SetManualPosition set_manual_position;
    cmd_Gps_SetUseManualPosition set_use_manual_position;
    cmd_Gps_GetMeteo get_meteo;
  } cmd;
} cmd_Gps_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_Gps_Root_init_default \
  {                               \
    0,                            \
    {                             \
      cmd_Gps_Start_init_default  \
    }                             \
  }
#define cmd_Gps_Start_init_default { 0 }
#define cmd_Gps_Stop_init_default { 0 }
#define cmd_Gps_GetMeteo_init_default { 0 }
#define cmd_Gps_SetUseManualPosition_init_default { 0 }
#define cmd_Gps_SetManualPosition_init_default { 0, 0, 0 }
#define cmd_Gps_Root_init_zero \
  {                            \
    0,                         \
    {                          \
      cmd_Gps_Start_init_zero  \
    }                          \
  }
#define cmd_Gps_Start_init_zero { 0 }
#define cmd_Gps_Stop_init_zero { 0 }
#define cmd_Gps_GetMeteo_init_zero { 0 }
#define cmd_Gps_SetUseManualPosition_init_zero { 0 }
#define cmd_Gps_SetManualPosition_init_zero { 0, 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_Gps_SetUseManualPosition_flag_tag 1
#define cmd_Gps_SetManualPosition_latitude_tag 1
#define cmd_Gps_SetManualPosition_longitude_tag 2
#define cmd_Gps_SetManualPosition_altitude_tag 3
#define cmd_Gps_Root_start_tag 1
#define cmd_Gps_Root_stop_tag 2
#define cmd_Gps_Root_set_manual_position_tag 3
#define cmd_Gps_Root_set_use_manual_position_tag 4
#define cmd_Gps_Root_get_meteo_tag 5

/* Struct field encoding specification for nanopb */
#define cmd_Gps_Root_FIELDLIST(X, a)                                \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start, cmd.start), 1)          \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop, cmd.stop), 2)            \
  X(a, STATIC, ONEOF, MESSAGE,                                      \
    (cmd, set_manual_position, cmd.set_manual_position), 3)         \
  X(a, STATIC, ONEOF, MESSAGE,                                      \
    (cmd, set_use_manual_position, cmd.set_use_manual_position), 4) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, get_meteo, cmd.get_meteo), 5)
#define cmd_Gps_Root_CALLBACK NULL
#define cmd_Gps_Root_DEFAULT NULL
#define cmd_Gps_Root_cmd_start_MSGTYPE cmd_Gps_Start
#define cmd_Gps_Root_cmd_stop_MSGTYPE cmd_Gps_Stop
#define cmd_Gps_Root_cmd_set_manual_position_MSGTYPE cmd_Gps_SetManualPosition
#define cmd_Gps_Root_cmd_set_use_manual_position_MSGTYPE \
  cmd_Gps_SetUseManualPosition
#define cmd_Gps_Root_cmd_get_meteo_MSGTYPE cmd_Gps_GetMeteo

#define cmd_Gps_Start_FIELDLIST(X, a)

#define cmd_Gps_Start_CALLBACK NULL
#define cmd_Gps_Start_DEFAULT NULL

#define cmd_Gps_Stop_FIELDLIST(X, a)

#define cmd_Gps_Stop_CALLBACK NULL
#define cmd_Gps_Stop_DEFAULT NULL

#define cmd_Gps_GetMeteo_FIELDLIST(X, a)

#define cmd_Gps_GetMeteo_CALLBACK NULL
#define cmd_Gps_GetMeteo_DEFAULT NULL

#define cmd_Gps_SetUseManualPosition_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, BOOL, flag, 1)
#define cmd_Gps_SetUseManualPosition_CALLBACK NULL
#define cmd_Gps_SetUseManualPosition_DEFAULT NULL

#define cmd_Gps_SetManualPosition_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, latitude, 1)     \
  X(a, STATIC, SINGULAR, DOUBLE, longitude, 2)    \
  X(a, STATIC, SINGULAR, DOUBLE, altitude, 3)
#define cmd_Gps_SetManualPosition_CALLBACK NULL
#define cmd_Gps_SetManualPosition_DEFAULT NULL

  extern const pb_msgdesc_t cmd_Gps_Root_msg;
  extern const pb_msgdesc_t cmd_Gps_Start_msg;
  extern const pb_msgdesc_t cmd_Gps_Stop_msg;
  extern const pb_msgdesc_t cmd_Gps_GetMeteo_msg;
  extern const pb_msgdesc_t cmd_Gps_SetUseManualPosition_msg;
  extern const pb_msgdesc_t cmd_Gps_SetManualPosition_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_Gps_Root_fields &cmd_Gps_Root_msg
#define cmd_Gps_Start_fields &cmd_Gps_Start_msg
#define cmd_Gps_Stop_fields &cmd_Gps_Stop_msg
#define cmd_Gps_GetMeteo_fields &cmd_Gps_GetMeteo_msg
#define cmd_Gps_SetUseManualPosition_fields &cmd_Gps_SetUseManualPosition_msg
#define cmd_Gps_SetManualPosition_fields &cmd_Gps_SetManualPosition_msg

/* Maximum encoded size of messages (where known) */
#define CMD_GPS_JON_SHARED_CMD_GPS_PB_H_MAX_SIZE cmd_Gps_Root_size
#define cmd_Gps_GetMeteo_size 0
#define cmd_Gps_Root_size 29
#define cmd_Gps_SetManualPosition_size 27
#define cmd_Gps_SetUseManualPosition_size 2
#define cmd_Gps_Start_size 0
#define cmd_Gps_Stop_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
