/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_PB_H_INCLUDED
#include "jon_shared_data_actual_space_time.pb.h"
#include "jon_shared_data_camera_day.pb.h"
#include "jon_shared_data_camera_heat.pb.h"
#include "jon_shared_data_compass.pb.h"
#include "jon_shared_data_compass_calibration.pb.h"
#include "jon_shared_data_day_cam_glass_heater.pb.h"
#include "jon_shared_data_gps.pb.h"
#include "jon_shared_data_lrf.pb.h"
#include "jon_shared_data_power.pb.h"
#include "jon_shared_data_rec_osd.pb.h"
#include "jon_shared_data_rotary.pb.h"
#include "jon_shared_data_system.pb.h"
#include "jon_shared_data_time.pb.h"
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Root message */
typedef struct _ser_JonGUIState
{
  uint32_t protocol_version;
  uint64_t system_monotonic_time_us; /* System monotonic time in microseconds */
  ser_JonGuiDataStateSource state_source;
  uint64_t
    frame_pts_day_ns; /* Day pipeline GStreamer buffer PTS in nanoseconds */
  uint64_t
    frame_pts_heat_ns; /* Heat pipeline GStreamer buffer PTS in nanoseconds */
  uint64_t frame_monotonic_day_us; /* Monotonic time when day frame was captured
                                      (microseconds) */
  uint64_t frame_monotonic_heat_us; /* Monotonic time when heat frame was
                                       captured (microseconds) */
  bool has_system;
  ser_JonGuiDataSystem system;
  bool has_meteo_internal;
  ser_JonGuiDataMeteo meteo_internal;
  bool has_lrf;
  ser_JonGuiDataLrf lrf;
  bool has_time;
  ser_JonGuiDataTime time;
  bool has_gps;
  ser_JonGuiDataGps gps;
  bool has_compass;
  ser_JonGuiDataCompass compass;
  bool has_rotary;
  ser_JonGuiDataRotary rotary;
  bool has_camera_day;
  ser_JonGuiDataCameraDay camera_day;
  bool has_camera_heat;
  ser_JonGuiDataCameraHeat camera_heat;
  bool has_compass_calibration;
  ser_JonGuiDataCompassCalibration compass_calibration;
  bool has_rec_osd;
  ser_JonGuiDataRecOsd rec_osd;
  bool has_day_cam_glass_heater;
  ser_JonGuiDataDayCamGlassHeater day_cam_glass_heater;
  bool has_actual_space_time;
  ser_JonGuiDataActualSpaceTime actual_space_time;
  bool has_power;
  ser_JonGuiDataPower power;
} ser_JonGUIState;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define ser_JonGUIState_init_default               \
  { 0,                                             \
    0,                                             \
    _ser_JonGuiDataStateSource_MIN,                \
    0,                                             \
    0,                                             \
    0,                                             \
    0,                                             \
    false,                                         \
    ser_JonGuiDataSystem_init_default,             \
    false,                                         \
    ser_JonGuiDataMeteo_init_default,              \
    false,                                         \
    ser_JonGuiDataLrf_init_default,                \
    false,                                         \
    ser_JonGuiDataTime_init_default,               \
    false,                                         \
    ser_JonGuiDataGps_init_default,                \
    false,                                         \
    ser_JonGuiDataCompass_init_default,            \
    false,                                         \
    ser_JonGuiDataRotary_init_default,             \
    false,                                         \
    ser_JonGuiDataCameraDay_init_default,          \
    false,                                         \
    ser_JonGuiDataCameraHeat_init_default,         \
    false,                                         \
    ser_JonGuiDataCompassCalibration_init_default, \
    false,                                         \
    ser_JonGuiDataRecOsd_init_default,             \
    false,                                         \
    ser_JonGuiDataDayCamGlassHeater_init_default,  \
    false,                                         \
    ser_JonGuiDataActualSpaceTime_init_default,    \
    false,                                         \
    ser_JonGuiDataPower_init_default }
#define ser_JonGUIState_init_zero               \
  { 0,                                          \
    0,                                          \
    _ser_JonGuiDataStateSource_MIN,             \
    0,                                          \
    0,                                          \
    0,                                          \
    0,                                          \
    false,                                      \
    ser_JonGuiDataSystem_init_zero,             \
    false,                                      \
    ser_JonGuiDataMeteo_init_zero,              \
    false,                                      \
    ser_JonGuiDataLrf_init_zero,                \
    false,                                      \
    ser_JonGuiDataTime_init_zero,               \
    false,                                      \
    ser_JonGuiDataGps_init_zero,                \
    false,                                      \
    ser_JonGuiDataCompass_init_zero,            \
    false,                                      \
    ser_JonGuiDataRotary_init_zero,             \
    false,                                      \
    ser_JonGuiDataCameraDay_init_zero,          \
    false,                                      \
    ser_JonGuiDataCameraHeat_init_zero,         \
    false,                                      \
    ser_JonGuiDataCompassCalibration_init_zero, \
    false,                                      \
    ser_JonGuiDataRecOsd_init_zero,             \
    false,                                      \
    ser_JonGuiDataDayCamGlassHeater_init_zero,  \
    false,                                      \
    ser_JonGuiDataActualSpaceTime_init_zero,    \
    false,                                      \
    ser_JonGuiDataPower_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGUIState_protocol_version_tag 1
#define ser_JonGUIState_system_monotonic_time_us_tag 2
#define ser_JonGUIState_state_source_tag 3
#define ser_JonGUIState_frame_pts_day_ns_tag 4
#define ser_JonGUIState_frame_pts_heat_ns_tag 5
#define ser_JonGUIState_frame_monotonic_day_us_tag 6
#define ser_JonGUIState_frame_monotonic_heat_us_tag 7
#define ser_JonGUIState_system_tag 13
#define ser_JonGUIState_meteo_internal_tag 14
#define ser_JonGUIState_lrf_tag 15
#define ser_JonGUIState_time_tag 16
#define ser_JonGUIState_gps_tag 17
#define ser_JonGUIState_compass_tag 18
#define ser_JonGUIState_rotary_tag 19
#define ser_JonGUIState_camera_day_tag 20
#define ser_JonGUIState_camera_heat_tag 21
#define ser_JonGUIState_compass_calibration_tag 22
#define ser_JonGUIState_rec_osd_tag 23
#define ser_JonGUIState_day_cam_glass_heater_tag 24
#define ser_JonGUIState_actual_space_time_tag 25
#define ser_JonGUIState_power_tag 26

/* Struct field encoding specification for nanopb */
#define ser_JonGUIState_FIELDLIST(X, a)                       \
  X(a, STATIC, SINGULAR, UINT32, protocol_version, 1)         \
  X(a, STATIC, SINGULAR, UINT64, system_monotonic_time_us, 2) \
  X(a, STATIC, SINGULAR, UENUM, state_source, 3)              \
  X(a, STATIC, SINGULAR, UINT64, frame_pts_day_ns, 4)         \
  X(a, STATIC, SINGULAR, UINT64, frame_pts_heat_ns, 5)        \
  X(a, STATIC, SINGULAR, UINT64, frame_monotonic_day_us, 6)   \
  X(a, STATIC, SINGULAR, UINT64, frame_monotonic_heat_us, 7)  \
  X(a, STATIC, OPTIONAL, MESSAGE, system, 13)                 \
  X(a, STATIC, OPTIONAL, MESSAGE, meteo_internal, 14)         \
  X(a, STATIC, OPTIONAL, MESSAGE, lrf, 15)                    \
  X(a, STATIC, OPTIONAL, MESSAGE, time, 16)                   \
  X(a, STATIC, OPTIONAL, MESSAGE, gps, 17)                    \
  X(a, STATIC, OPTIONAL, MESSAGE, compass, 18)                \
  X(a, STATIC, OPTIONAL, MESSAGE, rotary, 19)                 \
  X(a, STATIC, OPTIONAL, MESSAGE, camera_day, 20)             \
  X(a, STATIC, OPTIONAL, MESSAGE, camera_heat, 21)            \
  X(a, STATIC, OPTIONAL, MESSAGE, compass_calibration, 22)    \
  X(a, STATIC, OPTIONAL, MESSAGE, rec_osd, 23)                \
  X(a, STATIC, OPTIONAL, MESSAGE, day_cam_glass_heater, 24)   \
  X(a, STATIC, OPTIONAL, MESSAGE, actual_space_time, 25)      \
  X(a, STATIC, OPTIONAL, MESSAGE, power, 26)
#define ser_JonGUIState_CALLBACK NULL
#define ser_JonGUIState_DEFAULT NULL
#define ser_JonGUIState_system_MSGTYPE ser_JonGuiDataSystem
#define ser_JonGUIState_meteo_internal_MSGTYPE ser_JonGuiDataMeteo
#define ser_JonGUIState_lrf_MSGTYPE ser_JonGuiDataLrf
#define ser_JonGUIState_time_MSGTYPE ser_JonGuiDataTime
#define ser_JonGUIState_gps_MSGTYPE ser_JonGuiDataGps
#define ser_JonGUIState_compass_MSGTYPE ser_JonGuiDataCompass
#define ser_JonGUIState_rotary_MSGTYPE ser_JonGuiDataRotary
#define ser_JonGUIState_camera_day_MSGTYPE ser_JonGuiDataCameraDay
#define ser_JonGUIState_camera_heat_MSGTYPE ser_JonGuiDataCameraHeat
#define ser_JonGUIState_compass_calibration_MSGTYPE \
  ser_JonGuiDataCompassCalibration
#define ser_JonGUIState_rec_osd_MSGTYPE ser_JonGuiDataRecOsd
#define ser_JonGUIState_day_cam_glass_heater_MSGTYPE \
  ser_JonGuiDataDayCamGlassHeater
#define ser_JonGUIState_actual_space_time_MSGTYPE ser_JonGuiDataActualSpaceTime
#define ser_JonGUIState_power_MSGTYPE ser_JonGuiDataPower

  extern const pb_msgdesc_t ser_JonGUIState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGUIState_fields &ser_JonGUIState_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_PB_H_MAX_SIZE ser_JonGUIState_size
#define ser_JonGUIState_size 1514

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
