/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_cv.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_CV_Root, cmd_CV_Root, AUTO)


PB_BIND(cmd_CV_VampireModeEnable, cmd_CV_VampireModeEnable, AUTO)


PB_BIND(cmd_CV_DumpStart, cmd_CV_DumpStart, AUTO)


PB_BIND(cmd_CV_DumpStop, cmd_CV_DumpStop, AUTO)


PB_BIND(cmd_CV_VampireModeDisable, cmd_CV_VampireModeDisable, AUTO)


PB_BIND(cmd_CV_StabilizationModeEnable, cmd_CV_StabilizationModeEnable, AUTO)


PB_BIND(cmd_CV_StabilizationModeDisable, cmd_CV_StabilizationModeDisable, AUTO)


PB_BIND(cmd_CV_RecognitionModeEnable, cmd_CV_RecognitionModeEnable, AUTO)


PB_BIND(cmd_CV_RecognitionModeDisable, cmd_CV_RecognitionModeDisable, AUTO)


PB_BIND(cmd_CV_SetAutoFocus, cmd_CV_SetAutoFocus, AUTO)


PB_BIND(cmd_CV_StartTrackNDC, cmd_CV_StartTrackNDC, AUTO)


PB_BIND(cmd_CV_StopTrack, cmd_CV_StopTrack, AUTO)


PB_BIND(cmd_CV_BridgeStart, cmd_CV_BridgeStart, AUTO)


PB_BIND(cmd_CV_BridgeStop, cmd_CV_BridgeStop, AUTO)


PB_BIND(cmd_CV_BridgeRestart, cmd_CV_BridgeRestart, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

