/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_sych_archive.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(jon_archive_SychArchiveIndex, jon_archive_SychArchiveIndex, AUTO)


PB_BIND(jon_archive_ArchiveEntry, jon_archive_ArchiveEntry, AUTO)


PB_BIND(jon_archive_TimelineIndex, jon_archive_TimelineIndex, AUTO)


PB_BIND(jon_archive_VideoEntry, jon_archive_VideoEntry, 2)


PB_BIND(jon_archive_OSDReference, jon_archive_OSDReference, AUTO)
