/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_osd.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_OSD_Root, cmd_OSD_Root, AUTO)


PB_BIND(cmd_OSD_ShowDefaultScreen, cmd_OSD_ShowDefaultScreen, AUTO)


PB_BIND(cmd_OSD_ShowLRFMeasureScreen, cmd_OSD_ShowLRFMeasureScreen, AUTO)


PB_BIND(cmd_OSD_ShowLRFResultScreen, cmd_OSD_ShowLRFResultScreen, AUTO)


PB_BIND(cmd_OSD_ShowLRFResultSimplifiedScreen,
        cmd_OSD_ShowLRFResultSimplifiedScreen,
        AUTO)


PB_BIND(cmd_OSD_EnableHeatOSD, cmd_OSD_EnableHeatOSD, AUTO)


PB_BIND(cmd_OSD_DisableHeatOSD, cmd_OSD_DisableHeatOSD, AUTO)


PB_BIND(cmd_OSD_EnableDayOSD, cmd_OSD_EnableDayOSD, AUTO)


PB_BIND(cmd_OSD_DisableDayOSD, cmd_OSD_DisableDayOSD, AUTO)
