/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_ROTARYPLATFORM_JON_SHARED_CMD_ROTARY_PB_H_INCLUDED
#define PB_CMD_ROTARYPLATFORM_JON_SHARED_CMD_ROTARY_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_RotaryPlatform_SetMode
{
  ser_JonGuiDataRotaryMode mode;
} cmd_RotaryPlatform_SetMode;

typedef struct _cmd_RotaryPlatform_SetAzimuthValue
{
  double value;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_SetAzimuthValue;

typedef struct _cmd_RotaryPlatform_RotateAzimuthTo
{
  double target_value;
  double speed;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_RotateAzimuthTo;

typedef struct _cmd_RotaryPlatform_RotateAzimuth
{
  double speed;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_RotateAzimuth;

typedef struct _cmd_RotaryPlatform_RotateElevation
{
  double speed;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_RotateElevation;

typedef struct _cmd_RotaryPlatform_SetElevationValue
{
  double value;
} cmd_RotaryPlatform_SetElevationValue;

typedef struct _cmd_RotaryPlatform_RotateElevationTo
{
  double target_value;
  double speed;
} cmd_RotaryPlatform_RotateElevationTo;

typedef struct _cmd_RotaryPlatform_RotateElevationRelative
{
  double value;
  double speed;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_RotateElevationRelative;

typedef struct _cmd_RotaryPlatform_RotateElevationRelativeSet
{
  double value;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_RotateElevationRelativeSet;

typedef struct _cmd_RotaryPlatform_RotateAzimuthRelative
{
  double value;
  double speed;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_RotateAzimuthRelative;

typedef struct _cmd_RotaryPlatform_RotateAzimuthRelativeSet
{
  double value;
  ser_JonGuiDataRotaryDirection direction;
} cmd_RotaryPlatform_RotateAzimuthRelativeSet;

typedef struct _cmd_RotaryPlatform_SetPlatformAzimuth
{
  double value;
} cmd_RotaryPlatform_SetPlatformAzimuth;

typedef struct _cmd_RotaryPlatform_SetPlatformElevation
{
  double value;
} cmd_RotaryPlatform_SetPlatformElevation;

typedef struct _cmd_RotaryPlatform_SetPlatformBank
{
  double value;
} cmd_RotaryPlatform_SetPlatformBank;

typedef struct _cmd_RotaryPlatform_GetMeteo
{
  char dummy_field;
} cmd_RotaryPlatform_GetMeteo;

typedef struct _cmd_RotaryPlatform_Start
{
  char dummy_field;
} cmd_RotaryPlatform_Start;

typedef struct _cmd_RotaryPlatform_Stop
{
  char dummy_field;
} cmd_RotaryPlatform_Stop;

typedef struct _cmd_RotaryPlatform_Halt
{
  char dummy_field;
} cmd_RotaryPlatform_Halt;

typedef struct _cmd_RotaryPlatform_ScanStart
{
  char dummy_field;
} cmd_RotaryPlatform_ScanStart;

typedef struct _cmd_RotaryPlatform_ScanStop
{
  char dummy_field;
} cmd_RotaryPlatform_ScanStop;

typedef struct _cmd_RotaryPlatform_ScanPause
{
  char dummy_field;
} cmd_RotaryPlatform_ScanPause;

typedef struct _cmd_RotaryPlatform_ScanUnpause
{
  char dummy_field;
} cmd_RotaryPlatform_ScanUnpause;

typedef struct _cmd_RotaryPlatform_HaltAzimuth
{
  char dummy_field;
} cmd_RotaryPlatform_HaltAzimuth;

typedef struct _cmd_RotaryPlatform_Azimuth
{
  pb_size_t which_cmd;
  union
  {
    cmd_RotaryPlatform_SetAzimuthValue set_value;
    cmd_RotaryPlatform_RotateAzimuthTo rotate_to;
    cmd_RotaryPlatform_RotateAzimuth rotate;
    cmd_RotaryPlatform_RotateAzimuthRelative relative;
    cmd_RotaryPlatform_RotateAzimuthRelativeSet relative_set;
    cmd_RotaryPlatform_HaltAzimuth halt;
  } cmd;
} cmd_RotaryPlatform_Azimuth;

typedef struct _cmd_RotaryPlatform_HaltElevation
{
  char dummy_field;
} cmd_RotaryPlatform_HaltElevation;

typedef struct _cmd_RotaryPlatform_ScanPrev
{
  char dummy_field;
} cmd_RotaryPlatform_ScanPrev;

typedef struct _cmd_RotaryPlatform_ScanNext
{
  char dummy_field;
} cmd_RotaryPlatform_ScanNext;

typedef struct _cmd_RotaryPlatform_ScanRefreshNodeList
{
  char dummy_field;
} cmd_RotaryPlatform_ScanRefreshNodeList;

typedef struct _cmd_RotaryPlatform_ScanSelectNode
{
  int32_t index;
} cmd_RotaryPlatform_ScanSelectNode;

typedef struct _cmd_RotaryPlatform_ScanDeleteNode
{
  int32_t index;
} cmd_RotaryPlatform_ScanDeleteNode;

typedef struct _cmd_RotaryPlatform_ScanUpdateNode
{
  int32_t index;
  int32_t DayZoomTableValue;
  int32_t HeatZoomTableValue;
  double azimuth;
  double elevation;
  double linger;
  double speed;
} cmd_RotaryPlatform_ScanUpdateNode;

typedef struct _cmd_RotaryPlatform_ScanAddNode
{
  int32_t index;
  int32_t DayZoomTableValue;
  int32_t HeatZoomTableValue;
  double azimuth;
  double elevation;
  double linger;
  double speed;
} cmd_RotaryPlatform_ScanAddNode;

typedef struct _cmd_RotaryPlatform_Elevation
{
  pb_size_t which_cmd;
  union
  {
    cmd_RotaryPlatform_SetElevationValue set_value;
    cmd_RotaryPlatform_RotateElevationTo rotate_to;
    cmd_RotaryPlatform_RotateElevation rotate;
    cmd_RotaryPlatform_RotateElevationRelative relative;
    cmd_RotaryPlatform_RotateElevationRelativeSet relative_set;
    cmd_RotaryPlatform_HaltElevation halt;
  } cmd;
} cmd_RotaryPlatform_Elevation;

typedef struct _cmd_RotaryPlatform_Axis
{
  bool has_azimuth;
  cmd_RotaryPlatform_Azimuth azimuth;
  bool has_elevation;
  cmd_RotaryPlatform_Elevation elevation;
} cmd_RotaryPlatform_Axis;

typedef struct _cmd_RotaryPlatform_setUseRotaryAsCompass
{
  bool flag;
} cmd_RotaryPlatform_setUseRotaryAsCompass;

typedef struct _cmd_RotaryPlatform_RotateToGPS
{
  double latitude;
  double longitude;
  double altitude;
} cmd_RotaryPlatform_RotateToGPS;

typedef struct _cmd_RotaryPlatform_SetOriginGPS
{
  double latitude;
  double longitude;
  double altitude;
} cmd_RotaryPlatform_SetOriginGPS;

typedef struct _cmd_RotaryPlatform_RotateToNDC
{
  ser_JonGuiDataVideoChannel channel;
  double x;
  double y;
  uint64_t frame_time; /* Video frame timestamp */
  uint64_t state_time; /* System monotonic time from state when user performed
                          action */
} cmd_RotaryPlatform_RotateToNDC;

typedef struct _cmd_RotaryPlatform_HaltWithNDC
{
  ser_JonGuiDataVideoChannel channel;
  double x;
  double y;
  uint64_t frame_time; /* Video frame timestamp at gesture end */
  uint64_t state_time; /* System monotonic time from state when gesture ended */
} cmd_RotaryPlatform_HaltWithNDC;

typedef struct _cmd_RotaryPlatform_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_RotaryPlatform_Start start;
    cmd_RotaryPlatform_Stop stop;
    cmd_RotaryPlatform_Axis axis;
    cmd_RotaryPlatform_SetPlatformAzimuth set_platform_azimuth;
    cmd_RotaryPlatform_SetPlatformElevation set_platform_elevation;
    cmd_RotaryPlatform_SetPlatformBank set_platform_bank;
    cmd_RotaryPlatform_Halt halt;
    cmd_RotaryPlatform_setUseRotaryAsCompass set_use_rotary_as_compass;
    cmd_RotaryPlatform_RotateToGPS rotate_to_gps;
    cmd_RotaryPlatform_SetOriginGPS set_origin_gps;
    cmd_RotaryPlatform_SetMode set_mode;
    cmd_RotaryPlatform_RotateToNDC rotate_to_ndc;
    cmd_RotaryPlatform_ScanStart scan_start;
    cmd_RotaryPlatform_ScanStop scan_stop;
    cmd_RotaryPlatform_ScanPause scan_pause;
    cmd_RotaryPlatform_ScanUnpause scan_unpause;
    cmd_RotaryPlatform_GetMeteo get_meteo;
    cmd_RotaryPlatform_ScanPrev scan_prev;
    cmd_RotaryPlatform_ScanNext scan_next;
    cmd_RotaryPlatform_ScanRefreshNodeList scan_refresh_node_list;
    cmd_RotaryPlatform_ScanSelectNode scan_select_node;
    cmd_RotaryPlatform_ScanDeleteNode scan_delete_node;
    cmd_RotaryPlatform_ScanUpdateNode scan_update_node;
    cmd_RotaryPlatform_ScanAddNode scan_add_node;
    cmd_RotaryPlatform_HaltWithNDC halt_with_ndc;
  } cmd;
} cmd_RotaryPlatform_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_RotaryPlatform_Root_init_default \
  {                                          \
    0,                                       \
    {                                        \
      cmd_RotaryPlatform_Start_init_default  \
    }                                        \
  }
#define cmd_RotaryPlatform_Axis_init_default               \
  {                                                        \
    false, cmd_RotaryPlatform_Azimuth_init_default, false, \
      cmd_RotaryPlatform_Elevation_init_default            \
  }
#define cmd_RotaryPlatform_SetMode_init_default \
  {                                             \
    _ser_JonGuiDataRotaryMode_MIN               \
  }
#define cmd_RotaryPlatform_SetAzimuthValue_init_default \
  {                                                     \
    0, _ser_JonGuiDataRotaryDirection_MIN               \
  }
#define cmd_RotaryPlatform_RotateAzimuthTo_init_default \
  {                                                     \
    0, 0, _ser_JonGuiDataRotaryDirection_MIN            \
  }
#define cmd_RotaryPlatform_RotateAzimuth_init_default \
  {                                                   \
    0, _ser_JonGuiDataRotaryDirection_MIN             \
  }
#define cmd_RotaryPlatform_RotateElevation_init_default \
  {                                                     \
    0, _ser_JonGuiDataRotaryDirection_MIN               \
  }
#define cmd_RotaryPlatform_SetElevationValue_init_default \
  {                                                       \
    0                                                     \
  }
#define cmd_RotaryPlatform_RotateElevationTo_init_default \
  {                                                       \
    0, 0                                                  \
  }
#define cmd_RotaryPlatform_RotateElevationRelative_init_default \
  {                                                             \
    0, 0, _ser_JonGuiDataRotaryDirection_MIN                    \
  }
#define cmd_RotaryPlatform_RotateElevationRelativeSet_init_default \
  {                                                                \
    0, _ser_JonGuiDataRotaryDirection_MIN                          \
  }
#define cmd_RotaryPlatform_RotateAzimuthRelative_init_default \
  {                                                           \
    0, 0, _ser_JonGuiDataRotaryDirection_MIN                  \
  }
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_init_default \
  {                                                              \
    0, _ser_JonGuiDataRotaryDirection_MIN                        \
  }
#define cmd_RotaryPlatform_SetPlatformAzimuth_init_default \
  {                                                        \
    0                                                      \
  }
#define cmd_RotaryPlatform_SetPlatformElevation_init_default \
  {                                                          \
    0                                                        \
  }
#define cmd_RotaryPlatform_SetPlatformBank_init_default \
  {                                                     \
    0                                                   \
  }
#define cmd_RotaryPlatform_GetMeteo_init_default \
  {                                              \
    0                                            \
  }
#define cmd_RotaryPlatform_Azimuth_init_default       \
  {                                                   \
    0,                                                \
    {                                                 \
      cmd_RotaryPlatform_SetAzimuthValue_init_default \
    }                                                 \
  }
#define cmd_RotaryPlatform_Start_init_default \
  {                                           \
    0                                         \
  }
#define cmd_RotaryPlatform_Stop_init_default \
  {                                          \
    0                                        \
  }
#define cmd_RotaryPlatform_Halt_init_default \
  {                                          \
    0                                        \
  }
#define cmd_RotaryPlatform_ScanStart_init_default \
  {                                               \
    0                                             \
  }
#define cmd_RotaryPlatform_ScanStop_init_default \
  {                                              \
    0                                            \
  }
#define cmd_RotaryPlatform_ScanPause_init_default \
  {                                               \
    0                                             \
  }
#define cmd_RotaryPlatform_ScanUnpause_init_default \
  {                                                 \
    0                                               \
  }
#define cmd_RotaryPlatform_HaltAzimuth_init_default \
  {                                                 \
    0                                               \
  }
#define cmd_RotaryPlatform_HaltElevation_init_default \
  {                                                   \
    0                                                 \
  }
#define cmd_RotaryPlatform_ScanPrev_init_default \
  {                                              \
    0                                            \
  }
#define cmd_RotaryPlatform_ScanNext_init_default \
  {                                              \
    0                                            \
  }
#define cmd_RotaryPlatform_ScanRefreshNodeList_init_default \
  {                                                         \
    0                                                       \
  }
#define cmd_RotaryPlatform_ScanSelectNode_init_default \
  {                                                    \
    0                                                  \
  }
#define cmd_RotaryPlatform_ScanDeleteNode_init_default \
  {                                                    \
    0                                                  \
  }
#define cmd_RotaryPlatform_ScanUpdateNode_init_default \
  {                                                    \
    0, 0, 0, 0, 0, 0, 0                                \
  }
#define cmd_RotaryPlatform_ScanAddNode_init_default \
  {                                                 \
    0, 0, 0, 0, 0, 0, 0                             \
  }
#define cmd_RotaryPlatform_Elevation_init_default       \
  {                                                     \
    0,                                                  \
    {                                                   \
      cmd_RotaryPlatform_SetElevationValue_init_default \
    }                                                   \
  }
#define cmd_RotaryPlatform_setUseRotaryAsCompass_init_default \
  {                                                           \
    0                                                         \
  }
#define cmd_RotaryPlatform_RotateToGPS_init_default \
  {                                                 \
    0, 0, 0                                         \
  }
#define cmd_RotaryPlatform_SetOriginGPS_init_default \
  {                                                  \
    0, 0, 0                                          \
  }
#define cmd_RotaryPlatform_RotateToNDC_init_default \
  {                                                 \
    _ser_JonGuiDataVideoChannel_MIN, 0, 0, 0, 0     \
  }
#define cmd_RotaryPlatform_HaltWithNDC_init_default \
  {                                                 \
    _ser_JonGuiDataVideoChannel_MIN, 0, 0, 0, 0     \
  }
#define cmd_RotaryPlatform_Root_init_zero \
  {                                       \
    0,                                    \
    {                                     \
      cmd_RotaryPlatform_Start_init_zero  \
    }                                     \
  }
#define cmd_RotaryPlatform_Axis_init_zero               \
  {                                                     \
    false, cmd_RotaryPlatform_Azimuth_init_zero, false, \
      cmd_RotaryPlatform_Elevation_init_zero            \
  }
#define cmd_RotaryPlatform_SetMode_init_zero \
  {                                          \
    _ser_JonGuiDataRotaryMode_MIN            \
  }
#define cmd_RotaryPlatform_SetAzimuthValue_init_zero \
  {                                                  \
    0, _ser_JonGuiDataRotaryDirection_MIN            \
  }
#define cmd_RotaryPlatform_RotateAzimuthTo_init_zero \
  {                                                  \
    0, 0, _ser_JonGuiDataRotaryDirection_MIN         \
  }
#define cmd_RotaryPlatform_RotateAzimuth_init_zero \
  {                                                \
    0, _ser_JonGuiDataRotaryDirection_MIN          \
  }
#define cmd_RotaryPlatform_RotateElevation_init_zero \
  {                                                  \
    0, _ser_JonGuiDataRotaryDirection_MIN            \
  }
#define cmd_RotaryPlatform_SetElevationValue_init_zero \
  {                                                    \
    0                                                  \
  }
#define cmd_RotaryPlatform_RotateElevationTo_init_zero \
  {                                                    \
    0, 0                                               \
  }
#define cmd_RotaryPlatform_RotateElevationRelative_init_zero \
  {                                                          \
    0, 0, _ser_JonGuiDataRotaryDirection_MIN                 \
  }
#define cmd_RotaryPlatform_RotateElevationRelativeSet_init_zero \
  {                                                             \
    0, _ser_JonGuiDataRotaryDirection_MIN                       \
  }
#define cmd_RotaryPlatform_RotateAzimuthRelative_init_zero \
  {                                                        \
    0, 0, _ser_JonGuiDataRotaryDirection_MIN               \
  }
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_init_zero \
  {                                                           \
    0, _ser_JonGuiDataRotaryDirection_MIN                     \
  }
#define cmd_RotaryPlatform_SetPlatformAzimuth_init_zero \
  {                                                     \
    0                                                   \
  }
#define cmd_RotaryPlatform_SetPlatformElevation_init_zero \
  {                                                       \
    0                                                     \
  }
#define cmd_RotaryPlatform_SetPlatformBank_init_zero \
  {                                                  \
    0                                                \
  }
#define cmd_RotaryPlatform_GetMeteo_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_RotaryPlatform_Azimuth_init_zero       \
  {                                                \
    0,                                             \
    {                                              \
      cmd_RotaryPlatform_SetAzimuthValue_init_zero \
    }                                              \
  }
#define cmd_RotaryPlatform_Start_init_zero \
  {                                        \
    0                                      \
  }
#define cmd_RotaryPlatform_Stop_init_zero \
  {                                       \
    0                                     \
  }
#define cmd_RotaryPlatform_Halt_init_zero \
  {                                       \
    0                                     \
  }
#define cmd_RotaryPlatform_ScanStart_init_zero \
  {                                            \
    0                                          \
  }
#define cmd_RotaryPlatform_ScanStop_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_RotaryPlatform_ScanPause_init_zero \
  {                                            \
    0                                          \
  }
#define cmd_RotaryPlatform_ScanUnpause_init_zero \
  {                                              \
    0                                            \
  }
#define cmd_RotaryPlatform_HaltAzimuth_init_zero \
  {                                              \
    0                                            \
  }
#define cmd_RotaryPlatform_HaltElevation_init_zero \
  {                                                \
    0                                              \
  }
#define cmd_RotaryPlatform_ScanPrev_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_RotaryPlatform_ScanNext_init_zero \
  {                                           \
    0                                         \
  }
#define cmd_RotaryPlatform_ScanRefreshNodeList_init_zero \
  {                                                      \
    0                                                    \
  }
#define cmd_RotaryPlatform_ScanSelectNode_init_zero \
  {                                                 \
    0                                               \
  }
#define cmd_RotaryPlatform_ScanDeleteNode_init_zero \
  {                                                 \
    0                                               \
  }
#define cmd_RotaryPlatform_ScanUpdateNode_init_zero \
  {                                                 \
    0, 0, 0, 0, 0, 0, 0                             \
  }
#define cmd_RotaryPlatform_ScanAddNode_init_zero \
  {                                              \
    0, 0, 0, 0, 0, 0, 0                          \
  }
#define cmd_RotaryPlatform_Elevation_init_zero       \
  {                                                  \
    0,                                               \
    {                                                \
      cmd_RotaryPlatform_SetElevationValue_init_zero \
    }                                                \
  }
#define cmd_RotaryPlatform_setUseRotaryAsCompass_init_zero \
  {                                                        \
    0                                                      \
  }
#define cmd_RotaryPlatform_RotateToGPS_init_zero \
  {                                              \
    0, 0, 0                                      \
  }
#define cmd_RotaryPlatform_SetOriginGPS_init_zero \
  {                                               \
    0, 0, 0                                       \
  }
#define cmd_RotaryPlatform_RotateToNDC_init_zero \
  {                                              \
    _ser_JonGuiDataVideoChannel_MIN, 0, 0, 0, 0  \
  }
#define cmd_RotaryPlatform_HaltWithNDC_init_zero \
  {                                              \
    _ser_JonGuiDataVideoChannel_MIN, 0, 0, 0, 0  \
  }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_RotaryPlatform_SetMode_mode_tag 1
#define cmd_RotaryPlatform_SetAzimuthValue_value_tag 1
#define cmd_RotaryPlatform_SetAzimuthValue_direction_tag 2
#define cmd_RotaryPlatform_RotateAzimuthTo_target_value_tag 1
#define cmd_RotaryPlatform_RotateAzimuthTo_speed_tag 2
#define cmd_RotaryPlatform_RotateAzimuthTo_direction_tag 3
#define cmd_RotaryPlatform_RotateAzimuth_speed_tag 1
#define cmd_RotaryPlatform_RotateAzimuth_direction_tag 2
#define cmd_RotaryPlatform_RotateElevation_speed_tag 1
#define cmd_RotaryPlatform_RotateElevation_direction_tag 2
#define cmd_RotaryPlatform_SetElevationValue_value_tag 1
#define cmd_RotaryPlatform_RotateElevationTo_target_value_tag 1
#define cmd_RotaryPlatform_RotateElevationTo_speed_tag 2
#define cmd_RotaryPlatform_RotateElevationRelative_value_tag 1
#define cmd_RotaryPlatform_RotateElevationRelative_speed_tag 2
#define cmd_RotaryPlatform_RotateElevationRelative_direction_tag 3
#define cmd_RotaryPlatform_RotateElevationRelativeSet_value_tag 1
#define cmd_RotaryPlatform_RotateElevationRelativeSet_direction_tag 2
#define cmd_RotaryPlatform_RotateAzimuthRelative_value_tag 1
#define cmd_RotaryPlatform_RotateAzimuthRelative_speed_tag 2
#define cmd_RotaryPlatform_RotateAzimuthRelative_direction_tag 3
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_value_tag 1
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_direction_tag 2
#define cmd_RotaryPlatform_SetPlatformAzimuth_value_tag 1
#define cmd_RotaryPlatform_SetPlatformElevation_value_tag 1
#define cmd_RotaryPlatform_SetPlatformBank_value_tag 1
#define cmd_RotaryPlatform_Azimuth_set_value_tag 1
#define cmd_RotaryPlatform_Azimuth_rotate_to_tag 2
#define cmd_RotaryPlatform_Azimuth_rotate_tag 3
#define cmd_RotaryPlatform_Azimuth_relative_tag 4
#define cmd_RotaryPlatform_Azimuth_relative_set_tag 5
#define cmd_RotaryPlatform_Azimuth_halt_tag 6
#define cmd_RotaryPlatform_ScanSelectNode_index_tag 1
#define cmd_RotaryPlatform_ScanDeleteNode_index_tag 1
#define cmd_RotaryPlatform_ScanUpdateNode_index_tag 1
#define cmd_RotaryPlatform_ScanUpdateNode_DayZoomTableValue_tag 2
#define cmd_RotaryPlatform_ScanUpdateNode_HeatZoomTableValue_tag 3
#define cmd_RotaryPlatform_ScanUpdateNode_azimuth_tag 4
#define cmd_RotaryPlatform_ScanUpdateNode_elevation_tag 5
#define cmd_RotaryPlatform_ScanUpdateNode_linger_tag 6
#define cmd_RotaryPlatform_ScanUpdateNode_speed_tag 7
#define cmd_RotaryPlatform_ScanAddNode_index_tag 1
#define cmd_RotaryPlatform_ScanAddNode_DayZoomTableValue_tag 2
#define cmd_RotaryPlatform_ScanAddNode_HeatZoomTableValue_tag 3
#define cmd_RotaryPlatform_ScanAddNode_azimuth_tag 4
#define cmd_RotaryPlatform_ScanAddNode_elevation_tag 5
#define cmd_RotaryPlatform_ScanAddNode_linger_tag 6
#define cmd_RotaryPlatform_ScanAddNode_speed_tag 7
#define cmd_RotaryPlatform_Elevation_set_value_tag 1
#define cmd_RotaryPlatform_Elevation_rotate_to_tag 2
#define cmd_RotaryPlatform_Elevation_rotate_tag 3
#define cmd_RotaryPlatform_Elevation_relative_tag 4
#define cmd_RotaryPlatform_Elevation_relative_set_tag 5
#define cmd_RotaryPlatform_Elevation_halt_tag 6
#define cmd_RotaryPlatform_Axis_azimuth_tag 1
#define cmd_RotaryPlatform_Axis_elevation_tag 2
#define cmd_RotaryPlatform_setUseRotaryAsCompass_flag_tag 1
#define cmd_RotaryPlatform_RotateToGPS_latitude_tag 1
#define cmd_RotaryPlatform_RotateToGPS_longitude_tag 2
#define cmd_RotaryPlatform_RotateToGPS_altitude_tag 3
#define cmd_RotaryPlatform_SetOriginGPS_latitude_tag 1
#define cmd_RotaryPlatform_SetOriginGPS_longitude_tag 2
#define cmd_RotaryPlatform_SetOriginGPS_altitude_tag 3
#define cmd_RotaryPlatform_RotateToNDC_channel_tag 1
#define cmd_RotaryPlatform_RotateToNDC_x_tag 2
#define cmd_RotaryPlatform_RotateToNDC_y_tag 3
#define cmd_RotaryPlatform_RotateToNDC_frame_time_tag 4
#define cmd_RotaryPlatform_RotateToNDC_state_time_tag 5
#define cmd_RotaryPlatform_HaltWithNDC_channel_tag 1
#define cmd_RotaryPlatform_HaltWithNDC_x_tag 2
#define cmd_RotaryPlatform_HaltWithNDC_y_tag 3
#define cmd_RotaryPlatform_HaltWithNDC_frame_time_tag 4
#define cmd_RotaryPlatform_HaltWithNDC_state_time_tag 5
#define cmd_RotaryPlatform_Root_start_tag 1
#define cmd_RotaryPlatform_Root_stop_tag 2
#define cmd_RotaryPlatform_Root_axis_tag 3
#define cmd_RotaryPlatform_Root_set_platform_azimuth_tag 4
#define cmd_RotaryPlatform_Root_set_platform_elevation_tag 5
#define cmd_RotaryPlatform_Root_set_platform_bank_tag 6
#define cmd_RotaryPlatform_Root_halt_tag 7
#define cmd_RotaryPlatform_Root_set_use_rotary_as_compass_tag 8
#define cmd_RotaryPlatform_Root_rotate_to_gps_tag 9
#define cmd_RotaryPlatform_Root_set_origin_gps_tag 10
#define cmd_RotaryPlatform_Root_set_mode_tag 11
#define cmd_RotaryPlatform_Root_rotate_to_ndc_tag 12
#define cmd_RotaryPlatform_Root_scan_start_tag 13
#define cmd_RotaryPlatform_Root_scan_stop_tag 14
#define cmd_RotaryPlatform_Root_scan_pause_tag 15
#define cmd_RotaryPlatform_Root_scan_unpause_tag 16
#define cmd_RotaryPlatform_Root_get_meteo_tag 17
#define cmd_RotaryPlatform_Root_scan_prev_tag 18
#define cmd_RotaryPlatform_Root_scan_next_tag 19
#define cmd_RotaryPlatform_Root_scan_refresh_node_list_tag 20
#define cmd_RotaryPlatform_Root_scan_select_node_tag 21
#define cmd_RotaryPlatform_Root_scan_delete_node_tag 22
#define cmd_RotaryPlatform_Root_scan_update_node_tag 23
#define cmd_RotaryPlatform_Root_scan_add_node_tag 24
#define cmd_RotaryPlatform_Root_halt_with_ndc_tag 25

/* Struct field encoding specification for nanopb */
#define cmd_RotaryPlatform_Root_FIELDLIST(X, a)                               \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start, cmd.start), 1)                    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop, cmd.stop), 2)                      \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, axis, cmd.axis), 3)                      \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_platform_azimuth, cmd.set_platform_azimuth), 4)                 \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_platform_elevation, cmd.set_platform_elevation), 5)             \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_platform_bank, cmd.set_platform_bank), 6)                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, halt, cmd.halt), 7)                      \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_use_rotary_as_compass, cmd.set_use_rotary_as_compass), 8)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, rotate_to_gps, cmd.rotate_to_gps), 9)    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_origin_gps, cmd.set_origin_gps), 10) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_mode, cmd.set_mode), 11)             \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, rotate_to_ndc, cmd.rotate_to_ndc), 12)   \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_start, cmd.scan_start), 13)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_stop, cmd.scan_stop), 14)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_pause, cmd.scan_pause), 15)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_unpause, cmd.scan_unpause), 16)     \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, get_meteo, cmd.get_meteo), 17)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_prev, cmd.scan_prev), 18)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_next, cmd.scan_next), 19)           \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, scan_refresh_node_list, cmd.scan_refresh_node_list), 20)            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_select_node, cmd.scan_select_node), \
    21)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_delete_node, cmd.scan_delete_node), \
    22)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_update_node, cmd.scan_update_node), \
    23)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, scan_add_node, cmd.scan_add_node), 24)   \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, halt_with_ndc, cmd.halt_with_ndc), 25)
#define cmd_RotaryPlatform_Root_CALLBACK NULL
#define cmd_RotaryPlatform_Root_DEFAULT NULL
#define cmd_RotaryPlatform_Root_cmd_start_MSGTYPE cmd_RotaryPlatform_Start
#define cmd_RotaryPlatform_Root_cmd_stop_MSGTYPE cmd_RotaryPlatform_Stop
#define cmd_RotaryPlatform_Root_cmd_axis_MSGTYPE cmd_RotaryPlatform_Axis
#define cmd_RotaryPlatform_Root_cmd_set_platform_azimuth_MSGTYPE \
  cmd_RotaryPlatform_SetPlatformAzimuth
#define cmd_RotaryPlatform_Root_cmd_set_platform_elevation_MSGTYPE \
  cmd_RotaryPlatform_SetPlatformElevation
#define cmd_RotaryPlatform_Root_cmd_set_platform_bank_MSGTYPE \
  cmd_RotaryPlatform_SetPlatformBank
#define cmd_RotaryPlatform_Root_cmd_halt_MSGTYPE cmd_RotaryPlatform_Halt
#define cmd_RotaryPlatform_Root_cmd_set_use_rotary_as_compass_MSGTYPE \
  cmd_RotaryPlatform_setUseRotaryAsCompass
#define cmd_RotaryPlatform_Root_cmd_rotate_to_gps_MSGTYPE \
  cmd_RotaryPlatform_RotateToGPS
#define cmd_RotaryPlatform_Root_cmd_set_origin_gps_MSGTYPE \
  cmd_RotaryPlatform_SetOriginGPS
#define cmd_RotaryPlatform_Root_cmd_set_mode_MSGTYPE cmd_RotaryPlatform_SetMode
#define cmd_RotaryPlatform_Root_cmd_rotate_to_ndc_MSGTYPE \
  cmd_RotaryPlatform_RotateToNDC
#define cmd_RotaryPlatform_Root_cmd_scan_start_MSGTYPE \
  cmd_RotaryPlatform_ScanStart
#define cmd_RotaryPlatform_Root_cmd_scan_stop_MSGTYPE \
  cmd_RotaryPlatform_ScanStop
#define cmd_RotaryPlatform_Root_cmd_scan_pause_MSGTYPE \
  cmd_RotaryPlatform_ScanPause
#define cmd_RotaryPlatform_Root_cmd_scan_unpause_MSGTYPE \
  cmd_RotaryPlatform_ScanUnpause
#define cmd_RotaryPlatform_Root_cmd_get_meteo_MSGTYPE \
  cmd_RotaryPlatform_GetMeteo
#define cmd_RotaryPlatform_Root_cmd_scan_prev_MSGTYPE \
  cmd_RotaryPlatform_ScanPrev
#define cmd_RotaryPlatform_Root_cmd_scan_next_MSGTYPE \
  cmd_RotaryPlatform_ScanNext
#define cmd_RotaryPlatform_Root_cmd_scan_refresh_node_list_MSGTYPE \
  cmd_RotaryPlatform_ScanRefreshNodeList
#define cmd_RotaryPlatform_Root_cmd_scan_select_node_MSGTYPE \
  cmd_RotaryPlatform_ScanSelectNode
#define cmd_RotaryPlatform_Root_cmd_scan_delete_node_MSGTYPE \
  cmd_RotaryPlatform_ScanDeleteNode
#define cmd_RotaryPlatform_Root_cmd_scan_update_node_MSGTYPE \
  cmd_RotaryPlatform_ScanUpdateNode
#define cmd_RotaryPlatform_Root_cmd_scan_add_node_MSGTYPE \
  cmd_RotaryPlatform_ScanAddNode
#define cmd_RotaryPlatform_Root_cmd_halt_with_ndc_MSGTYPE \
  cmd_RotaryPlatform_HaltWithNDC

#define cmd_RotaryPlatform_Axis_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, azimuth, 1)   \
  X(a, STATIC, OPTIONAL, MESSAGE, elevation, 2)
#define cmd_RotaryPlatform_Axis_CALLBACK NULL
#define cmd_RotaryPlatform_Axis_DEFAULT NULL
#define cmd_RotaryPlatform_Axis_azimuth_MSGTYPE cmd_RotaryPlatform_Azimuth
#define cmd_RotaryPlatform_Axis_elevation_MSGTYPE cmd_RotaryPlatform_Elevation

#define cmd_RotaryPlatform_SetMode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, mode, 1)
#define cmd_RotaryPlatform_SetMode_CALLBACK NULL
#define cmd_RotaryPlatform_SetMode_DEFAULT NULL

#define cmd_RotaryPlatform_SetAzimuthValue_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)                 \
  X(a, STATIC, SINGULAR, UENUM, direction, 2)
#define cmd_RotaryPlatform_SetAzimuthValue_CALLBACK NULL
#define cmd_RotaryPlatform_SetAzimuthValue_DEFAULT NULL

#define cmd_RotaryPlatform_RotateAzimuthTo_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, target_value, 1)          \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 2)                 \
  X(a, STATIC, SINGULAR, UENUM, direction, 3)
#define cmd_RotaryPlatform_RotateAzimuthTo_CALLBACK NULL
#define cmd_RotaryPlatform_RotateAzimuthTo_DEFAULT NULL

#define cmd_RotaryPlatform_RotateAzimuth_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 1)               \
  X(a, STATIC, SINGULAR, UENUM, direction, 2)
#define cmd_RotaryPlatform_RotateAzimuth_CALLBACK NULL
#define cmd_RotaryPlatform_RotateAzimuth_DEFAULT NULL

#define cmd_RotaryPlatform_RotateElevation_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 1)                 \
  X(a, STATIC, SINGULAR, UENUM, direction, 2)
#define cmd_RotaryPlatform_RotateElevation_CALLBACK NULL
#define cmd_RotaryPlatform_RotateElevation_DEFAULT NULL

#define cmd_RotaryPlatform_SetElevationValue_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_RotaryPlatform_SetElevationValue_CALLBACK NULL
#define cmd_RotaryPlatform_SetElevationValue_DEFAULT NULL

#define cmd_RotaryPlatform_RotateElevationTo_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, target_value, 1)            \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 2)
#define cmd_RotaryPlatform_RotateElevationTo_CALLBACK NULL
#define cmd_RotaryPlatform_RotateElevationTo_DEFAULT NULL

#define cmd_RotaryPlatform_RotateElevationRelative_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)                         \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 2)                         \
  X(a, STATIC, SINGULAR, UENUM, direction, 3)
#define cmd_RotaryPlatform_RotateElevationRelative_CALLBACK NULL
#define cmd_RotaryPlatform_RotateElevationRelative_DEFAULT NULL

#define cmd_RotaryPlatform_RotateElevationRelativeSet_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)                            \
  X(a, STATIC, SINGULAR, UENUM, direction, 2)
#define cmd_RotaryPlatform_RotateElevationRelativeSet_CALLBACK NULL
#define cmd_RotaryPlatform_RotateElevationRelativeSet_DEFAULT NULL

#define cmd_RotaryPlatform_RotateAzimuthRelative_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)                       \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 2)                       \
  X(a, STATIC, SINGULAR, UENUM, direction, 3)
#define cmd_RotaryPlatform_RotateAzimuthRelative_CALLBACK NULL
#define cmd_RotaryPlatform_RotateAzimuthRelative_DEFAULT NULL

#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)                          \
  X(a, STATIC, SINGULAR, UENUM, direction, 2)
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_CALLBACK NULL
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_DEFAULT NULL

#define cmd_RotaryPlatform_SetPlatformAzimuth_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_RotaryPlatform_SetPlatformAzimuth_CALLBACK NULL
#define cmd_RotaryPlatform_SetPlatformAzimuth_DEFAULT NULL

#define cmd_RotaryPlatform_SetPlatformElevation_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_RotaryPlatform_SetPlatformElevation_CALLBACK NULL
#define cmd_RotaryPlatform_SetPlatformElevation_DEFAULT NULL

#define cmd_RotaryPlatform_SetPlatformBank_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, value, 1)
#define cmd_RotaryPlatform_SetPlatformBank_CALLBACK NULL
#define cmd_RotaryPlatform_SetPlatformBank_DEFAULT NULL

#define cmd_RotaryPlatform_GetMeteo_FIELDLIST(X, a)

#define cmd_RotaryPlatform_GetMeteo_CALLBACK NULL
#define cmd_RotaryPlatform_GetMeteo_DEFAULT NULL

#define cmd_RotaryPlatform_Azimuth_FIELDLIST(X, a)                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_value, cmd.set_value), 1)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, rotate_to, cmd.rotate_to), 2)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, rotate, cmd.rotate), 3)             \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, relative, cmd.relative), 4)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, relative_set, cmd.relative_set), 5) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, halt, cmd.halt), 6)
#define cmd_RotaryPlatform_Azimuth_CALLBACK NULL
#define cmd_RotaryPlatform_Azimuth_DEFAULT NULL
#define cmd_RotaryPlatform_Azimuth_cmd_set_value_MSGTYPE \
  cmd_RotaryPlatform_SetAzimuthValue
#define cmd_RotaryPlatform_Azimuth_cmd_rotate_to_MSGTYPE \
  cmd_RotaryPlatform_RotateAzimuthTo
#define cmd_RotaryPlatform_Azimuth_cmd_rotate_MSGTYPE \
  cmd_RotaryPlatform_RotateAzimuth
#define cmd_RotaryPlatform_Azimuth_cmd_relative_MSGTYPE \
  cmd_RotaryPlatform_RotateAzimuthRelative
#define cmd_RotaryPlatform_Azimuth_cmd_relative_set_MSGTYPE \
  cmd_RotaryPlatform_RotateAzimuthRelativeSet
#define cmd_RotaryPlatform_Azimuth_cmd_halt_MSGTYPE \
  cmd_RotaryPlatform_HaltAzimuth

#define cmd_RotaryPlatform_Start_FIELDLIST(X, a)

#define cmd_RotaryPlatform_Start_CALLBACK NULL
#define cmd_RotaryPlatform_Start_DEFAULT NULL

#define cmd_RotaryPlatform_Stop_FIELDLIST(X, a)

#define cmd_RotaryPlatform_Stop_CALLBACK NULL
#define cmd_RotaryPlatform_Stop_DEFAULT NULL

#define cmd_RotaryPlatform_Halt_FIELDLIST(X, a)

#define cmd_RotaryPlatform_Halt_CALLBACK NULL
#define cmd_RotaryPlatform_Halt_DEFAULT NULL

#define cmd_RotaryPlatform_ScanStart_FIELDLIST(X, a)

#define cmd_RotaryPlatform_ScanStart_CALLBACK NULL
#define cmd_RotaryPlatform_ScanStart_DEFAULT NULL

#define cmd_RotaryPlatform_ScanStop_FIELDLIST(X, a)

#define cmd_RotaryPlatform_ScanStop_CALLBACK NULL
#define cmd_RotaryPlatform_ScanStop_DEFAULT NULL

#define cmd_RotaryPlatform_ScanPause_FIELDLIST(X, a)

#define cmd_RotaryPlatform_ScanPause_CALLBACK NULL
#define cmd_RotaryPlatform_ScanPause_DEFAULT NULL

#define cmd_RotaryPlatform_ScanUnpause_FIELDLIST(X, a)

#define cmd_RotaryPlatform_ScanUnpause_CALLBACK NULL
#define cmd_RotaryPlatform_ScanUnpause_DEFAULT NULL

#define cmd_RotaryPlatform_HaltAzimuth_FIELDLIST(X, a)

#define cmd_RotaryPlatform_HaltAzimuth_CALLBACK NULL
#define cmd_RotaryPlatform_HaltAzimuth_DEFAULT NULL

#define cmd_RotaryPlatform_HaltElevation_FIELDLIST(X, a)

#define cmd_RotaryPlatform_HaltElevation_CALLBACK NULL
#define cmd_RotaryPlatform_HaltElevation_DEFAULT NULL

#define cmd_RotaryPlatform_ScanPrev_FIELDLIST(X, a)

#define cmd_RotaryPlatform_ScanPrev_CALLBACK NULL
#define cmd_RotaryPlatform_ScanPrev_DEFAULT NULL

#define cmd_RotaryPlatform_ScanNext_FIELDLIST(X, a)

#define cmd_RotaryPlatform_ScanNext_CALLBACK NULL
#define cmd_RotaryPlatform_ScanNext_DEFAULT NULL

#define cmd_RotaryPlatform_ScanRefreshNodeList_FIELDLIST(X, a)

#define cmd_RotaryPlatform_ScanRefreshNodeList_CALLBACK NULL
#define cmd_RotaryPlatform_ScanRefreshNodeList_DEFAULT NULL

#define cmd_RotaryPlatform_ScanSelectNode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, index, 1)
#define cmd_RotaryPlatform_ScanSelectNode_CALLBACK NULL
#define cmd_RotaryPlatform_ScanSelectNode_DEFAULT NULL

#define cmd_RotaryPlatform_ScanDeleteNode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, index, 1)
#define cmd_RotaryPlatform_ScanDeleteNode_CALLBACK NULL
#define cmd_RotaryPlatform_ScanDeleteNode_DEFAULT NULL

#define cmd_RotaryPlatform_ScanUpdateNode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, index, 1)                 \
  X(a, STATIC, SINGULAR, INT32, DayZoomTableValue, 2)     \
  X(a, STATIC, SINGULAR, INT32, HeatZoomTableValue, 3)    \
  X(a, STATIC, SINGULAR, DOUBLE, azimuth, 4)              \
  X(a, STATIC, SINGULAR, DOUBLE, elevation, 5)            \
  X(a, STATIC, SINGULAR, DOUBLE, linger, 6)               \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 7)
#define cmd_RotaryPlatform_ScanUpdateNode_CALLBACK NULL
#define cmd_RotaryPlatform_ScanUpdateNode_DEFAULT NULL

#define cmd_RotaryPlatform_ScanAddNode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, index, 1)              \
  X(a, STATIC, SINGULAR, INT32, DayZoomTableValue, 2)  \
  X(a, STATIC, SINGULAR, INT32, HeatZoomTableValue, 3) \
  X(a, STATIC, SINGULAR, DOUBLE, azimuth, 4)           \
  X(a, STATIC, SINGULAR, DOUBLE, elevation, 5)         \
  X(a, STATIC, SINGULAR, DOUBLE, linger, 6)            \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 7)
#define cmd_RotaryPlatform_ScanAddNode_CALLBACK NULL
#define cmd_RotaryPlatform_ScanAddNode_DEFAULT NULL

#define cmd_RotaryPlatform_Elevation_FIELDLIST(X, a)                     \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_value, cmd.set_value), 1)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, rotate_to, cmd.rotate_to), 2)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, rotate, cmd.rotate), 3)             \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, relative, cmd.relative), 4)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, relative_set, cmd.relative_set), 5) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, halt, cmd.halt), 6)
#define cmd_RotaryPlatform_Elevation_CALLBACK NULL
#define cmd_RotaryPlatform_Elevation_DEFAULT NULL
#define cmd_RotaryPlatform_Elevation_cmd_set_value_MSGTYPE \
  cmd_RotaryPlatform_SetElevationValue
#define cmd_RotaryPlatform_Elevation_cmd_rotate_to_MSGTYPE \
  cmd_RotaryPlatform_RotateElevationTo
#define cmd_RotaryPlatform_Elevation_cmd_rotate_MSGTYPE \
  cmd_RotaryPlatform_RotateElevation
#define cmd_RotaryPlatform_Elevation_cmd_relative_MSGTYPE \
  cmd_RotaryPlatform_RotateElevationRelative
#define cmd_RotaryPlatform_Elevation_cmd_relative_set_MSGTYPE \
  cmd_RotaryPlatform_RotateElevationRelativeSet
#define cmd_RotaryPlatform_Elevation_cmd_halt_MSGTYPE \
  cmd_RotaryPlatform_HaltElevation

#define cmd_RotaryPlatform_setUseRotaryAsCompass_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, BOOL, flag, 1)
#define cmd_RotaryPlatform_setUseRotaryAsCompass_CALLBACK NULL
#define cmd_RotaryPlatform_setUseRotaryAsCompass_DEFAULT NULL

#define cmd_RotaryPlatform_RotateToGPS_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, latitude, 1)          \
  X(a, STATIC, SINGULAR, DOUBLE, longitude, 2)         \
  X(a, STATIC, SINGULAR, DOUBLE, altitude, 3)
#define cmd_RotaryPlatform_RotateToGPS_CALLBACK NULL
#define cmd_RotaryPlatform_RotateToGPS_DEFAULT NULL

#define cmd_RotaryPlatform_SetOriginGPS_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, latitude, 1)           \
  X(a, STATIC, SINGULAR, DOUBLE, longitude, 2)          \
  X(a, STATIC, SINGULAR, DOUBLE, altitude, 3)
#define cmd_RotaryPlatform_SetOriginGPS_CALLBACK NULL
#define cmd_RotaryPlatform_SetOriginGPS_DEFAULT NULL

#define cmd_RotaryPlatform_RotateToNDC_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, channel, 1)            \
  X(a, STATIC, SINGULAR, DOUBLE, x, 2)                 \
  X(a, STATIC, SINGULAR, DOUBLE, y, 3)                 \
  X(a, STATIC, SINGULAR, UINT64, frame_time, 4)        \
  X(a, STATIC, SINGULAR, UINT64, state_time, 5)
#define cmd_RotaryPlatform_RotateToNDC_CALLBACK NULL
#define cmd_RotaryPlatform_RotateToNDC_DEFAULT NULL

#define cmd_RotaryPlatform_HaltWithNDC_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, channel, 1)            \
  X(a, STATIC, SINGULAR, DOUBLE, x, 2)                 \
  X(a, STATIC, SINGULAR, DOUBLE, y, 3)                 \
  X(a, STATIC, SINGULAR, UINT64, frame_time, 4)        \
  X(a, STATIC, SINGULAR, UINT64, state_time, 5)
#define cmd_RotaryPlatform_HaltWithNDC_CALLBACK NULL
#define cmd_RotaryPlatform_HaltWithNDC_DEFAULT NULL

  extern const pb_msgdesc_t cmd_RotaryPlatform_Root_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_Axis_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_SetMode_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_SetAzimuthValue_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateAzimuthTo_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateAzimuth_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateElevation_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_SetElevationValue_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateElevationTo_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateElevationRelative_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateElevationRelativeSet_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateAzimuthRelative_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateAzimuthRelativeSet_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_SetPlatformAzimuth_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_SetPlatformElevation_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_SetPlatformBank_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_GetMeteo_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_Azimuth_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_Start_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_Stop_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_Halt_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanStart_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanStop_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanPause_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanUnpause_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_HaltAzimuth_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_HaltElevation_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanPrev_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanNext_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanRefreshNodeList_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanSelectNode_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanDeleteNode_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanUpdateNode_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_ScanAddNode_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_Elevation_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_setUseRotaryAsCompass_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateToGPS_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_SetOriginGPS_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_RotateToNDC_msg;
  extern const pb_msgdesc_t cmd_RotaryPlatform_HaltWithNDC_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_RotaryPlatform_Root_fields &cmd_RotaryPlatform_Root_msg
#define cmd_RotaryPlatform_Axis_fields &cmd_RotaryPlatform_Axis_msg
#define cmd_RotaryPlatform_SetMode_fields &cmd_RotaryPlatform_SetMode_msg
#define cmd_RotaryPlatform_SetAzimuthValue_fields \
  &cmd_RotaryPlatform_SetAzimuthValue_msg
#define cmd_RotaryPlatform_RotateAzimuthTo_fields \
  &cmd_RotaryPlatform_RotateAzimuthTo_msg
#define cmd_RotaryPlatform_RotateAzimuth_fields \
  &cmd_RotaryPlatform_RotateAzimuth_msg
#define cmd_RotaryPlatform_RotateElevation_fields \
  &cmd_RotaryPlatform_RotateElevation_msg
#define cmd_RotaryPlatform_SetElevationValue_fields \
  &cmd_RotaryPlatform_SetElevationValue_msg
#define cmd_RotaryPlatform_RotateElevationTo_fields \
  &cmd_RotaryPlatform_RotateElevationTo_msg
#define cmd_RotaryPlatform_RotateElevationRelative_fields \
  &cmd_RotaryPlatform_RotateElevationRelative_msg
#define cmd_RotaryPlatform_RotateElevationRelativeSet_fields \
  &cmd_RotaryPlatform_RotateElevationRelativeSet_msg
#define cmd_RotaryPlatform_RotateAzimuthRelative_fields \
  &cmd_RotaryPlatform_RotateAzimuthRelative_msg
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_fields \
  &cmd_RotaryPlatform_RotateAzimuthRelativeSet_msg
#define cmd_RotaryPlatform_SetPlatformAzimuth_fields \
  &cmd_RotaryPlatform_SetPlatformAzimuth_msg
#define cmd_RotaryPlatform_SetPlatformElevation_fields \
  &cmd_RotaryPlatform_SetPlatformElevation_msg
#define cmd_RotaryPlatform_SetPlatformBank_fields \
  &cmd_RotaryPlatform_SetPlatformBank_msg
#define cmd_RotaryPlatform_GetMeteo_fields &cmd_RotaryPlatform_GetMeteo_msg
#define cmd_RotaryPlatform_Azimuth_fields &cmd_RotaryPlatform_Azimuth_msg
#define cmd_RotaryPlatform_Start_fields &cmd_RotaryPlatform_Start_msg
#define cmd_RotaryPlatform_Stop_fields &cmd_RotaryPlatform_Stop_msg
#define cmd_RotaryPlatform_Halt_fields &cmd_RotaryPlatform_Halt_msg
#define cmd_RotaryPlatform_ScanStart_fields &cmd_RotaryPlatform_ScanStart_msg
#define cmd_RotaryPlatform_ScanStop_fields &cmd_RotaryPlatform_ScanStop_msg
#define cmd_RotaryPlatform_ScanPause_fields &cmd_RotaryPlatform_ScanPause_msg
#define cmd_RotaryPlatform_ScanUnpause_fields \
  &cmd_RotaryPlatform_ScanUnpause_msg
#define cmd_RotaryPlatform_HaltAzimuth_fields \
  &cmd_RotaryPlatform_HaltAzimuth_msg
#define cmd_RotaryPlatform_HaltElevation_fields \
  &cmd_RotaryPlatform_HaltElevation_msg
#define cmd_RotaryPlatform_ScanPrev_fields &cmd_RotaryPlatform_ScanPrev_msg
#define cmd_RotaryPlatform_ScanNext_fields &cmd_RotaryPlatform_ScanNext_msg
#define cmd_RotaryPlatform_ScanRefreshNodeList_fields \
  &cmd_RotaryPlatform_ScanRefreshNodeList_msg
#define cmd_RotaryPlatform_ScanSelectNode_fields \
  &cmd_RotaryPlatform_ScanSelectNode_msg
#define cmd_RotaryPlatform_ScanDeleteNode_fields \
  &cmd_RotaryPlatform_ScanDeleteNode_msg
#define cmd_RotaryPlatform_ScanUpdateNode_fields \
  &cmd_RotaryPlatform_ScanUpdateNode_msg
#define cmd_RotaryPlatform_ScanAddNode_fields \
  &cmd_RotaryPlatform_ScanAddNode_msg
#define cmd_RotaryPlatform_Elevation_fields &cmd_RotaryPlatform_Elevation_msg
#define cmd_RotaryPlatform_setUseRotaryAsCompass_fields \
  &cmd_RotaryPlatform_setUseRotaryAsCompass_msg
#define cmd_RotaryPlatform_RotateToGPS_fields \
  &cmd_RotaryPlatform_RotateToGPS_msg
#define cmd_RotaryPlatform_SetOriginGPS_fields \
  &cmd_RotaryPlatform_SetOriginGPS_msg
#define cmd_RotaryPlatform_RotateToNDC_fields \
  &cmd_RotaryPlatform_RotateToNDC_msg
#define cmd_RotaryPlatform_HaltWithNDC_fields \
  &cmd_RotaryPlatform_HaltWithNDC_msg

/* Maximum encoded size of messages (where known) */
#define CMD_ROTARYPLATFORM_JON_SHARED_CMD_ROTARY_PB_H_MAX_SIZE \
  cmd_RotaryPlatform_Root_size
#define cmd_RotaryPlatform_Axis_size 48
#define cmd_RotaryPlatform_Azimuth_size 22
#define cmd_RotaryPlatform_Elevation_size 22
#define cmd_RotaryPlatform_GetMeteo_size 0
#define cmd_RotaryPlatform_HaltAzimuth_size 0
#define cmd_RotaryPlatform_HaltElevation_size 0
#define cmd_RotaryPlatform_HaltWithNDC_size 42
#define cmd_RotaryPlatform_Halt_size 0
#define cmd_RotaryPlatform_Root_size 72
#define cmd_RotaryPlatform_RotateAzimuthRelativeSet_size 11
#define cmd_RotaryPlatform_RotateAzimuthRelative_size 20
#define cmd_RotaryPlatform_RotateAzimuthTo_size 20
#define cmd_RotaryPlatform_RotateAzimuth_size 11
#define cmd_RotaryPlatform_RotateElevationRelativeSet_size 11
#define cmd_RotaryPlatform_RotateElevationRelative_size 20
#define cmd_RotaryPlatform_RotateElevationTo_size 18
#define cmd_RotaryPlatform_RotateElevation_size 11
#define cmd_RotaryPlatform_RotateToGPS_size 27
#define cmd_RotaryPlatform_RotateToNDC_size 42
#define cmd_RotaryPlatform_ScanAddNode_size 69
#define cmd_RotaryPlatform_ScanDeleteNode_size 11
#define cmd_RotaryPlatform_ScanNext_size 0
#define cmd_RotaryPlatform_ScanPause_size 0
#define cmd_RotaryPlatform_ScanPrev_size 0
#define cmd_RotaryPlatform_ScanRefreshNodeList_size 0
#define cmd_RotaryPlatform_ScanSelectNode_size 11
#define cmd_RotaryPlatform_ScanStart_size 0
#define cmd_RotaryPlatform_ScanStop_size 0
#define cmd_RotaryPlatform_ScanUnpause_size 0
#define cmd_RotaryPlatform_ScanUpdateNode_size 69
#define cmd_RotaryPlatform_SetAzimuthValue_size 11
#define cmd_RotaryPlatform_SetElevationValue_size 9
#define cmd_RotaryPlatform_SetMode_size 2
#define cmd_RotaryPlatform_SetOriginGPS_size 27
#define cmd_RotaryPlatform_SetPlatformAzimuth_size 9
#define cmd_RotaryPlatform_SetPlatformBank_size 9
#define cmd_RotaryPlatform_SetPlatformElevation_size 9
#define cmd_RotaryPlatform_Start_size 0
#define cmd_RotaryPlatform_Stop_size 0
#define cmd_RotaryPlatform_setUseRotaryAsCompass_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
