/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_ROTARY_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_ROTARY_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ser_ScanNode
{
  int32_t index;
  int32_t DayZoomTableValue;
  int32_t HeatZoomTableValue;
  double azimuth;
  double elevation;
  double linger;
  double speed;
} ser_ScanNode;

typedef struct _ser_JonGuiDataRotary
{
  double azimuth;
  double azimuth_speed;
  double elevation;
  double elevation_speed;
  double platform_azimuth;
  double platform_elevation;
  double platform_bank;
  bool is_moving;
  ser_JonGuiDataRotaryMode mode;
  bool is_scanning;
  bool is_scanning_paused;
  bool use_rotary_as_compass;
  int32_t scan_target;
  int32_t scan_target_max;
  double sun_azimuth;
  double sun_elevation;
  bool has_current_scan_node;
  ser_ScanNode current_scan_node;
} ser_JonGuiDataRotary;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataRotary_init_default                      \
  { 0, 0, 0, 0, 0, 0, 0, 0,     _ser_JonGuiDataRotaryMode_MIN, \
    0, 0, 0, 0, 0, 0, 0, false, ser_ScanNode_init_default }
#define ser_ScanNode_init_default { 0, 0, 0, 0, 0, 0, 0 }
#define ser_JonGuiDataRotary_init_zero                         \
  { 0, 0, 0, 0, 0, 0, 0, 0,     _ser_JonGuiDataRotaryMode_MIN, \
    0, 0, 0, 0, 0, 0, 0, false, ser_ScanNode_init_zero }
#define ser_ScanNode_init_zero { 0, 0, 0, 0, 0, 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define ser_ScanNode_index_tag 1
#define ser_ScanNode_DayZoomTableValue_tag 2
#define ser_ScanNode_HeatZoomTableValue_tag 3
#define ser_ScanNode_azimuth_tag 4
#define ser_ScanNode_elevation_tag 5
#define ser_ScanNode_linger_tag 6
#define ser_ScanNode_speed_tag 7
#define ser_JonGuiDataRotary_azimuth_tag 1
#define ser_JonGuiDataRotary_azimuth_speed_tag 2
#define ser_JonGuiDataRotary_elevation_tag 3
#define ser_JonGuiDataRotary_elevation_speed_tag 4
#define ser_JonGuiDataRotary_platform_azimuth_tag 5
#define ser_JonGuiDataRotary_platform_elevation_tag 6
#define ser_JonGuiDataRotary_platform_bank_tag 7
#define ser_JonGuiDataRotary_is_moving_tag 8
#define ser_JonGuiDataRotary_mode_tag 9
#define ser_JonGuiDataRotary_is_scanning_tag 10
#define ser_JonGuiDataRotary_is_scanning_paused_tag 11
#define ser_JonGuiDataRotary_use_rotary_as_compass_tag 12
#define ser_JonGuiDataRotary_scan_target_tag 13
#define ser_JonGuiDataRotary_scan_target_max_tag 14
#define ser_JonGuiDataRotary_sun_azimuth_tag 15
#define ser_JonGuiDataRotary_sun_elevation_tag 16
#define ser_JonGuiDataRotary_current_scan_node_tag 17

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataRotary_FIELDLIST(X, a)              \
  X(a, STATIC, SINGULAR, DOUBLE, azimuth, 1)              \
  X(a, STATIC, SINGULAR, DOUBLE, azimuth_speed, 2)        \
  X(a, STATIC, SINGULAR, DOUBLE, elevation, 3)            \
  X(a, STATIC, SINGULAR, DOUBLE, elevation_speed, 4)      \
  X(a, STATIC, SINGULAR, DOUBLE, platform_azimuth, 5)     \
  X(a, STATIC, SINGULAR, DOUBLE, platform_elevation, 6)   \
  X(a, STATIC, SINGULAR, DOUBLE, platform_bank, 7)        \
  X(a, STATIC, SINGULAR, BOOL, is_moving, 8)              \
  X(a, STATIC, SINGULAR, UENUM, mode, 9)                  \
  X(a, STATIC, SINGULAR, BOOL, is_scanning, 10)           \
  X(a, STATIC, SINGULAR, BOOL, is_scanning_paused, 11)    \
  X(a, STATIC, SINGULAR, BOOL, use_rotary_as_compass, 12) \
  X(a, STATIC, SINGULAR, INT32, scan_target, 13)          \
  X(a, STATIC, SINGULAR, INT32, scan_target_max, 14)      \
  X(a, STATIC, SINGULAR, DOUBLE, sun_azimuth, 15)         \
  X(a, STATIC, SINGULAR, DOUBLE, sun_elevation, 16)       \
  X(a, STATIC, OPTIONAL, MESSAGE, current_scan_node, 17)
#define ser_JonGuiDataRotary_CALLBACK NULL
#define ser_JonGuiDataRotary_DEFAULT NULL
#define ser_JonGuiDataRotary_current_scan_node_MSGTYPE ser_ScanNode

#define ser_ScanNode_FIELDLIST(X, a)                   \
  X(a, STATIC, SINGULAR, INT32, index, 1)              \
  X(a, STATIC, SINGULAR, INT32, DayZoomTableValue, 2)  \
  X(a, STATIC, SINGULAR, INT32, HeatZoomTableValue, 3) \
  X(a, STATIC, SINGULAR, DOUBLE, azimuth, 4)           \
  X(a, STATIC, SINGULAR, DOUBLE, elevation, 5)         \
  X(a, STATIC, SINGULAR, DOUBLE, linger, 6)            \
  X(a, STATIC, SINGULAR, DOUBLE, speed, 7)
#define ser_ScanNode_CALLBACK NULL
#define ser_ScanNode_DEFAULT NULL

  extern const pb_msgdesc_t ser_JonGuiDataRotary_msg;
  extern const pb_msgdesc_t ser_ScanNode_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataRotary_fields &ser_JonGuiDataRotary_msg
#define ser_ScanNode_fields &ser_ScanNode_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_ROTARY_PB_H_MAX_SIZE ser_JonGuiDataRotary_size
#define ser_JonGuiDataRotary_size 186
#define ser_ScanNode_size 69

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
