/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_ACTUAL_SPACE_TIME_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_ACTUAL_SPACE_TIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ser_JonGuiDataActualSpaceTime {
    double azimuth;
    double elevation;
    double bank;
    double latitude;
    double longitude;
    double altitude;
    int64_t timestamp;
} ser_JonGuiDataActualSpaceTime;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataActualSpaceTime_init_default {0, 0, 0, 0, 0, 0, 0}
#define ser_JonGuiDataActualSpaceTime_init_zero  {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataActualSpaceTime_azimuth_tag 1
#define ser_JonGuiDataActualSpaceTime_elevation_tag 2
#define ser_JonGuiDataActualSpaceTime_bank_tag   3
#define ser_JonGuiDataActualSpaceTime_latitude_tag 4
#define ser_JonGuiDataActualSpaceTime_longitude_tag 5
#define ser_JonGuiDataActualSpaceTime_altitude_tag 6
#define ser_JonGuiDataActualSpaceTime_timestamp_tag 7

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataActualSpaceTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   azimuth,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   elevation,         2) \
X(a, STATIC,   SINGULAR, DOUBLE,   bank,              3) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          4) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         5) \
X(a, STATIC,   SINGULAR, DOUBLE,   altitude,          6) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         7)
#define ser_JonGuiDataActualSpaceTime_CALLBACK NULL
#define ser_JonGuiDataActualSpaceTime_DEFAULT NULL

extern const pb_msgdesc_t ser_JonGuiDataActualSpaceTime_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataActualSpaceTime_fields &ser_JonGuiDataActualSpaceTime_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_ACTUAL_SPACE_TIME_PB_H_MAX_SIZE ser_JonGuiDataActualSpaceTime_size
#define ser_JonGuiDataActualSpaceTime_size       65

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
