/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_DAYCAMERA_JON_SHARED_CMD_DAY_CAMERA_PB_H_INCLUDED
#define PB_CMD_DAYCAMERA_JON_SHARED_CMD_DAY_CAMERA_PB_H_INCLUDED
#include <pb.h>
#include "jon_shared_data_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_DayCamera_SetValue {
    double value;
} cmd_DayCamera_SetValue;

typedef struct _cmd_DayCamera_Move {
    double target_value;
    double speed;
} cmd_DayCamera_Move;

typedef struct _cmd_DayCamera_Offset {
    double offset_value;
} cmd_DayCamera_Offset;

typedef struct _cmd_DayCamera_SetClaheLevel {
    double value;
} cmd_DayCamera_SetClaheLevel;

typedef struct _cmd_DayCamera_ShiftClaheLevel {
    double value;
} cmd_DayCamera_ShiftClaheLevel;

typedef struct _cmd_DayCamera_GetPos {
    char dummy_field;
} cmd_DayCamera_GetPos;

typedef struct _cmd_DayCamera_NextFxMode {
    char dummy_field;
} cmd_DayCamera_NextFxMode;

typedef struct _cmd_DayCamera_PrevFxMode {
    char dummy_field;
} cmd_DayCamera_PrevFxMode;

typedef struct _cmd_DayCamera_RefreshFxMode {
    char dummy_field;
} cmd_DayCamera_RefreshFxMode;

typedef struct _cmd_DayCamera_HaltAll {
    char dummy_field;
} cmd_DayCamera_HaltAll;

typedef struct _cmd_DayCamera_SetFxMode {
    ser_JonGuiDataFxModeDay mode;
} cmd_DayCamera_SetFxMode;

typedef struct _cmd_DayCamera_SetDigitalZoomLevel {
    double value;
} cmd_DayCamera_SetDigitalZoomLevel;

typedef struct _cmd_DayCamera_NextZoomTablePos {
    char dummy_field;
} cmd_DayCamera_NextZoomTablePos;

typedef struct _cmd_DayCamera_PrevZoomTablePos {
    char dummy_field;
} cmd_DayCamera_PrevZoomTablePos;

typedef struct _cmd_DayCamera_SetIris {
    double value;
} cmd_DayCamera_SetIris;

typedef struct _cmd_DayCamera_SetInfraRedFilter {
    bool value;
} cmd_DayCamera_SetInfraRedFilter;

typedef struct _cmd_DayCamera_SetAutoIris {
    bool value;
} cmd_DayCamera_SetAutoIris;

typedef struct _cmd_DayCamera_SetAutoGain {
    bool value;
} cmd_DayCamera_SetAutoGain;

typedef struct _cmd_DayCamera_SetZoomTableValue {
    int32_t value;
} cmd_DayCamera_SetZoomTableValue;

typedef struct _cmd_DayCamera_Stop {
    char dummy_field;
} cmd_DayCamera_Stop;

typedef struct _cmd_DayCamera_Start {
    char dummy_field;
} cmd_DayCamera_Start;

typedef struct _cmd_DayCamera_Photo {
    char dummy_field;
} cmd_DayCamera_Photo;

typedef struct _cmd_DayCamera_Halt {
    char dummy_field;
} cmd_DayCamera_Halt;

typedef struct _cmd_DayCamera_GetMeteo {
    char dummy_field;
} cmd_DayCamera_GetMeteo;

typedef struct _cmd_DayCamera_ResetZoom {
    char dummy_field;
} cmd_DayCamera_ResetZoom;

typedef struct _cmd_DayCamera_ResetFocus {
    char dummy_field;
} cmd_DayCamera_ResetFocus;

typedef struct _cmd_DayCamera_SaveToTable {
    char dummy_field;
} cmd_DayCamera_SaveToTable;

typedef struct _cmd_DayCamera_Zoom {
    pb_size_t which_cmd;
    union {
        cmd_DayCamera_SetValue set_value;
        cmd_DayCamera_Move move;
        cmd_DayCamera_Halt halt;
        cmd_DayCamera_SetZoomTableValue set_zoom_table_value;
        cmd_DayCamera_NextZoomTablePos next_zoom_table_pos;
        cmd_DayCamera_PrevZoomTablePos prev_zoom_table_pos;
        cmd_DayCamera_Offset offset;
        cmd_DayCamera_ResetZoom reset_zoom;
        cmd_DayCamera_SaveToTable save_to_table;
    } cmd;
} cmd_DayCamera_Zoom;

typedef struct _cmd_DayCamera_SaveToTableFocus {
    char dummy_field;
} cmd_DayCamera_SaveToTableFocus;

typedef struct _cmd_DayCamera_Focus {
    pb_size_t which_cmd;
    union {
        cmd_DayCamera_SetValue set_value;
        cmd_DayCamera_Move move;
        cmd_DayCamera_Halt halt;
        cmd_DayCamera_Offset offset;
        cmd_DayCamera_ResetFocus reset_focus;
        cmd_DayCamera_SaveToTableFocus save_to_table_focus;
    } cmd;
} cmd_DayCamera_Focus;

typedef struct _cmd_DayCamera_FocusROI {
    double x1;
    double y1;
    double x2;
    double y2;
    /* TODO: Remove these fields after migration - now in Root message (fields 6-8) */
    uint64_t frame_time;
    uint64_t state_time; /* System monotonic time from state when user performed action */
} cmd_DayCamera_FocusROI;

typedef struct _cmd_DayCamera_TrackROI {
    double x1;
    double y1;
    double x2;
    double y2;
    /* TODO: Remove these fields after migration - now in Root message (fields 6-8) */
    uint64_t frame_time;
    uint64_t state_time; /* System monotonic time from state when user performed action */
} cmd_DayCamera_TrackROI;

typedef struct _cmd_DayCamera_ZoomROI {
    double x1;
    double y1;
    double x2;
    double y2;
    /* TODO: Remove these fields after migration - now in Root message (fields 6-8) */
    uint64_t frame_time;
    uint64_t state_time; /* System monotonic time from state when user performed action */
} cmd_DayCamera_ZoomROI;

typedef struct _cmd_DayCamera_FxROI {
    double x1;
    double y1;
    double x2;
    double y2;
    /* TODO: Remove these fields after migration - now in Root message (fields 6-8) */
    uint64_t frame_time;
    uint64_t state_time; /* System monotonic time from state when user performed action */
} cmd_DayCamera_FxROI;

typedef struct _cmd_DayCamera_Root {
    pb_size_t which_cmd;
    union {
        cmd_DayCamera_Focus focus;
        cmd_DayCamera_Zoom zoom;
        cmd_DayCamera_SetIris set_iris;
        cmd_DayCamera_SetInfraRedFilter set_infra_red_filter;
        cmd_DayCamera_Start start;
        cmd_DayCamera_Stop stop;
        cmd_DayCamera_Photo photo;
        cmd_DayCamera_SetAutoIris set_auto_iris;
        cmd_DayCamera_HaltAll halt_all;
        cmd_DayCamera_SetFxMode set_fx_mode;
        cmd_DayCamera_NextFxMode next_fx_mode;
        cmd_DayCamera_PrevFxMode prev_fx_mode;
        cmd_DayCamera_GetMeteo get_meteo;
        cmd_DayCamera_RefreshFxMode refresh_fx_mode;
        cmd_DayCamera_SetDigitalZoomLevel set_digital_zoom_level;
        cmd_DayCamera_SetClaheLevel set_clahe_level;
        cmd_DayCamera_ShiftClaheLevel shift_clahe_level;
        cmd_DayCamera_FocusROI focus_roi;
        cmd_DayCamera_TrackROI track_roi;
        cmd_DayCamera_ZoomROI zoom_roi;
        cmd_DayCamera_FxROI fx_roi;
        cmd_DayCamera_SetAutoGain set_auto_gain;
    } cmd;
} cmd_DayCamera_Root;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cmd_DayCamera_SetValue_init_default      {0}
#define cmd_DayCamera_Move_init_default          {0, 0}
#define cmd_DayCamera_Offset_init_default        {0}
#define cmd_DayCamera_SetClaheLevel_init_default {0}
#define cmd_DayCamera_ShiftClaheLevel_init_default {0}
#define cmd_DayCamera_Root_init_default          {0, {cmd_DayCamera_Focus_init_default}}
#define cmd_DayCamera_GetPos_init_default        {0}
#define cmd_DayCamera_NextFxMode_init_default    {0}
#define cmd_DayCamera_PrevFxMode_init_default    {0}
#define cmd_DayCamera_RefreshFxMode_init_default {0}
#define cmd_DayCamera_HaltAll_init_default       {0}
#define cmd_DayCamera_SetFxMode_init_default     {_ser_JonGuiDataFxModeDay_MIN}
#define cmd_DayCamera_SetDigitalZoomLevel_init_default {0}
#define cmd_DayCamera_Focus_init_default         {0, {cmd_DayCamera_SetValue_init_default}}
#define cmd_DayCamera_Zoom_init_default          {0, {cmd_DayCamera_SetValue_init_default}}
#define cmd_DayCamera_NextZoomTablePos_init_default {0}
#define cmd_DayCamera_PrevZoomTablePos_init_default {0}
#define cmd_DayCamera_SetIris_init_default       {0}
#define cmd_DayCamera_SetInfraRedFilter_init_default {0}
#define cmd_DayCamera_SetAutoIris_init_default   {0}
#define cmd_DayCamera_SetAutoGain_init_default   {0}
#define cmd_DayCamera_SetZoomTableValue_init_default {0}
#define cmd_DayCamera_Stop_init_default          {0}
#define cmd_DayCamera_Start_init_default         {0}
#define cmd_DayCamera_Photo_init_default         {0}
#define cmd_DayCamera_Halt_init_default          {0}
#define cmd_DayCamera_GetMeteo_init_default      {0}
#define cmd_DayCamera_ResetZoom_init_default     {0}
#define cmd_DayCamera_ResetFocus_init_default    {0}
#define cmd_DayCamera_SaveToTable_init_default   {0}
#define cmd_DayCamera_SaveToTableFocus_init_default {0}
#define cmd_DayCamera_FocusROI_init_default      {0, 0, 0, 0, 0, 0}
#define cmd_DayCamera_TrackROI_init_default      {0, 0, 0, 0, 0, 0}
#define cmd_DayCamera_ZoomROI_init_default       {0, 0, 0, 0, 0, 0}
#define cmd_DayCamera_FxROI_init_default         {0, 0, 0, 0, 0, 0}
#define cmd_DayCamera_SetValue_init_zero         {0}
#define cmd_DayCamera_Move_init_zero             {0, 0}
#define cmd_DayCamera_Offset_init_zero           {0}
#define cmd_DayCamera_SetClaheLevel_init_zero    {0}
#define cmd_DayCamera_ShiftClaheLevel_init_zero  {0}
#define cmd_DayCamera_Root_init_zero             {0, {cmd_DayCamera_Focus_init_zero}}
#define cmd_DayCamera_GetPos_init_zero           {0}
#define cmd_DayCamera_NextFxMode_init_zero       {0}
#define cmd_DayCamera_PrevFxMode_init_zero       {0}
#define cmd_DayCamera_RefreshFxMode_init_zero    {0}
#define cmd_DayCamera_HaltAll_init_zero          {0}
#define cmd_DayCamera_SetFxMode_init_zero        {_ser_JonGuiDataFxModeDay_MIN}
#define cmd_DayCamera_SetDigitalZoomLevel_init_zero {0}
#define cmd_DayCamera_Focus_init_zero            {0, {cmd_DayCamera_SetValue_init_zero}}
#define cmd_DayCamera_Zoom_init_zero             {0, {cmd_DayCamera_SetValue_init_zero}}
#define cmd_DayCamera_NextZoomTablePos_init_zero {0}
#define cmd_DayCamera_PrevZoomTablePos_init_zero {0}
#define cmd_DayCamera_SetIris_init_zero          {0}
#define cmd_DayCamera_SetInfraRedFilter_init_zero {0}
#define cmd_DayCamera_SetAutoIris_init_zero      {0}
#define cmd_DayCamera_SetAutoGain_init_zero      {0}
#define cmd_DayCamera_SetZoomTableValue_init_zero {0}
#define cmd_DayCamera_Stop_init_zero             {0}
#define cmd_DayCamera_Start_init_zero            {0}
#define cmd_DayCamera_Photo_init_zero            {0}
#define cmd_DayCamera_Halt_init_zero             {0}
#define cmd_DayCamera_GetMeteo_init_zero         {0}
#define cmd_DayCamera_ResetZoom_init_zero        {0}
#define cmd_DayCamera_ResetFocus_init_zero       {0}
#define cmd_DayCamera_SaveToTable_init_zero      {0}
#define cmd_DayCamera_SaveToTableFocus_init_zero {0}
#define cmd_DayCamera_FocusROI_init_zero         {0, 0, 0, 0, 0, 0}
#define cmd_DayCamera_TrackROI_init_zero         {0, 0, 0, 0, 0, 0}
#define cmd_DayCamera_ZoomROI_init_zero          {0, 0, 0, 0, 0, 0}
#define cmd_DayCamera_FxROI_init_zero            {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define cmd_DayCamera_SetValue_value_tag         1
#define cmd_DayCamera_Move_target_value_tag      1
#define cmd_DayCamera_Move_speed_tag             2
#define cmd_DayCamera_Offset_offset_value_tag    1
#define cmd_DayCamera_SetClaheLevel_value_tag    1
#define cmd_DayCamera_ShiftClaheLevel_value_tag  1
#define cmd_DayCamera_SetFxMode_mode_tag         1
#define cmd_DayCamera_SetDigitalZoomLevel_value_tag 1
#define cmd_DayCamera_SetIris_value_tag          1
#define cmd_DayCamera_SetInfraRedFilter_value_tag 1
#define cmd_DayCamera_SetAutoIris_value_tag      1
#define cmd_DayCamera_SetAutoGain_value_tag      1
#define cmd_DayCamera_SetZoomTableValue_value_tag 1
#define cmd_DayCamera_Zoom_set_value_tag         1
#define cmd_DayCamera_Zoom_move_tag              2
#define cmd_DayCamera_Zoom_halt_tag              3
#define cmd_DayCamera_Zoom_set_zoom_table_value_tag 4
#define cmd_DayCamera_Zoom_next_zoom_table_pos_tag 5
#define cmd_DayCamera_Zoom_prev_zoom_table_pos_tag 6
#define cmd_DayCamera_Zoom_offset_tag            7
#define cmd_DayCamera_Zoom_reset_zoom_tag        8
#define cmd_DayCamera_Zoom_save_to_table_tag     9
#define cmd_DayCamera_Focus_set_value_tag        1
#define cmd_DayCamera_Focus_move_tag             2
#define cmd_DayCamera_Focus_halt_tag             3
#define cmd_DayCamera_Focus_offset_tag           4
#define cmd_DayCamera_Focus_reset_focus_tag      5
#define cmd_DayCamera_Focus_save_to_table_focus_tag 6
#define cmd_DayCamera_FocusROI_x1_tag            1
#define cmd_DayCamera_FocusROI_y1_tag            2
#define cmd_DayCamera_FocusROI_x2_tag            3
#define cmd_DayCamera_FocusROI_y2_tag            4
#define cmd_DayCamera_FocusROI_frame_time_tag    5
#define cmd_DayCamera_FocusROI_state_time_tag    6
#define cmd_DayCamera_TrackROI_x1_tag            1
#define cmd_DayCamera_TrackROI_y1_tag            2
#define cmd_DayCamera_TrackROI_x2_tag            3
#define cmd_DayCamera_TrackROI_y2_tag            4
#define cmd_DayCamera_TrackROI_frame_time_tag    5
#define cmd_DayCamera_TrackROI_state_time_tag    6
#define cmd_DayCamera_ZoomROI_x1_tag             1
#define cmd_DayCamera_ZoomROI_y1_tag             2
#define cmd_DayCamera_ZoomROI_x2_tag             3
#define cmd_DayCamera_ZoomROI_y2_tag             4
#define cmd_DayCamera_ZoomROI_frame_time_tag     5
#define cmd_DayCamera_ZoomROI_state_time_tag     6
#define cmd_DayCamera_FxROI_x1_tag               1
#define cmd_DayCamera_FxROI_y1_tag               2
#define cmd_DayCamera_FxROI_x2_tag               3
#define cmd_DayCamera_FxROI_y2_tag               4
#define cmd_DayCamera_FxROI_frame_time_tag       5
#define cmd_DayCamera_FxROI_state_time_tag       6
#define cmd_DayCamera_Root_focus_tag             1
#define cmd_DayCamera_Root_zoom_tag              2
#define cmd_DayCamera_Root_set_iris_tag          3
#define cmd_DayCamera_Root_set_infra_red_filter_tag 4
#define cmd_DayCamera_Root_start_tag             5
#define cmd_DayCamera_Root_stop_tag              6
#define cmd_DayCamera_Root_photo_tag             7
#define cmd_DayCamera_Root_set_auto_iris_tag     8
#define cmd_DayCamera_Root_halt_all_tag          9
#define cmd_DayCamera_Root_set_fx_mode_tag       10
#define cmd_DayCamera_Root_next_fx_mode_tag      11
#define cmd_DayCamera_Root_prev_fx_mode_tag      12
#define cmd_DayCamera_Root_get_meteo_tag         13
#define cmd_DayCamera_Root_refresh_fx_mode_tag   14
#define cmd_DayCamera_Root_set_digital_zoom_level_tag 15
#define cmd_DayCamera_Root_set_clahe_level_tag   16
#define cmd_DayCamera_Root_shift_clahe_level_tag 17
#define cmd_DayCamera_Root_focus_roi_tag         18
#define cmd_DayCamera_Root_track_roi_tag         19
#define cmd_DayCamera_Root_zoom_roi_tag          20
#define cmd_DayCamera_Root_fx_roi_tag            21
#define cmd_DayCamera_Root_set_auto_gain_tag     22

/* Struct field encoding specification for nanopb */
#define cmd_DayCamera_SetValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1)
#define cmd_DayCamera_SetValue_CALLBACK NULL
#define cmd_DayCamera_SetValue_DEFAULT NULL

#define cmd_DayCamera_Move_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   target_value,      1) \
X(a, STATIC,   SINGULAR, DOUBLE,   speed,             2)
#define cmd_DayCamera_Move_CALLBACK NULL
#define cmd_DayCamera_Move_DEFAULT NULL

#define cmd_DayCamera_Offset_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   offset_value,      1)
#define cmd_DayCamera_Offset_CALLBACK NULL
#define cmd_DayCamera_Offset_DEFAULT NULL

#define cmd_DayCamera_SetClaheLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1)
#define cmd_DayCamera_SetClaheLevel_CALLBACK NULL
#define cmd_DayCamera_SetClaheLevel_DEFAULT NULL

#define cmd_DayCamera_ShiftClaheLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1)
#define cmd_DayCamera_ShiftClaheLevel_CALLBACK NULL
#define cmd_DayCamera_ShiftClaheLevel_DEFAULT NULL

#define cmd_DayCamera_Root_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,focus,cmd.focus),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,zoom,cmd.zoom),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_iris,cmd.set_iris),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_infra_red_filter,cmd.set_infra_red_filter),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,start,cmd.start),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,stop,cmd.stop),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,photo,cmd.photo),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_auto_iris,cmd.set_auto_iris),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,halt_all,cmd.halt_all),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_fx_mode,cmd.set_fx_mode),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,next_fx_mode,cmd.next_fx_mode),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,prev_fx_mode,cmd.prev_fx_mode),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,get_meteo,cmd.get_meteo),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,refresh_fx_mode,cmd.refresh_fx_mode),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_digital_zoom_level,cmd.set_digital_zoom_level),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_clahe_level,cmd.set_clahe_level),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,shift_clahe_level,cmd.shift_clahe_level),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,focus_roi,cmd.focus_roi),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,track_roi,cmd.track_roi),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,zoom_roi,cmd.zoom_roi),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,fx_roi,cmd.fx_roi),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_auto_gain,cmd.set_auto_gain),  22)
#define cmd_DayCamera_Root_CALLBACK NULL
#define cmd_DayCamera_Root_DEFAULT NULL
#define cmd_DayCamera_Root_cmd_focus_MSGTYPE cmd_DayCamera_Focus
#define cmd_DayCamera_Root_cmd_zoom_MSGTYPE cmd_DayCamera_Zoom
#define cmd_DayCamera_Root_cmd_set_iris_MSGTYPE cmd_DayCamera_SetIris
#define cmd_DayCamera_Root_cmd_set_infra_red_filter_MSGTYPE cmd_DayCamera_SetInfraRedFilter
#define cmd_DayCamera_Root_cmd_start_MSGTYPE cmd_DayCamera_Start
#define cmd_DayCamera_Root_cmd_stop_MSGTYPE cmd_DayCamera_Stop
#define cmd_DayCamera_Root_cmd_photo_MSGTYPE cmd_DayCamera_Photo
#define cmd_DayCamera_Root_cmd_set_auto_iris_MSGTYPE cmd_DayCamera_SetAutoIris
#define cmd_DayCamera_Root_cmd_halt_all_MSGTYPE cmd_DayCamera_HaltAll
#define cmd_DayCamera_Root_cmd_set_fx_mode_MSGTYPE cmd_DayCamera_SetFxMode
#define cmd_DayCamera_Root_cmd_next_fx_mode_MSGTYPE cmd_DayCamera_NextFxMode
#define cmd_DayCamera_Root_cmd_prev_fx_mode_MSGTYPE cmd_DayCamera_PrevFxMode
#define cmd_DayCamera_Root_cmd_get_meteo_MSGTYPE cmd_DayCamera_GetMeteo
#define cmd_DayCamera_Root_cmd_refresh_fx_mode_MSGTYPE cmd_DayCamera_RefreshFxMode
#define cmd_DayCamera_Root_cmd_set_digital_zoom_level_MSGTYPE cmd_DayCamera_SetDigitalZoomLevel
#define cmd_DayCamera_Root_cmd_set_clahe_level_MSGTYPE cmd_DayCamera_SetClaheLevel
#define cmd_DayCamera_Root_cmd_shift_clahe_level_MSGTYPE cmd_DayCamera_ShiftClaheLevel
#define cmd_DayCamera_Root_cmd_focus_roi_MSGTYPE cmd_DayCamera_FocusROI
#define cmd_DayCamera_Root_cmd_track_roi_MSGTYPE cmd_DayCamera_TrackROI
#define cmd_DayCamera_Root_cmd_zoom_roi_MSGTYPE cmd_DayCamera_ZoomROI
#define cmd_DayCamera_Root_cmd_fx_roi_MSGTYPE cmd_DayCamera_FxROI
#define cmd_DayCamera_Root_cmd_set_auto_gain_MSGTYPE cmd_DayCamera_SetAutoGain

#define cmd_DayCamera_GetPos_FIELDLIST(X, a) \

#define cmd_DayCamera_GetPos_CALLBACK NULL
#define cmd_DayCamera_GetPos_DEFAULT NULL

#define cmd_DayCamera_NextFxMode_FIELDLIST(X, a) \

#define cmd_DayCamera_NextFxMode_CALLBACK NULL
#define cmd_DayCamera_NextFxMode_DEFAULT NULL

#define cmd_DayCamera_PrevFxMode_FIELDLIST(X, a) \

#define cmd_DayCamera_PrevFxMode_CALLBACK NULL
#define cmd_DayCamera_PrevFxMode_DEFAULT NULL

#define cmd_DayCamera_RefreshFxMode_FIELDLIST(X, a) \

#define cmd_DayCamera_RefreshFxMode_CALLBACK NULL
#define cmd_DayCamera_RefreshFxMode_DEFAULT NULL

#define cmd_DayCamera_HaltAll_FIELDLIST(X, a) \

#define cmd_DayCamera_HaltAll_CALLBACK NULL
#define cmd_DayCamera_HaltAll_DEFAULT NULL

#define cmd_DayCamera_SetFxMode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1)
#define cmd_DayCamera_SetFxMode_CALLBACK NULL
#define cmd_DayCamera_SetFxMode_DEFAULT NULL

#define cmd_DayCamera_SetDigitalZoomLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1)
#define cmd_DayCamera_SetDigitalZoomLevel_CALLBACK NULL
#define cmd_DayCamera_SetDigitalZoomLevel_DEFAULT NULL

#define cmd_DayCamera_Focus_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_value,cmd.set_value),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,move,cmd.move),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,halt,cmd.halt),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,offset,cmd.offset),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,reset_focus,cmd.reset_focus),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,save_to_table_focus,cmd.save_to_table_focus),   6)
#define cmd_DayCamera_Focus_CALLBACK NULL
#define cmd_DayCamera_Focus_DEFAULT NULL
#define cmd_DayCamera_Focus_cmd_set_value_MSGTYPE cmd_DayCamera_SetValue
#define cmd_DayCamera_Focus_cmd_move_MSGTYPE cmd_DayCamera_Move
#define cmd_DayCamera_Focus_cmd_halt_MSGTYPE cmd_DayCamera_Halt
#define cmd_DayCamera_Focus_cmd_offset_MSGTYPE cmd_DayCamera_Offset
#define cmd_DayCamera_Focus_cmd_reset_focus_MSGTYPE cmd_DayCamera_ResetFocus
#define cmd_DayCamera_Focus_cmd_save_to_table_focus_MSGTYPE cmd_DayCamera_SaveToTableFocus

#define cmd_DayCamera_Zoom_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_value,cmd.set_value),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,move,cmd.move),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,halt,cmd.halt),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_zoom_table_value,cmd.set_zoom_table_value),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,next_zoom_table_pos,cmd.next_zoom_table_pos),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,prev_zoom_table_pos,cmd.prev_zoom_table_pos),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,offset,cmd.offset),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,reset_zoom,cmd.reset_zoom),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,save_to_table,cmd.save_to_table),   9)
#define cmd_DayCamera_Zoom_CALLBACK NULL
#define cmd_DayCamera_Zoom_DEFAULT NULL
#define cmd_DayCamera_Zoom_cmd_set_value_MSGTYPE cmd_DayCamera_SetValue
#define cmd_DayCamera_Zoom_cmd_move_MSGTYPE cmd_DayCamera_Move
#define cmd_DayCamera_Zoom_cmd_halt_MSGTYPE cmd_DayCamera_Halt
#define cmd_DayCamera_Zoom_cmd_set_zoom_table_value_MSGTYPE cmd_DayCamera_SetZoomTableValue
#define cmd_DayCamera_Zoom_cmd_next_zoom_table_pos_MSGTYPE cmd_DayCamera_NextZoomTablePos
#define cmd_DayCamera_Zoom_cmd_prev_zoom_table_pos_MSGTYPE cmd_DayCamera_PrevZoomTablePos
#define cmd_DayCamera_Zoom_cmd_offset_MSGTYPE cmd_DayCamera_Offset
#define cmd_DayCamera_Zoom_cmd_reset_zoom_MSGTYPE cmd_DayCamera_ResetZoom
#define cmd_DayCamera_Zoom_cmd_save_to_table_MSGTYPE cmd_DayCamera_SaveToTable

#define cmd_DayCamera_NextZoomTablePos_FIELDLIST(X, a) \

#define cmd_DayCamera_NextZoomTablePos_CALLBACK NULL
#define cmd_DayCamera_NextZoomTablePos_DEFAULT NULL

#define cmd_DayCamera_PrevZoomTablePos_FIELDLIST(X, a) \

#define cmd_DayCamera_PrevZoomTablePos_CALLBACK NULL
#define cmd_DayCamera_PrevZoomTablePos_DEFAULT NULL

#define cmd_DayCamera_SetIris_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1)
#define cmd_DayCamera_SetIris_CALLBACK NULL
#define cmd_DayCamera_SetIris_DEFAULT NULL

#define cmd_DayCamera_SetInfraRedFilter_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     value,             1)
#define cmd_DayCamera_SetInfraRedFilter_CALLBACK NULL
#define cmd_DayCamera_SetInfraRedFilter_DEFAULT NULL

#define cmd_DayCamera_SetAutoIris_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     value,             1)
#define cmd_DayCamera_SetAutoIris_CALLBACK NULL
#define cmd_DayCamera_SetAutoIris_DEFAULT NULL

#define cmd_DayCamera_SetAutoGain_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     value,             1)
#define cmd_DayCamera_SetAutoGain_CALLBACK NULL
#define cmd_DayCamera_SetAutoGain_DEFAULT NULL

#define cmd_DayCamera_SetZoomTableValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1)
#define cmd_DayCamera_SetZoomTableValue_CALLBACK NULL
#define cmd_DayCamera_SetZoomTableValue_DEFAULT NULL

#define cmd_DayCamera_Stop_FIELDLIST(X, a) \

#define cmd_DayCamera_Stop_CALLBACK NULL
#define cmd_DayCamera_Stop_DEFAULT NULL

#define cmd_DayCamera_Start_FIELDLIST(X, a) \

#define cmd_DayCamera_Start_CALLBACK NULL
#define cmd_DayCamera_Start_DEFAULT NULL

#define cmd_DayCamera_Photo_FIELDLIST(X, a) \

#define cmd_DayCamera_Photo_CALLBACK NULL
#define cmd_DayCamera_Photo_DEFAULT NULL

#define cmd_DayCamera_Halt_FIELDLIST(X, a) \

#define cmd_DayCamera_Halt_CALLBACK NULL
#define cmd_DayCamera_Halt_DEFAULT NULL

#define cmd_DayCamera_GetMeteo_FIELDLIST(X, a) \

#define cmd_DayCamera_GetMeteo_CALLBACK NULL
#define cmd_DayCamera_GetMeteo_DEFAULT NULL

#define cmd_DayCamera_ResetZoom_FIELDLIST(X, a) \

#define cmd_DayCamera_ResetZoom_CALLBACK NULL
#define cmd_DayCamera_ResetZoom_DEFAULT NULL

#define cmd_DayCamera_ResetFocus_FIELDLIST(X, a) \

#define cmd_DayCamera_ResetFocus_CALLBACK NULL
#define cmd_DayCamera_ResetFocus_DEFAULT NULL

#define cmd_DayCamera_SaveToTable_FIELDLIST(X, a) \

#define cmd_DayCamera_SaveToTable_CALLBACK NULL
#define cmd_DayCamera_SaveToTable_DEFAULT NULL

#define cmd_DayCamera_SaveToTableFocus_FIELDLIST(X, a) \

#define cmd_DayCamera_SaveToTableFocus_CALLBACK NULL
#define cmd_DayCamera_SaveToTableFocus_DEFAULT NULL

#define cmd_DayCamera_FocusROI_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x1,                1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y1,                2) \
X(a, STATIC,   SINGULAR, DOUBLE,   x2,                3) \
X(a, STATIC,   SINGULAR, DOUBLE,   y2,                4) \
X(a, STATIC,   SINGULAR, UINT64,   frame_time,        5) \
X(a, STATIC,   SINGULAR, UINT64,   state_time,        6)
#define cmd_DayCamera_FocusROI_CALLBACK NULL
#define cmd_DayCamera_FocusROI_DEFAULT NULL

#define cmd_DayCamera_TrackROI_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x1,                1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y1,                2) \
X(a, STATIC,   SINGULAR, DOUBLE,   x2,                3) \
X(a, STATIC,   SINGULAR, DOUBLE,   y2,                4) \
X(a, STATIC,   SINGULAR, UINT64,   frame_time,        5) \
X(a, STATIC,   SINGULAR, UINT64,   state_time,        6)
#define cmd_DayCamera_TrackROI_CALLBACK NULL
#define cmd_DayCamera_TrackROI_DEFAULT NULL

#define cmd_DayCamera_ZoomROI_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x1,                1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y1,                2) \
X(a, STATIC,   SINGULAR, DOUBLE,   x2,                3) \
X(a, STATIC,   SINGULAR, DOUBLE,   y2,                4) \
X(a, STATIC,   SINGULAR, UINT64,   frame_time,        5) \
X(a, STATIC,   SINGULAR, UINT64,   state_time,        6)
#define cmd_DayCamera_ZoomROI_CALLBACK NULL
#define cmd_DayCamera_ZoomROI_DEFAULT NULL

#define cmd_DayCamera_FxROI_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x1,                1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y1,                2) \
X(a, STATIC,   SINGULAR, DOUBLE,   x2,                3) \
X(a, STATIC,   SINGULAR, DOUBLE,   y2,                4) \
X(a, STATIC,   SINGULAR, UINT64,   frame_time,        5) \
X(a, STATIC,   SINGULAR, UINT64,   state_time,        6)
#define cmd_DayCamera_FxROI_CALLBACK NULL
#define cmd_DayCamera_FxROI_DEFAULT NULL

extern const pb_msgdesc_t cmd_DayCamera_SetValue_msg;
extern const pb_msgdesc_t cmd_DayCamera_Move_msg;
extern const pb_msgdesc_t cmd_DayCamera_Offset_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetClaheLevel_msg;
extern const pb_msgdesc_t cmd_DayCamera_ShiftClaheLevel_msg;
extern const pb_msgdesc_t cmd_DayCamera_Root_msg;
extern const pb_msgdesc_t cmd_DayCamera_GetPos_msg;
extern const pb_msgdesc_t cmd_DayCamera_NextFxMode_msg;
extern const pb_msgdesc_t cmd_DayCamera_PrevFxMode_msg;
extern const pb_msgdesc_t cmd_DayCamera_RefreshFxMode_msg;
extern const pb_msgdesc_t cmd_DayCamera_HaltAll_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetFxMode_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetDigitalZoomLevel_msg;
extern const pb_msgdesc_t cmd_DayCamera_Focus_msg;
extern const pb_msgdesc_t cmd_DayCamera_Zoom_msg;
extern const pb_msgdesc_t cmd_DayCamera_NextZoomTablePos_msg;
extern const pb_msgdesc_t cmd_DayCamera_PrevZoomTablePos_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetIris_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetInfraRedFilter_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetAutoIris_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetAutoGain_msg;
extern const pb_msgdesc_t cmd_DayCamera_SetZoomTableValue_msg;
extern const pb_msgdesc_t cmd_DayCamera_Stop_msg;
extern const pb_msgdesc_t cmd_DayCamera_Start_msg;
extern const pb_msgdesc_t cmd_DayCamera_Photo_msg;
extern const pb_msgdesc_t cmd_DayCamera_Halt_msg;
extern const pb_msgdesc_t cmd_DayCamera_GetMeteo_msg;
extern const pb_msgdesc_t cmd_DayCamera_ResetZoom_msg;
extern const pb_msgdesc_t cmd_DayCamera_ResetFocus_msg;
extern const pb_msgdesc_t cmd_DayCamera_SaveToTable_msg;
extern const pb_msgdesc_t cmd_DayCamera_SaveToTableFocus_msg;
extern const pb_msgdesc_t cmd_DayCamera_FocusROI_msg;
extern const pb_msgdesc_t cmd_DayCamera_TrackROI_msg;
extern const pb_msgdesc_t cmd_DayCamera_ZoomROI_msg;
extern const pb_msgdesc_t cmd_DayCamera_FxROI_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_DayCamera_SetValue_fields &cmd_DayCamera_SetValue_msg
#define cmd_DayCamera_Move_fields &cmd_DayCamera_Move_msg
#define cmd_DayCamera_Offset_fields &cmd_DayCamera_Offset_msg
#define cmd_DayCamera_SetClaheLevel_fields &cmd_DayCamera_SetClaheLevel_msg
#define cmd_DayCamera_ShiftClaheLevel_fields &cmd_DayCamera_ShiftClaheLevel_msg
#define cmd_DayCamera_Root_fields &cmd_DayCamera_Root_msg
#define cmd_DayCamera_GetPos_fields &cmd_DayCamera_GetPos_msg
#define cmd_DayCamera_NextFxMode_fields &cmd_DayCamera_NextFxMode_msg
#define cmd_DayCamera_PrevFxMode_fields &cmd_DayCamera_PrevFxMode_msg
#define cmd_DayCamera_RefreshFxMode_fields &cmd_DayCamera_RefreshFxMode_msg
#define cmd_DayCamera_HaltAll_fields &cmd_DayCamera_HaltAll_msg
#define cmd_DayCamera_SetFxMode_fields &cmd_DayCamera_SetFxMode_msg
#define cmd_DayCamera_SetDigitalZoomLevel_fields &cmd_DayCamera_SetDigitalZoomLevel_msg
#define cmd_DayCamera_Focus_fields &cmd_DayCamera_Focus_msg
#define cmd_DayCamera_Zoom_fields &cmd_DayCamera_Zoom_msg
#define cmd_DayCamera_NextZoomTablePos_fields &cmd_DayCamera_NextZoomTablePos_msg
#define cmd_DayCamera_PrevZoomTablePos_fields &cmd_DayCamera_PrevZoomTablePos_msg
#define cmd_DayCamera_SetIris_fields &cmd_DayCamera_SetIris_msg
#define cmd_DayCamera_SetInfraRedFilter_fields &cmd_DayCamera_SetInfraRedFilter_msg
#define cmd_DayCamera_SetAutoIris_fields &cmd_DayCamera_SetAutoIris_msg
#define cmd_DayCamera_SetAutoGain_fields &cmd_DayCamera_SetAutoGain_msg
#define cmd_DayCamera_SetZoomTableValue_fields &cmd_DayCamera_SetZoomTableValue_msg
#define cmd_DayCamera_Stop_fields &cmd_DayCamera_Stop_msg
#define cmd_DayCamera_Start_fields &cmd_DayCamera_Start_msg
#define cmd_DayCamera_Photo_fields &cmd_DayCamera_Photo_msg
#define cmd_DayCamera_Halt_fields &cmd_DayCamera_Halt_msg
#define cmd_DayCamera_GetMeteo_fields &cmd_DayCamera_GetMeteo_msg
#define cmd_DayCamera_ResetZoom_fields &cmd_DayCamera_ResetZoom_msg
#define cmd_DayCamera_ResetFocus_fields &cmd_DayCamera_ResetFocus_msg
#define cmd_DayCamera_SaveToTable_fields &cmd_DayCamera_SaveToTable_msg
#define cmd_DayCamera_SaveToTableFocus_fields &cmd_DayCamera_SaveToTableFocus_msg
#define cmd_DayCamera_FocusROI_fields &cmd_DayCamera_FocusROI_msg
#define cmd_DayCamera_TrackROI_fields &cmd_DayCamera_TrackROI_msg
#define cmd_DayCamera_ZoomROI_fields &cmd_DayCamera_ZoomROI_msg
#define cmd_DayCamera_FxROI_fields &cmd_DayCamera_FxROI_msg

/* Maximum encoded size of messages (where known) */
#define CMD_DAYCAMERA_JON_SHARED_CMD_DAY_CAMERA_PB_H_MAX_SIZE cmd_DayCamera_Root_size
#define cmd_DayCamera_FocusROI_size              58
#define cmd_DayCamera_Focus_size                 20
#define cmd_DayCamera_FxROI_size                 58
#define cmd_DayCamera_GetMeteo_size              0
#define cmd_DayCamera_GetPos_size                0
#define cmd_DayCamera_HaltAll_size               0
#define cmd_DayCamera_Halt_size                  0
#define cmd_DayCamera_Move_size                  18
#define cmd_DayCamera_NextFxMode_size            0
#define cmd_DayCamera_NextZoomTablePos_size      0
#define cmd_DayCamera_Offset_size                9
#define cmd_DayCamera_Photo_size                 0
#define cmd_DayCamera_PrevFxMode_size            0
#define cmd_DayCamera_PrevZoomTablePos_size      0
#define cmd_DayCamera_RefreshFxMode_size         0
#define cmd_DayCamera_ResetFocus_size            0
#define cmd_DayCamera_ResetZoom_size             0
#define cmd_DayCamera_Root_size                  61
#define cmd_DayCamera_SaveToTableFocus_size      0
#define cmd_DayCamera_SaveToTable_size           0
#define cmd_DayCamera_SetAutoGain_size           2
#define cmd_DayCamera_SetAutoIris_size           2
#define cmd_DayCamera_SetClaheLevel_size         9
#define cmd_DayCamera_SetDigitalZoomLevel_size   9
#define cmd_DayCamera_SetFxMode_size             2
#define cmd_DayCamera_SetInfraRedFilter_size     2
#define cmd_DayCamera_SetIris_size               9
#define cmd_DayCamera_SetValue_size              9
#define cmd_DayCamera_SetZoomTableValue_size     11
#define cmd_DayCamera_ShiftClaheLevel_size       9
#define cmd_DayCamera_Start_size                 0
#define cmd_DayCamera_Stop_size                  0
#define cmd_DayCamera_TrackROI_size              58
#define cmd_DayCamera_ZoomROI_size               58
#define cmd_DayCamera_Zoom_size                  20

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
