/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_DAYCAMGLASSHEATER_JON_SHARED_CMD_DAY_CAM_GLASS_HEATER_PB_H_INCLUDED
#define PB_CMD_DAYCAMGLASSHEATER_JON_SHARED_CMD_DAY_CAM_GLASS_HEATER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_DayCamGlassHeater_Start {
    char dummy_field;
} cmd_DayCamGlassHeater_Start;

typedef struct _cmd_DayCamGlassHeater_Stop {
    char dummy_field;
} cmd_DayCamGlassHeater_Stop;

typedef struct _cmd_DayCamGlassHeater_TurnOn {
    char dummy_field;
} cmd_DayCamGlassHeater_TurnOn;

typedef struct _cmd_DayCamGlassHeater_TurnOff {
    char dummy_field;
} cmd_DayCamGlassHeater_TurnOff;

typedef struct _cmd_DayCamGlassHeater_GetMeteo {
    char dummy_field;
} cmd_DayCamGlassHeater_GetMeteo;

typedef struct _cmd_DayCamGlassHeater_Root {
    pb_size_t which_cmd;
    union {
        cmd_DayCamGlassHeater_Start start;
        cmd_DayCamGlassHeater_Stop stop;
        cmd_DayCamGlassHeater_TurnOn turn_on;
        cmd_DayCamGlassHeater_TurnOff turn_off;
        cmd_DayCamGlassHeater_GetMeteo get_meteo;
    } cmd;
} cmd_DayCamGlassHeater_Root;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cmd_DayCamGlassHeater_Root_init_default  {0, {cmd_DayCamGlassHeater_Start_init_default}}
#define cmd_DayCamGlassHeater_Start_init_default {0}
#define cmd_DayCamGlassHeater_Stop_init_default  {0}
#define cmd_DayCamGlassHeater_TurnOn_init_default {0}
#define cmd_DayCamGlassHeater_TurnOff_init_default {0}
#define cmd_DayCamGlassHeater_GetMeteo_init_default {0}
#define cmd_DayCamGlassHeater_Root_init_zero     {0, {cmd_DayCamGlassHeater_Start_init_zero}}
#define cmd_DayCamGlassHeater_Start_init_zero    {0}
#define cmd_DayCamGlassHeater_Stop_init_zero     {0}
#define cmd_DayCamGlassHeater_TurnOn_init_zero   {0}
#define cmd_DayCamGlassHeater_TurnOff_init_zero  {0}
#define cmd_DayCamGlassHeater_GetMeteo_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define cmd_DayCamGlassHeater_Root_start_tag     1
#define cmd_DayCamGlassHeater_Root_stop_tag      2
#define cmd_DayCamGlassHeater_Root_turn_on_tag   3
#define cmd_DayCamGlassHeater_Root_turn_off_tag  4
#define cmd_DayCamGlassHeater_Root_get_meteo_tag 5

/* Struct field encoding specification for nanopb */
#define cmd_DayCamGlassHeater_Root_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,start,cmd.start),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,stop,cmd.stop),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,turn_on,cmd.turn_on),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,turn_off,cmd.turn_off),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,get_meteo,cmd.get_meteo),   5)
#define cmd_DayCamGlassHeater_Root_CALLBACK NULL
#define cmd_DayCamGlassHeater_Root_DEFAULT NULL
#define cmd_DayCamGlassHeater_Root_cmd_start_MSGTYPE cmd_DayCamGlassHeater_Start
#define cmd_DayCamGlassHeater_Root_cmd_stop_MSGTYPE cmd_DayCamGlassHeater_Stop
#define cmd_DayCamGlassHeater_Root_cmd_turn_on_MSGTYPE cmd_DayCamGlassHeater_TurnOn
#define cmd_DayCamGlassHeater_Root_cmd_turn_off_MSGTYPE cmd_DayCamGlassHeater_TurnOff
#define cmd_DayCamGlassHeater_Root_cmd_get_meteo_MSGTYPE cmd_DayCamGlassHeater_GetMeteo

#define cmd_DayCamGlassHeater_Start_FIELDLIST(X, a) \

#define cmd_DayCamGlassHeater_Start_CALLBACK NULL
#define cmd_DayCamGlassHeater_Start_DEFAULT NULL

#define cmd_DayCamGlassHeater_Stop_FIELDLIST(X, a) \

#define cmd_DayCamGlassHeater_Stop_CALLBACK NULL
#define cmd_DayCamGlassHeater_Stop_DEFAULT NULL

#define cmd_DayCamGlassHeater_TurnOn_FIELDLIST(X, a) \

#define cmd_DayCamGlassHeater_TurnOn_CALLBACK NULL
#define cmd_DayCamGlassHeater_TurnOn_DEFAULT NULL

#define cmd_DayCamGlassHeater_TurnOff_FIELDLIST(X, a) \

#define cmd_DayCamGlassHeater_TurnOff_CALLBACK NULL
#define cmd_DayCamGlassHeater_TurnOff_DEFAULT NULL

#define cmd_DayCamGlassHeater_GetMeteo_FIELDLIST(X, a) \

#define cmd_DayCamGlassHeater_GetMeteo_CALLBACK NULL
#define cmd_DayCamGlassHeater_GetMeteo_DEFAULT NULL

extern const pb_msgdesc_t cmd_DayCamGlassHeater_Root_msg;
extern const pb_msgdesc_t cmd_DayCamGlassHeater_Start_msg;
extern const pb_msgdesc_t cmd_DayCamGlassHeater_Stop_msg;
extern const pb_msgdesc_t cmd_DayCamGlassHeater_TurnOn_msg;
extern const pb_msgdesc_t cmd_DayCamGlassHeater_TurnOff_msg;
extern const pb_msgdesc_t cmd_DayCamGlassHeater_GetMeteo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_DayCamGlassHeater_Root_fields &cmd_DayCamGlassHeater_Root_msg
#define cmd_DayCamGlassHeater_Start_fields &cmd_DayCamGlassHeater_Start_msg
#define cmd_DayCamGlassHeater_Stop_fields &cmd_DayCamGlassHeater_Stop_msg
#define cmd_DayCamGlassHeater_TurnOn_fields &cmd_DayCamGlassHeater_TurnOn_msg
#define cmd_DayCamGlassHeater_TurnOff_fields &cmd_DayCamGlassHeater_TurnOff_msg
#define cmd_DayCamGlassHeater_GetMeteo_fields &cmd_DayCamGlassHeater_GetMeteo_msg

/* Maximum encoded size of messages (where known) */
#define CMD_DAYCAMGLASSHEATER_JON_SHARED_CMD_DAY_CAM_GLASS_HEATER_PB_H_MAX_SIZE cmd_DayCamGlassHeater_Root_size
#define cmd_DayCamGlassHeater_GetMeteo_size      0
#define cmd_DayCamGlassHeater_Root_size          2
#define cmd_DayCamGlassHeater_Start_size         0
#define cmd_DayCamGlassHeater_Stop_size          0
#define cmd_DayCamGlassHeater_TurnOff_size       0
#define cmd_DayCamGlassHeater_TurnOn_size        0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
