/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_JON_LOGS_JON_CLIENT_LOGS_PB_H_INCLUDED
#define PB_JON_LOGS_JON_CLIENT_LOGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Client log entry - represents a single log message from the frontend */
typedef struct _jon_logs_ClientLogEntry {
    /* Core log data (validated on ingress) */
    pb_callback_t lvl;
    pb_callback_t mod;
    pb_callback_t msg;
    int64_t ts;
    /* Source location */
    pb_callback_t file;
    int32_t line;
    /* Session/client info */
    pb_callback_t sid;
    pb_callback_t ua; /* user agent */
    pb_callback_t url; /* page path + query (optional - workers don't have location) */
    pb_callback_t origin; /* page origin (optional - workers don't have location) */
    pb_callback_t commit; /* git commit hash (build-time) */
    pb_callback_t build; /* build timestamp */
    /* Device info */
    int32_t sw;
    int32_t sh;
    double dpr; /* device pixel ratio */
    pb_callback_t lang; /* browser language */
    pb_callback_t tz; /* timezone */
    pb_callback_t extra; /* optional JSON blob */
    /* Raw state snapshot bytes - NOT validated, stored as-is, decode later */
    pb_callback_t state_snapshot;
} jon_logs_ClientLogEntry;

/* Batch of client log entries - sent over WebSocket */
typedef struct _jon_logs_ClientLogBatch {
    /* Protocol version for future compatibility */
    uint32_t version; /* Currently only v1 */
    pb_callback_t entries;
} jon_logs_ClientLogBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define jon_logs_ClientLogEntry_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define jon_logs_ClientLogBatch_init_default     {0, {{NULL}, NULL}}
#define jon_logs_ClientLogEntry_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define jon_logs_ClientLogBatch_init_zero        {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define jon_logs_ClientLogEntry_lvl_tag          1
#define jon_logs_ClientLogEntry_mod_tag          2
#define jon_logs_ClientLogEntry_msg_tag          3
#define jon_logs_ClientLogEntry_ts_tag           4
#define jon_logs_ClientLogEntry_file_tag         5
#define jon_logs_ClientLogEntry_line_tag         6
#define jon_logs_ClientLogEntry_sid_tag          7
#define jon_logs_ClientLogEntry_ua_tag           8
#define jon_logs_ClientLogEntry_url_tag          9
#define jon_logs_ClientLogEntry_origin_tag       10
#define jon_logs_ClientLogEntry_commit_tag       11
#define jon_logs_ClientLogEntry_build_tag        12
#define jon_logs_ClientLogEntry_sw_tag           13
#define jon_logs_ClientLogEntry_sh_tag           14
#define jon_logs_ClientLogEntry_dpr_tag          15
#define jon_logs_ClientLogEntry_lang_tag         16
#define jon_logs_ClientLogEntry_tz_tag           17
#define jon_logs_ClientLogEntry_extra_tag        18
#define jon_logs_ClientLogEntry_state_snapshot_tag 19
#define jon_logs_ClientLogBatch_version_tag      1
#define jon_logs_ClientLogBatch_entries_tag      2

/* Struct field encoding specification for nanopb */
#define jon_logs_ClientLogEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   lvl,               1) \
X(a, CALLBACK, SINGULAR, STRING,   mod,               2) \
X(a, CALLBACK, SINGULAR, STRING,   msg,               3) \
X(a, STATIC,   SINGULAR, INT64,    ts,                4) \
X(a, CALLBACK, SINGULAR, STRING,   file,              5) \
X(a, STATIC,   SINGULAR, INT32,    line,              6) \
X(a, CALLBACK, SINGULAR, STRING,   sid,               7) \
X(a, CALLBACK, SINGULAR, STRING,   ua,                8) \
X(a, CALLBACK, OPTIONAL, STRING,   url,               9) \
X(a, CALLBACK, OPTIONAL, STRING,   origin,           10) \
X(a, CALLBACK, SINGULAR, STRING,   commit,           11) \
X(a, CALLBACK, SINGULAR, STRING,   build,            12) \
X(a, STATIC,   SINGULAR, INT32,    sw,               13) \
X(a, STATIC,   SINGULAR, INT32,    sh,               14) \
X(a, STATIC,   SINGULAR, DOUBLE,   dpr,              15) \
X(a, CALLBACK, SINGULAR, STRING,   lang,             16) \
X(a, CALLBACK, SINGULAR, STRING,   tz,               17) \
X(a, CALLBACK, SINGULAR, STRING,   extra,            18) \
X(a, CALLBACK, OPTIONAL, BYTES,    state_snapshot,   19)
#define jon_logs_ClientLogEntry_CALLBACK pb_default_field_callback
#define jon_logs_ClientLogEntry_DEFAULT NULL

#define jon_logs_ClientLogBatch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           2)
#define jon_logs_ClientLogBatch_CALLBACK pb_default_field_callback
#define jon_logs_ClientLogBatch_DEFAULT NULL
#define jon_logs_ClientLogBatch_entries_MSGTYPE jon_logs_ClientLogEntry

extern const pb_msgdesc_t jon_logs_ClientLogEntry_msg;
extern const pb_msgdesc_t jon_logs_ClientLogBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jon_logs_ClientLogEntry_fields &jon_logs_ClientLogEntry_msg
#define jon_logs_ClientLogBatch_fields &jon_logs_ClientLogBatch_msg

/* Maximum encoded size of messages (where known) */
/* jon_logs_ClientLogEntry_size depends on runtime parameters */
/* jon_logs_ClientLogBatch_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
