/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_TYPES_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_TYPES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ser_JonGuiDataVideoChannelHeatFilters {
    ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_UNSPECIFIED = 0,
    ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_HOT_WHITE = 1,
    ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_HOT_BLACK = 2,
    ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_SEPIA = 3,
    ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_SEPIA_INVERSE = 4
} ser_JonGuiDataVideoChannelHeatFilters;

typedef enum _ser_JonGuiDataVideoChannelHeatAGCModes {
    ser_JonGuiDataVideoChannelHeatAGCModes_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_AGC_MODE_UNSPECIFIED = 0,
    ser_JonGuiDataVideoChannelHeatAGCModes_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_AGC_MODE_1 = 1,
    ser_JonGuiDataVideoChannelHeatAGCModes_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_AGC_MODE_2 = 2,
    ser_JonGuiDataVideoChannelHeatAGCModes_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_AGC_MODE_3 = 3
} ser_JonGuiDataVideoChannelHeatAGCModes;

typedef enum _ser_JonGuiDataGpsUnits {
    ser_JonGuiDataGpsUnits_JON_GUI_DATA_GPS_UNITS_UNSPECIFIED = 0,
    ser_JonGuiDataGpsUnits_JON_GUI_DATA_GPS_UNITS_DECIMAL_DEGREES = 1,
    ser_JonGuiDataGpsUnits_JON_GUI_DATA_GPS_UNITS_DEGREES_MINUTES_SECONDS = 2,
    ser_JonGuiDataGpsUnits_JON_GUI_DATA_GPS_UNITS_DEGREES_DECIMAL_MINUTES = 3
} ser_JonGuiDataGpsUnits;

typedef enum _ser_JonGuiDataGpsFixType {
    ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_UNSPECIFIED = 0,
    ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_NONE = 1,
    ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_1D = 2,
    ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_2D = 3,
    ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_3D = 4,
    ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_MANUAL = 5
} ser_JonGuiDataGpsFixType;

typedef enum _ser_JonGuiDataCompassUnits {
    ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_UNSPECIFIED = 0,
    ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_DEGREES = 1,
    ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_MILS = 2,
    ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_GRAD = 3,
    ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_MRAD = 4
} ser_JonGuiDataCompassUnits;

typedef enum _ser_JonGuiDataAccumulatorStateIdx {
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_UNSPECIFIED = 0,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_UNKNOWN = 1,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_EMPTY = 2,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_1 = 3,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_2 = 4,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_3 = 5,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_4 = 6,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_5 = 7,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_6 = 8,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_FULL = 9,
    ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_CHARGING = 10
} ser_JonGuiDataAccumulatorStateIdx;

typedef enum _ser_JonGuiDataTimeFormats {
    ser_JonGuiDataTimeFormats_JON_GUI_DATA_TIME_FORMAT_UNSPECIFIED = 0,
    ser_JonGuiDataTimeFormats_JON_GUI_DATA_TIME_FORMAT_H_M_S = 1,
    ser_JonGuiDataTimeFormats_JON_GUI_DATA_TIME_FORMAT_Y_m_D_H_M_S = 2
} ser_JonGuiDataTimeFormats;

typedef enum _ser_JonGuiDataRotaryDirection {
    ser_JonGuiDataRotaryDirection_JON_GUI_DATA_ROTARY_DIRECTION_UNSPECIFIED = 0,
    ser_JonGuiDataRotaryDirection_JON_GUI_DATA_ROTARY_DIRECTION_CLOCKWISE = 1,
    ser_JonGuiDataRotaryDirection_JON_GUI_DATA_ROTARY_DIRECTION_COUNTER_CLOCKWISE = 2
} ser_JonGuiDataRotaryDirection;

typedef enum _ser_JonGuiDataLrfScanModes {
    ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_UNSPECIFIED = 0,
    ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_1_HZ_CONTINUOUS = 1,
    ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_4_HZ_CONTINUOUS = 2,
    ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_10_HZ_CONTINUOUS = 3,
    ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_20_HZ_CONTINUOUS = 4,
    ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_100_HZ_CONTINUOUS = 5,
    ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_200_HZ_CONTINUOUS = 6
} ser_JonGuiDataLrfScanModes;

typedef enum _ser_JonGuiDatatLrfLaserPointerModes {
    ser_JonGuiDatatLrfLaserPointerModes_JON_GUI_DATA_LRF_LASER_POINTER_MODE_UNSPECIFIED = 0,
    ser_JonGuiDatatLrfLaserPointerModes_JON_GUI_DATA_LRF_LASER_POINTER_MODE_OFF = 1,
    ser_JonGuiDatatLrfLaserPointerModes_JON_GUI_DATA_LRF_LASER_POINTER_MODE_ON_1 = 2,
    ser_JonGuiDatatLrfLaserPointerModes_JON_GUI_DATA_LRF_LASER_POINTER_MODE_ON_2 = 3
} ser_JonGuiDatatLrfLaserPointerModes;

typedef enum _ser_JonGuiDataCompassCalibrateStatus {
    ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_UNSPECIFIED = 0,
    ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_NOT_CALIBRATING = 1,
    ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_CALIBRATING_SHORT = 2,
    ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_CALIBRATING_LONG = 3,
    ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_FINISHED = 4,
    ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_ERROR = 5
} ser_JonGuiDataCompassCalibrateStatus;

typedef enum _ser_JonGuiDataRotaryMode {
    ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_UNSPECIFIED = 0,
    ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_INITIALIZATION = 1,
    ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_SPEED = 2,
    ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_POSITION = 3,
    ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_STABILIZATION = 4,
    ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_TARGETING = 5,
    ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_VIDEO_TRACKER = 6
} ser_JonGuiDataRotaryMode;

typedef enum _ser_JonGuiDataVideoChannel {
    ser_JonGuiDataVideoChannel_JON_GUI_DATA_VIDEO_CHANNEL_UNSPECIFIED = 0,
    ser_JonGuiDataVideoChannel_JON_GUI_DATA_VIDEO_CHANNEL_HEAT = 1,
    ser_JonGuiDataVideoChannel_JON_GUI_DATA_VIDEO_CHANNEL_DAY = 2
} ser_JonGuiDataVideoChannel;

typedef enum _ser_JonGuiDataRecOsdScreen {
    ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_UNSPECIFIED = 0,
    ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_MAIN = 1,
    ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_LRF_MEASURE = 2,
    ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_LRF_RESULT = 3,
    ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_LRF_RESULT_SIMPLIFIED = 4
} ser_JonGuiDataRecOsdScreen;

typedef enum _ser_JonGuiDataFxModeDay {
    ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_DEFAULT = 0,
    ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_A = 1,
    ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_B = 2,
    ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_C = 3,
    ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_D = 4,
    ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_E = 5,
    ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_F = 6
} ser_JonGuiDataFxModeDay;

typedef enum _ser_JonGuiDataFxModeHeat {
    ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_DEFAULT = 0,
    ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_A = 1,
    ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_B = 2,
    ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_C = 3,
    ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_D = 4,
    ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_E = 5,
    ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_F = 6
} ser_JonGuiDataFxModeHeat;

typedef enum _ser_JonGuiDataSystemLocalizations {
    ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_UNSPECIFIED = 0,
    ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_EN = 1,
    ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_UA = 2,
    ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_AR = 3,
    ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_CS = 4
} ser_JonGuiDataSystemLocalizations;

typedef enum _ser_JonGuiDataClientType {
    ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_UNSPECIFIED = 0,
    ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_INTERNAL_CV = 1,
    ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_LOCAL_NETWORK = 2,
    ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_CERTIFICATE_PROTECTED = 3,
    ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_LIRA = 4
} ser_JonGuiDataClientType;

typedef enum _ser_JonGuiDataClientApp {
    ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_UNSPECIFIED = 0,
    ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_BROWSER_UI = 1,
    ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_BROWSER_MAP = 2,
    ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_DESKTOP_NATIVE = 3,
    ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_MOBILE_NATIVE = 4
} ser_JonGuiDataClientApp;

typedef enum _ser_JonGuiDataExtBatStatus {
    ser_JonGuiDataExtBatStatus_JON_GUI_DATA_EXT_BAT_STATUS_UNSPECIFIED = 0,
    ser_JonGuiDataExtBatStatus_JON_GUI_DATA_EXT_BAT_STATUS_CHARGING = 1,
    ser_JonGuiDataExtBatStatus_JON_GUI_DATA_EXT_BAT_STATUS_DISCHARGING = 2,
    ser_JonGuiDataExtBatStatus_JON_GUI_DATA_EXT_BAT_STATUS_BALANCING = 3
} ser_JonGuiDataExtBatStatus;

typedef enum _ser_JonGuiDataStateSource {
    ser_JonGuiDataStateSource_JON_GUI_DATA_STATE_SOURCE_UNSPECIFIED = 0,
    ser_JonGuiDataStateSource_JON_GUI_DATA_STATE_SOURCE_DAY_PIPELINE = 1,
    ser_JonGuiDataStateSource_JON_GUI_DATA_STATE_SOURCE_HEAT_PIPELINE = 2,
    ser_JonGuiDataStateSource_JON_GUI_DATA_STATE_SOURCE_SYSTEM = 3
} ser_JonGuiDataStateSource;

/* Struct definitions */
typedef struct _ser_JonGuiDataMeteo {
    double temperature;
    double humidity;
    double pressure;
} ser_JonGuiDataMeteo;

/* Structured version for opaque payloads.
 Enables simple numeric comparison without string parsing. */
typedef struct _ser_JonOpaquePayloadVersion {
    uint32_t major;
    uint32_t minor;
    uint64_t build; /* Can be timestamp (ms since epoch) or build number */
} ser_JonOpaquePayloadVersion;

/* Opaque extension payload for subsystem-specific data.
 Transport layer passes through without interpretation.
 Handlers match on type_uuid and check version compatibility. */
typedef struct _ser_JonOpaquePayload {
    /* UUIDv7 identifying the payload type (e.g., "019415a9-5c34-7def-8000-000000000001") */
    pb_callback_t type_uuid;
    /* Structured version - handler decides compatibility logic */
    bool has_version;
    ser_JonOpaquePayloadVersion version;
    /* Opaque binary payload */
    pb_callback_t payload;
} ser_JonOpaquePayload;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ser_JonGuiDataVideoChannelHeatFilters_MIN ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_UNSPECIFIED
#define _ser_JonGuiDataVideoChannelHeatFilters_MAX ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_SEPIA_INVERSE
#define _ser_JonGuiDataVideoChannelHeatFilters_ARRAYSIZE ((ser_JonGuiDataVideoChannelHeatFilters)(ser_JonGuiDataVideoChannelHeatFilters_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_FILTER_SEPIA_INVERSE+1))

#define _ser_JonGuiDataVideoChannelHeatAGCModes_MIN ser_JonGuiDataVideoChannelHeatAGCModes_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_AGC_MODE_UNSPECIFIED
#define _ser_JonGuiDataVideoChannelHeatAGCModes_MAX ser_JonGuiDataVideoChannelHeatAGCModes_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_AGC_MODE_3
#define _ser_JonGuiDataVideoChannelHeatAGCModes_ARRAYSIZE ((ser_JonGuiDataVideoChannelHeatAGCModes)(ser_JonGuiDataVideoChannelHeatAGCModes_JON_GUI_DATA_VIDEO_CHANNEL_HEAT_AGC_MODE_3+1))

#define _ser_JonGuiDataGpsUnits_MIN ser_JonGuiDataGpsUnits_JON_GUI_DATA_GPS_UNITS_UNSPECIFIED
#define _ser_JonGuiDataGpsUnits_MAX ser_JonGuiDataGpsUnits_JON_GUI_DATA_GPS_UNITS_DEGREES_DECIMAL_MINUTES
#define _ser_JonGuiDataGpsUnits_ARRAYSIZE ((ser_JonGuiDataGpsUnits)(ser_JonGuiDataGpsUnits_JON_GUI_DATA_GPS_UNITS_DEGREES_DECIMAL_MINUTES+1))

#define _ser_JonGuiDataGpsFixType_MIN ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_UNSPECIFIED
#define _ser_JonGuiDataGpsFixType_MAX ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_MANUAL
#define _ser_JonGuiDataGpsFixType_ARRAYSIZE ((ser_JonGuiDataGpsFixType)(ser_JonGuiDataGpsFixType_JON_GUI_DATA_GPS_FIX_TYPE_MANUAL+1))

#define _ser_JonGuiDataCompassUnits_MIN ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_UNSPECIFIED
#define _ser_JonGuiDataCompassUnits_MAX ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_MRAD
#define _ser_JonGuiDataCompassUnits_ARRAYSIZE ((ser_JonGuiDataCompassUnits)(ser_JonGuiDataCompassUnits_JON_GUI_DATA_COMPASS_UNITS_MRAD+1))

#define _ser_JonGuiDataAccumulatorStateIdx_MIN ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_UNSPECIFIED
#define _ser_JonGuiDataAccumulatorStateIdx_MAX ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_CHARGING
#define _ser_JonGuiDataAccumulatorStateIdx_ARRAYSIZE ((ser_JonGuiDataAccumulatorStateIdx)(ser_JonGuiDataAccumulatorStateIdx_JON_GUI_DATA_ACCUMULATOR_STATE_CHARGING+1))

#define _ser_JonGuiDataTimeFormats_MIN ser_JonGuiDataTimeFormats_JON_GUI_DATA_TIME_FORMAT_UNSPECIFIED
#define _ser_JonGuiDataTimeFormats_MAX ser_JonGuiDataTimeFormats_JON_GUI_DATA_TIME_FORMAT_Y_m_D_H_M_S
#define _ser_JonGuiDataTimeFormats_ARRAYSIZE ((ser_JonGuiDataTimeFormats)(ser_JonGuiDataTimeFormats_JON_GUI_DATA_TIME_FORMAT_Y_m_D_H_M_S+1))

#define _ser_JonGuiDataRotaryDirection_MIN ser_JonGuiDataRotaryDirection_JON_GUI_DATA_ROTARY_DIRECTION_UNSPECIFIED
#define _ser_JonGuiDataRotaryDirection_MAX ser_JonGuiDataRotaryDirection_JON_GUI_DATA_ROTARY_DIRECTION_COUNTER_CLOCKWISE
#define _ser_JonGuiDataRotaryDirection_ARRAYSIZE ((ser_JonGuiDataRotaryDirection)(ser_JonGuiDataRotaryDirection_JON_GUI_DATA_ROTARY_DIRECTION_COUNTER_CLOCKWISE+1))

#define _ser_JonGuiDataLrfScanModes_MIN ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_UNSPECIFIED
#define _ser_JonGuiDataLrfScanModes_MAX ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_200_HZ_CONTINUOUS
#define _ser_JonGuiDataLrfScanModes_ARRAYSIZE ((ser_JonGuiDataLrfScanModes)(ser_JonGuiDataLrfScanModes_JON_GUI_DATA_LRF_SCAN_MODE_200_HZ_CONTINUOUS+1))

#define _ser_JonGuiDatatLrfLaserPointerModes_MIN ser_JonGuiDatatLrfLaserPointerModes_JON_GUI_DATA_LRF_LASER_POINTER_MODE_UNSPECIFIED
#define _ser_JonGuiDatatLrfLaserPointerModes_MAX ser_JonGuiDatatLrfLaserPointerModes_JON_GUI_DATA_LRF_LASER_POINTER_MODE_ON_2
#define _ser_JonGuiDatatLrfLaserPointerModes_ARRAYSIZE ((ser_JonGuiDatatLrfLaserPointerModes)(ser_JonGuiDatatLrfLaserPointerModes_JON_GUI_DATA_LRF_LASER_POINTER_MODE_ON_2+1))

#define _ser_JonGuiDataCompassCalibrateStatus_MIN ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_UNSPECIFIED
#define _ser_JonGuiDataCompassCalibrateStatus_MAX ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_ERROR
#define _ser_JonGuiDataCompassCalibrateStatus_ARRAYSIZE ((ser_JonGuiDataCompassCalibrateStatus)(ser_JonGuiDataCompassCalibrateStatus_JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_ERROR+1))

#define _ser_JonGuiDataRotaryMode_MIN ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_UNSPECIFIED
#define _ser_JonGuiDataRotaryMode_MAX ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_VIDEO_TRACKER
#define _ser_JonGuiDataRotaryMode_ARRAYSIZE ((ser_JonGuiDataRotaryMode)(ser_JonGuiDataRotaryMode_JON_GUI_DATA_ROTARY_MODE_VIDEO_TRACKER+1))

#define _ser_JonGuiDataVideoChannel_MIN ser_JonGuiDataVideoChannel_JON_GUI_DATA_VIDEO_CHANNEL_UNSPECIFIED
#define _ser_JonGuiDataVideoChannel_MAX ser_JonGuiDataVideoChannel_JON_GUI_DATA_VIDEO_CHANNEL_DAY
#define _ser_JonGuiDataVideoChannel_ARRAYSIZE ((ser_JonGuiDataVideoChannel)(ser_JonGuiDataVideoChannel_JON_GUI_DATA_VIDEO_CHANNEL_DAY+1))

#define _ser_JonGuiDataRecOsdScreen_MIN ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_UNSPECIFIED
#define _ser_JonGuiDataRecOsdScreen_MAX ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_LRF_RESULT_SIMPLIFIED
#define _ser_JonGuiDataRecOsdScreen_ARRAYSIZE ((ser_JonGuiDataRecOsdScreen)(ser_JonGuiDataRecOsdScreen_JON_GUI_DATA_REC_OSD_SCREEN_LRF_RESULT_SIMPLIFIED+1))

#define _ser_JonGuiDataFxModeDay_MIN ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_DEFAULT
#define _ser_JonGuiDataFxModeDay_MAX ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_F
#define _ser_JonGuiDataFxModeDay_ARRAYSIZE ((ser_JonGuiDataFxModeDay)(ser_JonGuiDataFxModeDay_JON_GUI_DATA_FX_MODE_DAY_F+1))

#define _ser_JonGuiDataFxModeHeat_MIN ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_DEFAULT
#define _ser_JonGuiDataFxModeHeat_MAX ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_F
#define _ser_JonGuiDataFxModeHeat_ARRAYSIZE ((ser_JonGuiDataFxModeHeat)(ser_JonGuiDataFxModeHeat_JON_GUI_DATA_FX_MODE_HEAT_F+1))

#define _ser_JonGuiDataSystemLocalizations_MIN ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_UNSPECIFIED
#define _ser_JonGuiDataSystemLocalizations_MAX ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_CS
#define _ser_JonGuiDataSystemLocalizations_ARRAYSIZE ((ser_JonGuiDataSystemLocalizations)(ser_JonGuiDataSystemLocalizations_JON_GUI_DATA_SYSTEM_LOCALIZATION_CS+1))

#define _ser_JonGuiDataClientType_MIN ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_UNSPECIFIED
#define _ser_JonGuiDataClientType_MAX ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_LIRA
#define _ser_JonGuiDataClientType_ARRAYSIZE ((ser_JonGuiDataClientType)(ser_JonGuiDataClientType_JON_GUI_DATA_CLIENT_TYPE_LIRA+1))

#define _ser_JonGuiDataClientApp_MIN ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_UNSPECIFIED
#define _ser_JonGuiDataClientApp_MAX ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_MOBILE_NATIVE
#define _ser_JonGuiDataClientApp_ARRAYSIZE ((ser_JonGuiDataClientApp)(ser_JonGuiDataClientApp_JON_GUI_DATA_CLIENT_APP_MOBILE_NATIVE+1))

#define _ser_JonGuiDataExtBatStatus_MIN ser_JonGuiDataExtBatStatus_JON_GUI_DATA_EXT_BAT_STATUS_UNSPECIFIED
#define _ser_JonGuiDataExtBatStatus_MAX ser_JonGuiDataExtBatStatus_JON_GUI_DATA_EXT_BAT_STATUS_BALANCING
#define _ser_JonGuiDataExtBatStatus_ARRAYSIZE ((ser_JonGuiDataExtBatStatus)(ser_JonGuiDataExtBatStatus_JON_GUI_DATA_EXT_BAT_STATUS_BALANCING+1))

#define _ser_JonGuiDataStateSource_MIN ser_JonGuiDataStateSource_JON_GUI_DATA_STATE_SOURCE_UNSPECIFIED
#define _ser_JonGuiDataStateSource_MAX ser_JonGuiDataStateSource_JON_GUI_DATA_STATE_SOURCE_SYSTEM
#define _ser_JonGuiDataStateSource_ARRAYSIZE ((ser_JonGuiDataStateSource)(ser_JonGuiDataStateSource_JON_GUI_DATA_STATE_SOURCE_SYSTEM+1))





/* Initializer values for message structs */
#define ser_JonGuiDataMeteo_init_default         {0, 0, 0}
#define ser_JonOpaquePayloadVersion_init_default {0, 0, 0}
#define ser_JonOpaquePayload_init_default        {{{NULL}, NULL}, false, ser_JonOpaquePayloadVersion_init_default, {{NULL}, NULL}}
#define ser_JonGuiDataMeteo_init_zero            {0, 0, 0}
#define ser_JonOpaquePayloadVersion_init_zero    {0, 0, 0}
#define ser_JonOpaquePayload_init_zero           {{{NULL}, NULL}, false, ser_JonOpaquePayloadVersion_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataMeteo_temperature_tag      1
#define ser_JonGuiDataMeteo_humidity_tag         2
#define ser_JonGuiDataMeteo_pressure_tag         3
#define ser_JonOpaquePayloadVersion_major_tag    1
#define ser_JonOpaquePayloadVersion_minor_tag    2
#define ser_JonOpaquePayloadVersion_build_tag    3
#define ser_JonOpaquePayload_type_uuid_tag       1
#define ser_JonOpaquePayload_version_tag         2
#define ser_JonOpaquePayload_payload_tag         3

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataMeteo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   temperature,       1) \
X(a, STATIC,   SINGULAR, DOUBLE,   humidity,          2) \
X(a, STATIC,   SINGULAR, DOUBLE,   pressure,          3)
#define ser_JonGuiDataMeteo_CALLBACK NULL
#define ser_JonGuiDataMeteo_DEFAULT NULL

#define ser_JonOpaquePayloadVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2) \
X(a, STATIC,   SINGULAR, UINT64,   build,             3)
#define ser_JonOpaquePayloadVersion_CALLBACK NULL
#define ser_JonOpaquePayloadVersion_DEFAULT NULL

#define ser_JonOpaquePayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   type_uuid,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           2) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           3)
#define ser_JonOpaquePayload_CALLBACK pb_default_field_callback
#define ser_JonOpaquePayload_DEFAULT NULL
#define ser_JonOpaquePayload_version_MSGTYPE ser_JonOpaquePayloadVersion

extern const pb_msgdesc_t ser_JonGuiDataMeteo_msg;
extern const pb_msgdesc_t ser_JonOpaquePayloadVersion_msg;
extern const pb_msgdesc_t ser_JonOpaquePayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataMeteo_fields &ser_JonGuiDataMeteo_msg
#define ser_JonOpaquePayloadVersion_fields &ser_JonOpaquePayloadVersion_msg
#define ser_JonOpaquePayload_fields &ser_JonOpaquePayload_msg

/* Maximum encoded size of messages (where known) */
/* ser_JonOpaquePayload_size depends on runtime parameters */
#define SER_JON_SHARED_DATA_TYPES_PB_H_MAX_SIZE  ser_JonGuiDataMeteo_size
#define ser_JonGuiDataMeteo_size                 27
#define ser_JonOpaquePayloadVersion_size         23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
