/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_OSD_JON_SHARED_CMD_OSD_PB_H_INCLUDED
#define PB_CMD_OSD_JON_SHARED_CMD_OSD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_OSD_ShowDefaultScreen {
    char dummy_field;
} cmd_OSD_ShowDefaultScreen;

typedef struct _cmd_OSD_ShowLRFMeasureScreen {
    char dummy_field;
} cmd_OSD_ShowLRFMeasureScreen;

typedef struct _cmd_OSD_ShowLRFResultScreen {
    char dummy_field;
} cmd_OSD_ShowLRFResultScreen;

typedef struct _cmd_OSD_ShowLRFResultSimplifiedScreen {
    char dummy_field;
} cmd_OSD_ShowLRFResultSimplifiedScreen;

typedef struct _cmd_OSD_EnableHeatOSD {
    char dummy_field;
} cmd_OSD_EnableHeatOSD;

typedef struct _cmd_OSD_DisableHeatOSD {
    char dummy_field;
} cmd_OSD_DisableHeatOSD;

typedef struct _cmd_OSD_EnableDayOSD {
    char dummy_field;
} cmd_OSD_EnableDayOSD;

typedef struct _cmd_OSD_DisableDayOSD {
    char dummy_field;
} cmd_OSD_DisableDayOSD;

typedef struct _cmd_OSD_Root {
    pb_size_t which_cmd;
    union {
        cmd_OSD_ShowDefaultScreen show_default_screen;
        cmd_OSD_ShowLRFMeasureScreen show_lrf_measure_screen;
        cmd_OSD_ShowLRFResultScreen show_lrf_result_screen;
        cmd_OSD_ShowLRFResultSimplifiedScreen show_lrf_result_simplified_screen;
        cmd_OSD_EnableHeatOSD enable_heat_osd;
        cmd_OSD_DisableHeatOSD disable_heat_osd;
        cmd_OSD_EnableDayOSD enable_day_osd;
        cmd_OSD_DisableDayOSD disable_day_osd;
    } cmd;
} cmd_OSD_Root;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cmd_OSD_Root_init_default                {0, {cmd_OSD_ShowDefaultScreen_init_default}}
#define cmd_OSD_ShowDefaultScreen_init_default   {0}
#define cmd_OSD_ShowLRFMeasureScreen_init_default {0}
#define cmd_OSD_ShowLRFResultScreen_init_default {0}
#define cmd_OSD_ShowLRFResultSimplifiedScreen_init_default {0}
#define cmd_OSD_EnableHeatOSD_init_default       {0}
#define cmd_OSD_DisableHeatOSD_init_default      {0}
#define cmd_OSD_EnableDayOSD_init_default        {0}
#define cmd_OSD_DisableDayOSD_init_default       {0}
#define cmd_OSD_Root_init_zero                   {0, {cmd_OSD_ShowDefaultScreen_init_zero}}
#define cmd_OSD_ShowDefaultScreen_init_zero      {0}
#define cmd_OSD_ShowLRFMeasureScreen_init_zero   {0}
#define cmd_OSD_ShowLRFResultScreen_init_zero    {0}
#define cmd_OSD_ShowLRFResultSimplifiedScreen_init_zero {0}
#define cmd_OSD_EnableHeatOSD_init_zero          {0}
#define cmd_OSD_DisableHeatOSD_init_zero         {0}
#define cmd_OSD_EnableDayOSD_init_zero           {0}
#define cmd_OSD_DisableDayOSD_init_zero          {0}

/* Field tags (for use in manual encoding/decoding) */
#define cmd_OSD_Root_show_default_screen_tag     1
#define cmd_OSD_Root_show_lrf_measure_screen_tag 2
#define cmd_OSD_Root_show_lrf_result_screen_tag  3
#define cmd_OSD_Root_show_lrf_result_simplified_screen_tag 4
#define cmd_OSD_Root_enable_heat_osd_tag         5
#define cmd_OSD_Root_disable_heat_osd_tag        6
#define cmd_OSD_Root_enable_day_osd_tag          7
#define cmd_OSD_Root_disable_day_osd_tag         8

/* Struct field encoding specification for nanopb */
#define cmd_OSD_Root_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,show_default_screen,cmd.show_default_screen),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,show_lrf_measure_screen,cmd.show_lrf_measure_screen),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,show_lrf_result_screen,cmd.show_lrf_result_screen),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,show_lrf_result_simplified_screen,cmd.show_lrf_result_simplified_screen),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,enable_heat_osd,cmd.enable_heat_osd),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,disable_heat_osd,cmd.disable_heat_osd),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,enable_day_osd,cmd.enable_day_osd),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,disable_day_osd,cmd.disable_day_osd),   8)
#define cmd_OSD_Root_CALLBACK NULL
#define cmd_OSD_Root_DEFAULT NULL
#define cmd_OSD_Root_cmd_show_default_screen_MSGTYPE cmd_OSD_ShowDefaultScreen
#define cmd_OSD_Root_cmd_show_lrf_measure_screen_MSGTYPE cmd_OSD_ShowLRFMeasureScreen
#define cmd_OSD_Root_cmd_show_lrf_result_screen_MSGTYPE cmd_OSD_ShowLRFResultScreen
#define cmd_OSD_Root_cmd_show_lrf_result_simplified_screen_MSGTYPE cmd_OSD_ShowLRFResultSimplifiedScreen
#define cmd_OSD_Root_cmd_enable_heat_osd_MSGTYPE cmd_OSD_EnableHeatOSD
#define cmd_OSD_Root_cmd_disable_heat_osd_MSGTYPE cmd_OSD_DisableHeatOSD
#define cmd_OSD_Root_cmd_enable_day_osd_MSGTYPE cmd_OSD_EnableDayOSD
#define cmd_OSD_Root_cmd_disable_day_osd_MSGTYPE cmd_OSD_DisableDayOSD

#define cmd_OSD_ShowDefaultScreen_FIELDLIST(X, a) \

#define cmd_OSD_ShowDefaultScreen_CALLBACK NULL
#define cmd_OSD_ShowDefaultScreen_DEFAULT NULL

#define cmd_OSD_ShowLRFMeasureScreen_FIELDLIST(X, a) \

#define cmd_OSD_ShowLRFMeasureScreen_CALLBACK NULL
#define cmd_OSD_ShowLRFMeasureScreen_DEFAULT NULL

#define cmd_OSD_ShowLRFResultScreen_FIELDLIST(X, a) \

#define cmd_OSD_ShowLRFResultScreen_CALLBACK NULL
#define cmd_OSD_ShowLRFResultScreen_DEFAULT NULL

#define cmd_OSD_ShowLRFResultSimplifiedScreen_FIELDLIST(X, a) \

#define cmd_OSD_ShowLRFResultSimplifiedScreen_CALLBACK NULL
#define cmd_OSD_ShowLRFResultSimplifiedScreen_DEFAULT NULL

#define cmd_OSD_EnableHeatOSD_FIELDLIST(X, a) \

#define cmd_OSD_EnableHeatOSD_CALLBACK NULL
#define cmd_OSD_EnableHeatOSD_DEFAULT NULL

#define cmd_OSD_DisableHeatOSD_FIELDLIST(X, a) \

#define cmd_OSD_DisableHeatOSD_CALLBACK NULL
#define cmd_OSD_DisableHeatOSD_DEFAULT NULL

#define cmd_OSD_EnableDayOSD_FIELDLIST(X, a) \

#define cmd_OSD_EnableDayOSD_CALLBACK NULL
#define cmd_OSD_EnableDayOSD_DEFAULT NULL

#define cmd_OSD_DisableDayOSD_FIELDLIST(X, a) \

#define cmd_OSD_DisableDayOSD_CALLBACK NULL
#define cmd_OSD_DisableDayOSD_DEFAULT NULL

extern const pb_msgdesc_t cmd_OSD_Root_msg;
extern const pb_msgdesc_t cmd_OSD_ShowDefaultScreen_msg;
extern const pb_msgdesc_t cmd_OSD_ShowLRFMeasureScreen_msg;
extern const pb_msgdesc_t cmd_OSD_ShowLRFResultScreen_msg;
extern const pb_msgdesc_t cmd_OSD_ShowLRFResultSimplifiedScreen_msg;
extern const pb_msgdesc_t cmd_OSD_EnableHeatOSD_msg;
extern const pb_msgdesc_t cmd_OSD_DisableHeatOSD_msg;
extern const pb_msgdesc_t cmd_OSD_EnableDayOSD_msg;
extern const pb_msgdesc_t cmd_OSD_DisableDayOSD_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_OSD_Root_fields &cmd_OSD_Root_msg
#define cmd_OSD_ShowDefaultScreen_fields &cmd_OSD_ShowDefaultScreen_msg
#define cmd_OSD_ShowLRFMeasureScreen_fields &cmd_OSD_ShowLRFMeasureScreen_msg
#define cmd_OSD_ShowLRFResultScreen_fields &cmd_OSD_ShowLRFResultScreen_msg
#define cmd_OSD_ShowLRFResultSimplifiedScreen_fields &cmd_OSD_ShowLRFResultSimplifiedScreen_msg
#define cmd_OSD_EnableHeatOSD_fields &cmd_OSD_EnableHeatOSD_msg
#define cmd_OSD_DisableHeatOSD_fields &cmd_OSD_DisableHeatOSD_msg
#define cmd_OSD_EnableDayOSD_fields &cmd_OSD_EnableDayOSD_msg
#define cmd_OSD_DisableDayOSD_fields &cmd_OSD_DisableDayOSD_msg

/* Maximum encoded size of messages (where known) */
#define CMD_OSD_JON_SHARED_CMD_OSD_PB_H_MAX_SIZE cmd_OSD_Root_size
#define cmd_OSD_DisableDayOSD_size               0
#define cmd_OSD_DisableHeatOSD_size              0
#define cmd_OSD_EnableDayOSD_size                0
#define cmd_OSD_EnableHeatOSD_size               0
#define cmd_OSD_Root_size                        2
#define cmd_OSD_ShowDefaultScreen_size           0
#define cmd_OSD_ShowLRFMeasureScreen_size        0
#define cmd_OSD_ShowLRFResultScreen_size         0
#define cmd_OSD_ShowLRFResultSimplifiedScreen_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
