/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_POWER_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_POWER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Power module state for a single channel (S0-S7) */
typedef struct _ser_JonGuiDataPowerModule
{
  double voltage; /* Volts */
  double current; /* Amps */
  double power;   /* Watts */
  bool is_on;     /* Channel power state */
  bool has_alarm; /* Overcurrent/fault alarm */
} ser_JonGuiDataPowerModule;

/* Power state for all 8 channels */
typedef struct _ser_JonGuiDataPower
{
  bool has_s0;
  ser_JonGuiDataPowerModule s0; /* GPS */
  bool has_s1;
  ser_JonGuiDataPowerModule s1; /* Compass */
  bool has_s2;
  ser_JonGuiDataPowerModule s2; /* LRF (Laser Range Finder) */
  bool has_s3;
  ser_JonGuiDataPowerModule s3; /* Day Camera Lens */
  bool has_s4;
  ser_JonGuiDataPowerModule s4; /* Thermal Camera */
  bool has_s5;
  ser_JonGuiDataPowerModule s5; /* ORIN NUC (Main compute) */
  bool has_s6;
  ser_JonGuiDataPowerModule s6; /* Thermal Core */
  bool has_s7;
  ser_JonGuiDataPowerModule s7; /* Heater / Spare */
} ser_JonGuiDataPower;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataPowerModule_init_default \
  {                                            \
    0, 0, 0, 0, 0                              \
  }
#define ser_JonGuiDataPower_init_default                  \
  {                                                       \
    false, ser_JonGuiDataPowerModule_init_default, false, \
      ser_JonGuiDataPowerModule_init_default, false,      \
      ser_JonGuiDataPowerModule_init_default, false,      \
      ser_JonGuiDataPowerModule_init_default, false,      \
      ser_JonGuiDataPowerModule_init_default, false,      \
      ser_JonGuiDataPowerModule_init_default, false,      \
      ser_JonGuiDataPowerModule_init_default, false,      \
      ser_JonGuiDataPowerModule_init_default              \
  }
#define ser_JonGuiDataPowerModule_init_zero \
  {                                         \
    0, 0, 0, 0, 0                           \
  }
#define ser_JonGuiDataPower_init_zero                  \
  {                                                    \
    false, ser_JonGuiDataPowerModule_init_zero, false, \
      ser_JonGuiDataPowerModule_init_zero, false,      \
      ser_JonGuiDataPowerModule_init_zero, false,      \
      ser_JonGuiDataPowerModule_init_zero, false,      \
      ser_JonGuiDataPowerModule_init_zero, false,      \
      ser_JonGuiDataPowerModule_init_zero, false,      \
      ser_JonGuiDataPowerModule_init_zero, false,      \
      ser_JonGuiDataPowerModule_init_zero              \
  }

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataPowerModule_voltage_tag 1
#define ser_JonGuiDataPowerModule_current_tag 2
#define ser_JonGuiDataPowerModule_power_tag 3
#define ser_JonGuiDataPowerModule_is_on_tag 4
#define ser_JonGuiDataPowerModule_has_alarm_tag 5
#define ser_JonGuiDataPower_s0_tag 1
#define ser_JonGuiDataPower_s1_tag 2
#define ser_JonGuiDataPower_s2_tag 3
#define ser_JonGuiDataPower_s3_tag 4
#define ser_JonGuiDataPower_s4_tag 5
#define ser_JonGuiDataPower_s5_tag 6
#define ser_JonGuiDataPower_s6_tag 7
#define ser_JonGuiDataPower_s7_tag 8

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataPowerModule_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, voltage, 1)      \
  X(a, STATIC, SINGULAR, DOUBLE, current, 2)      \
  X(a, STATIC, SINGULAR, DOUBLE, power, 3)        \
  X(a, STATIC, SINGULAR, BOOL, is_on, 4)          \
  X(a, STATIC, SINGULAR, BOOL, has_alarm, 5)
#define ser_JonGuiDataPowerModule_CALLBACK NULL
#define ser_JonGuiDataPowerModule_DEFAULT NULL

#define ser_JonGuiDataPower_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, s0, 1)    \
  X(a, STATIC, OPTIONAL, MESSAGE, s1, 2)    \
  X(a, STATIC, OPTIONAL, MESSAGE, s2, 3)    \
  X(a, STATIC, OPTIONAL, MESSAGE, s3, 4)    \
  X(a, STATIC, OPTIONAL, MESSAGE, s4, 5)    \
  X(a, STATIC, OPTIONAL, MESSAGE, s5, 6)    \
  X(a, STATIC, OPTIONAL, MESSAGE, s6, 7)    \
  X(a, STATIC, OPTIONAL, MESSAGE, s7, 8)
#define ser_JonGuiDataPower_CALLBACK NULL
#define ser_JonGuiDataPower_DEFAULT NULL
#define ser_JonGuiDataPower_s0_MSGTYPE ser_JonGuiDataPowerModule
#define ser_JonGuiDataPower_s1_MSGTYPE ser_JonGuiDataPowerModule
#define ser_JonGuiDataPower_s2_MSGTYPE ser_JonGuiDataPowerModule
#define ser_JonGuiDataPower_s3_MSGTYPE ser_JonGuiDataPowerModule
#define ser_JonGuiDataPower_s4_MSGTYPE ser_JonGuiDataPowerModule
#define ser_JonGuiDataPower_s5_MSGTYPE ser_JonGuiDataPowerModule
#define ser_JonGuiDataPower_s6_MSGTYPE ser_JonGuiDataPowerModule
#define ser_JonGuiDataPower_s7_MSGTYPE ser_JonGuiDataPowerModule

  extern const pb_msgdesc_t ser_JonGuiDataPowerModule_msg;
  extern const pb_msgdesc_t ser_JonGuiDataPower_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataPowerModule_fields &ser_JonGuiDataPowerModule_msg
#define ser_JonGuiDataPower_fields &ser_JonGuiDataPower_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_POWER_PB_H_MAX_SIZE ser_JonGuiDataPower_size
#define ser_JonGuiDataPowerModule_size 31
#define ser_JonGuiDataPower_size 264

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
