/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_power.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_Power_Root, cmd_Power_Root, AUTO)


PB_BIND(cmd_Power_SetChannel, cmd_Power_SetChannel, AUTO)


PB_BIND(cmd_Power_SetAll, cmd_Power_SetAll, AUTO)


PB_BIND(cmd_Power_SetAlertThreshold, cmd_Power_SetAlertThreshold, AUTO)
