/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_POWER_JON_SHARED_CMD_POWER_PB_H_INCLUDED
#define PB_CMD_POWER_JON_SHARED_CMD_POWER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Set power state for a single channel */
typedef struct _cmd_Power_SetChannel
{
  uint32_t channel;
  bool power_on;
} cmd_Power_SetChannel;

/* Set power state for all channels */
typedef struct _cmd_Power_SetAll
{
  bool power_on;
} cmd_Power_SetAll;

/* Set overcurrent alert threshold for a channel */
typedef struct _cmd_Power_SetAlertThreshold
{
  uint32_t channel;
  uint32_t threshold_ma; /* Threshold in milliamps */
} cmd_Power_SetAlertThreshold;

/* Power module control commands root */
typedef struct _cmd_Power_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_Power_SetChannel set_channel;
    cmd_Power_SetAll set_all;
    cmd_Power_SetAlertThreshold set_alert_threshold;
  } cmd;
} cmd_Power_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_Power_Root_init_default     \
  {                                     \
    0,                                  \
    {                                   \
      cmd_Power_SetChannel_init_default \
    }                                   \
  }
#define cmd_Power_SetChannel_init_default { 0, 0 }
#define cmd_Power_SetAll_init_default { 0 }
#define cmd_Power_SetAlertThreshold_init_default { 0, 0 }
#define cmd_Power_Root_init_zero     \
  {                                  \
    0,                               \
    {                                \
      cmd_Power_SetChannel_init_zero \
    }                                \
  }
#define cmd_Power_SetChannel_init_zero { 0, 0 }
#define cmd_Power_SetAll_init_zero { 0 }
#define cmd_Power_SetAlertThreshold_init_zero { 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_Power_SetChannel_channel_tag 1
#define cmd_Power_SetChannel_power_on_tag 2
#define cmd_Power_SetAll_power_on_tag 1
#define cmd_Power_SetAlertThreshold_channel_tag 1
#define cmd_Power_SetAlertThreshold_threshold_ma_tag 2
#define cmd_Power_Root_set_channel_tag 1
#define cmd_Power_Root_set_all_tag 2
#define cmd_Power_Root_set_alert_threshold_tag 3

/* Struct field encoding specification for nanopb */
#define cmd_Power_Root_FIELDLIST(X, a)                                 \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_channel, cmd.set_channel), 1) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_all, cmd.set_all), 2)         \
  X(a, STATIC, ONEOF, MESSAGE,                                         \
    (cmd, set_alert_threshold, cmd.set_alert_threshold), 3)
#define cmd_Power_Root_CALLBACK NULL
#define cmd_Power_Root_DEFAULT NULL
#define cmd_Power_Root_cmd_set_channel_MSGTYPE cmd_Power_SetChannel
#define cmd_Power_Root_cmd_set_all_MSGTYPE cmd_Power_SetAll
#define cmd_Power_Root_cmd_set_alert_threshold_MSGTYPE \
  cmd_Power_SetAlertThreshold

#define cmd_Power_SetChannel_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UINT32, channel, 1) \
  X(a, STATIC, SINGULAR, BOOL, power_on, 2)
#define cmd_Power_SetChannel_CALLBACK NULL
#define cmd_Power_SetChannel_DEFAULT NULL

#define cmd_Power_SetAll_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, BOOL, power_on, 1)
#define cmd_Power_SetAll_CALLBACK NULL
#define cmd_Power_SetAll_DEFAULT NULL

#define cmd_Power_SetAlertThreshold_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UINT32, channel, 1)        \
  X(a, STATIC, SINGULAR, UINT32, threshold_ma, 2)
#define cmd_Power_SetAlertThreshold_CALLBACK NULL
#define cmd_Power_SetAlertThreshold_DEFAULT NULL

  extern const pb_msgdesc_t cmd_Power_Root_msg;
  extern const pb_msgdesc_t cmd_Power_SetChannel_msg;
  extern const pb_msgdesc_t cmd_Power_SetAll_msg;
  extern const pb_msgdesc_t cmd_Power_SetAlertThreshold_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_Power_Root_fields &cmd_Power_Root_msg
#define cmd_Power_SetChannel_fields &cmd_Power_SetChannel_msg
#define cmd_Power_SetAll_fields &cmd_Power_SetAll_msg
#define cmd_Power_SetAlertThreshold_fields &cmd_Power_SetAlertThreshold_msg

/* Maximum encoded size of messages (where known) */
#define CMD_POWER_JON_SHARED_CMD_POWER_PB_H_MAX_SIZE cmd_Power_Root_size
#define cmd_Power_Root_size 14
#define cmd_Power_SetAlertThreshold_size 12
#define cmd_Power_SetAll_size 2
#define cmd_Power_SetChannel_size 8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
