/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_SYSTEM_JON_SHARED_CMD_SYSTEM_PB_H_INCLUDED
#define PB_CMD_SYSTEM_JON_SHARED_CMD_SYSTEM_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_System_StartALl
{
  char dummy_field;
} cmd_System_StartALl;

typedef struct _cmd_System_StopALl
{
  char dummy_field;
} cmd_System_StopALl;

typedef struct _cmd_System_Reboot
{
  char dummy_field;
} cmd_System_Reboot;

typedef struct _cmd_System_PowerOff
{
  char dummy_field;
} cmd_System_PowerOff;

typedef struct _cmd_System_ResetConfigs
{
  char dummy_field;
} cmd_System_ResetConfigs;

typedef struct _cmd_System_SaveFactoryDefaults
{
  char dummy_field;
} cmd_System_SaveFactoryDefaults;

typedef struct _cmd_System_WipeUserData
{
  char dummy_field;
} cmd_System_WipeUserData;

typedef struct _cmd_System_StartRec
{
  char dummy_field;
} cmd_System_StartRec;

typedef struct _cmd_System_StopRec
{
  char dummy_field;
} cmd_System_StopRec;

typedef struct _cmd_System_MarkRecImportant
{
  char dummy_field;
} cmd_System_MarkRecImportant;

typedef struct _cmd_System_UnmarkRecImportant
{
  char dummy_field;
} cmd_System_UnmarkRecImportant;

typedef struct _cmd_System_EnterTransport
{
  char dummy_field;
} cmd_System_EnterTransport;

typedef struct _cmd_System_EnableGeodesicMode
{
  char dummy_field;
} cmd_System_EnableGeodesicMode;

typedef struct _cmd_System_DisableGeodesicMode
{
  char dummy_field;
} cmd_System_DisableGeodesicMode;

typedef struct _cmd_System_SetLocalization
{
  ser_JonGuiDataSystemLocalizations loc;
} cmd_System_SetLocalization;

typedef struct _cmd_System_StepYear
{
  int32_t offset; /* Positive or negative year offset */
} cmd_System_StepYear;

typedef struct _cmd_System_StepMonth
{
  int32_t offset; /* Positive or negative month offset */
} cmd_System_StepMonth;

typedef struct _cmd_System_StepDay
{
  int32_t offset; /* Positive or negative day offset */
} cmd_System_StepDay;

typedef struct _cmd_System_StepHour
{
  int32_t offset; /* Positive or negative hour offset */
} cmd_System_StepHour;

typedef struct _cmd_System_StepMinute
{
  int32_t offset; /* Positive or negative minute offset */
} cmd_System_StepMinute;

typedef struct _cmd_System_StepSecond
{
  int32_t offset; /* Positive or negative second offset */
} cmd_System_StepSecond;

typedef struct _cmd_System_EnableManualTime
{
  char dummy_field;
} cmd_System_EnableManualTime;

typedef struct _cmd_System_DisableManualTime
{
  char dummy_field;
} cmd_System_DisableManualTime;

typedef struct _cmd_System_SetTimeZone
{
  int32_t zone_id;
} cmd_System_SetTimeZone;

typedef struct _cmd_System_StepTimeZone
{
  int32_t offset; /* Positive or negative timezone index offset */
} cmd_System_StepTimeZone;

typedef struct _cmd_System_SetTimeAndZone
{
  int64_t timestamp;
  int32_t zone_id;
} cmd_System_SetTimeAndZone;

typedef struct _cmd_System_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_System_StartALl start_all;
    cmd_System_StopALl stop_all;
    cmd_System_Reboot reboot;
    cmd_System_PowerOff power_off;
    cmd_System_SetLocalization localization;
    cmd_System_ResetConfigs reset_configs;
    cmd_System_StartRec start_rec;
    cmd_System_StopRec stop_rec;
    cmd_System_MarkRecImportant mark_rec_important;
    cmd_System_UnmarkRecImportant unmark_rec_important;
    cmd_System_EnterTransport enter_transport;
    cmd_System_EnableGeodesicMode geodesic_mode_enable;
    cmd_System_DisableGeodesicMode geodesic_mode_disable;
    cmd_System_SaveFactoryDefaults save_factory_defaults;
    cmd_System_WipeUserData wipe_user_data;
    cmd_System_StepYear step_year;
    cmd_System_StepMonth step_month;
    cmd_System_StepDay step_day;
    cmd_System_StepHour step_hour;
    cmd_System_StepMinute step_minute;
    cmd_System_StepSecond step_second;
    cmd_System_EnableManualTime enable_manual_time;
    cmd_System_DisableManualTime disable_manual_time;
    cmd_System_SetTimeZone set_time_zone;
    cmd_System_StepTimeZone step_time_zone;
    cmd_System_SetTimeAndZone set_time_and_zone;
  } cmd;
} cmd_System_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_System_Root_init_default   \
  {                                    \
    0,                                 \
    {                                  \
      cmd_System_StartALl_init_default \
    }                                  \
  }
#define cmd_System_StartALl_init_default { 0 }
#define cmd_System_StopALl_init_default { 0 }
#define cmd_System_Reboot_init_default { 0 }
#define cmd_System_PowerOff_init_default { 0 }
#define cmd_System_ResetConfigs_init_default { 0 }
#define cmd_System_SaveFactoryDefaults_init_default { 0 }
#define cmd_System_WipeUserData_init_default { 0 }
#define cmd_System_StartRec_init_default { 0 }
#define cmd_System_StopRec_init_default { 0 }
#define cmd_System_MarkRecImportant_init_default { 0 }
#define cmd_System_UnmarkRecImportant_init_default { 0 }
#define cmd_System_EnterTransport_init_default { 0 }
#define cmd_System_EnableGeodesicMode_init_default { 0 }
#define cmd_System_DisableGeodesicMode_init_default { 0 }
#define cmd_System_SetLocalization_init_default \
  { _ser_JonGuiDataSystemLocalizations_MIN }
#define cmd_System_StepYear_init_default { 0 }
#define cmd_System_StepMonth_init_default { 0 }
#define cmd_System_StepDay_init_default { 0 }
#define cmd_System_StepHour_init_default { 0 }
#define cmd_System_StepMinute_init_default { 0 }
#define cmd_System_StepSecond_init_default { 0 }
#define cmd_System_EnableManualTime_init_default { 0 }
#define cmd_System_DisableManualTime_init_default { 0 }
#define cmd_System_SetTimeZone_init_default { 0 }
#define cmd_System_StepTimeZone_init_default { 0 }
#define cmd_System_SetTimeAndZone_init_default { 0, 0 }
#define cmd_System_Root_init_zero   \
  {                                 \
    0,                              \
    {                               \
      cmd_System_StartALl_init_zero \
    }                               \
  }
#define cmd_System_StartALl_init_zero { 0 }
#define cmd_System_StopALl_init_zero { 0 }
#define cmd_System_Reboot_init_zero { 0 }
#define cmd_System_PowerOff_init_zero { 0 }
#define cmd_System_ResetConfigs_init_zero { 0 }
#define cmd_System_SaveFactoryDefaults_init_zero { 0 }
#define cmd_System_WipeUserData_init_zero { 0 }
#define cmd_System_StartRec_init_zero { 0 }
#define cmd_System_StopRec_init_zero { 0 }
#define cmd_System_MarkRecImportant_init_zero { 0 }
#define cmd_System_UnmarkRecImportant_init_zero { 0 }
#define cmd_System_EnterTransport_init_zero { 0 }
#define cmd_System_EnableGeodesicMode_init_zero { 0 }
#define cmd_System_DisableGeodesicMode_init_zero { 0 }
#define cmd_System_SetLocalization_init_zero \
  { _ser_JonGuiDataSystemLocalizations_MIN }
#define cmd_System_StepYear_init_zero { 0 }
#define cmd_System_StepMonth_init_zero { 0 }
#define cmd_System_StepDay_init_zero { 0 }
#define cmd_System_StepHour_init_zero { 0 }
#define cmd_System_StepMinute_init_zero { 0 }
#define cmd_System_StepSecond_init_zero { 0 }
#define cmd_System_EnableManualTime_init_zero { 0 }
#define cmd_System_DisableManualTime_init_zero { 0 }
#define cmd_System_SetTimeZone_init_zero { 0 }
#define cmd_System_StepTimeZone_init_zero { 0 }
#define cmd_System_SetTimeAndZone_init_zero { 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_System_SetLocalization_loc_tag 1
#define cmd_System_StepYear_offset_tag 1
#define cmd_System_StepMonth_offset_tag 1
#define cmd_System_StepDay_offset_tag 1
#define cmd_System_StepHour_offset_tag 1
#define cmd_System_StepMinute_offset_tag 1
#define cmd_System_StepSecond_offset_tag 1
#define cmd_System_SetTimeZone_zone_id_tag 1
#define cmd_System_StepTimeZone_offset_tag 1
#define cmd_System_SetTimeAndZone_timestamp_tag 1
#define cmd_System_SetTimeAndZone_zone_id_tag 2
#define cmd_System_Root_start_all_tag 1
#define cmd_System_Root_stop_all_tag 2
#define cmd_System_Root_reboot_tag 3
#define cmd_System_Root_power_off_tag 4
#define cmd_System_Root_localization_tag 5
#define cmd_System_Root_reset_configs_tag 6
#define cmd_System_Root_start_rec_tag 7
#define cmd_System_Root_stop_rec_tag 8
#define cmd_System_Root_mark_rec_important_tag 9
#define cmd_System_Root_unmark_rec_important_tag 10
#define cmd_System_Root_enter_transport_tag 11
#define cmd_System_Root_geodesic_mode_enable_tag 12
#define cmd_System_Root_geodesic_mode_disable_tag 13
#define cmd_System_Root_save_factory_defaults_tag 14
#define cmd_System_Root_wipe_user_data_tag 15
#define cmd_System_Root_step_year_tag 16
#define cmd_System_Root_step_month_tag 17
#define cmd_System_Root_step_day_tag 18
#define cmd_System_Root_step_hour_tag 19
#define cmd_System_Root_step_minute_tag 20
#define cmd_System_Root_step_second_tag 21
#define cmd_System_Root_enable_manual_time_tag 22
#define cmd_System_Root_disable_manual_time_tag 23
#define cmd_System_Root_set_time_zone_tag 24
#define cmd_System_Root_step_time_zone_tag 25
#define cmd_System_Root_set_time_and_zone_tag 26

/* Struct field encoding specification for nanopb */
#define cmd_System_Root_FIELDLIST(X, a)                                       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start_all, cmd.start_all), 1)            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop_all, cmd.stop_all), 2)              \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, reboot, cmd.reboot), 3)                  \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, power_off, cmd.power_off), 4)            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, localization, cmd.localization), 5)      \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, reset_configs, cmd.reset_configs), 6)    \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start_rec, cmd.start_rec), 7)            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop_rec, cmd.stop_rec), 8)              \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, mark_rec_important, cmd.mark_rec_important), 9)                     \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, unmark_rec_important, cmd.unmark_rec_important), 10)                \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, enter_transport, cmd.enter_transport),   \
    11)                                                                       \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, geodesic_mode_enable, cmd.geodesic_mode_enable), 12)                \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, geodesic_mode_disable, cmd.geodesic_mode_disable), 13)              \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, save_factory_defaults, cmd.save_factory_defaults), 14)              \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, wipe_user_data, cmd.wipe_user_data), 15) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, step_year, cmd.step_year), 16)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, step_month, cmd.step_month), 17)         \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, step_day, cmd.step_day), 18)             \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, step_hour, cmd.step_hour), 19)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, step_minute, cmd.step_minute), 20)       \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, step_second, cmd.step_second), 21)       \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, enable_manual_time, cmd.enable_manual_time), 22)                    \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, disable_manual_time, cmd.disable_manual_time), 23)                  \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_time_zone, cmd.set_time_zone), 24)   \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, step_time_zone, cmd.step_time_zone), 25) \
  X(a, STATIC, ONEOF, MESSAGE,                                                \
    (cmd, set_time_and_zone, cmd.set_time_and_zone), 26)
#define cmd_System_Root_CALLBACK NULL
#define cmd_System_Root_DEFAULT NULL
#define cmd_System_Root_cmd_start_all_MSGTYPE cmd_System_StartALl
#define cmd_System_Root_cmd_stop_all_MSGTYPE cmd_System_StopALl
#define cmd_System_Root_cmd_reboot_MSGTYPE cmd_System_Reboot
#define cmd_System_Root_cmd_power_off_MSGTYPE cmd_System_PowerOff
#define cmd_System_Root_cmd_localization_MSGTYPE cmd_System_SetLocalization
#define cmd_System_Root_cmd_reset_configs_MSGTYPE cmd_System_ResetConfigs
#define cmd_System_Root_cmd_start_rec_MSGTYPE cmd_System_StartRec
#define cmd_System_Root_cmd_stop_rec_MSGTYPE cmd_System_StopRec
#define cmd_System_Root_cmd_mark_rec_important_MSGTYPE \
  cmd_System_MarkRecImportant
#define cmd_System_Root_cmd_unmark_rec_important_MSGTYPE \
  cmd_System_UnmarkRecImportant
#define cmd_System_Root_cmd_enter_transport_MSGTYPE cmd_System_EnterTransport
#define cmd_System_Root_cmd_geodesic_mode_enable_MSGTYPE \
  cmd_System_EnableGeodesicMode
#define cmd_System_Root_cmd_geodesic_mode_disable_MSGTYPE \
  cmd_System_DisableGeodesicMode
#define cmd_System_Root_cmd_save_factory_defaults_MSGTYPE \
  cmd_System_SaveFactoryDefaults
#define cmd_System_Root_cmd_wipe_user_data_MSGTYPE cmd_System_WipeUserData
#define cmd_System_Root_cmd_step_year_MSGTYPE cmd_System_StepYear
#define cmd_System_Root_cmd_step_month_MSGTYPE cmd_System_StepMonth
#define cmd_System_Root_cmd_step_day_MSGTYPE cmd_System_StepDay
#define cmd_System_Root_cmd_step_hour_MSGTYPE cmd_System_StepHour
#define cmd_System_Root_cmd_step_minute_MSGTYPE cmd_System_StepMinute
#define cmd_System_Root_cmd_step_second_MSGTYPE cmd_System_StepSecond
#define cmd_System_Root_cmd_enable_manual_time_MSGTYPE \
  cmd_System_EnableManualTime
#define cmd_System_Root_cmd_disable_manual_time_MSGTYPE \
  cmd_System_DisableManualTime
#define cmd_System_Root_cmd_set_time_zone_MSGTYPE cmd_System_SetTimeZone
#define cmd_System_Root_cmd_step_time_zone_MSGTYPE cmd_System_StepTimeZone
#define cmd_System_Root_cmd_set_time_and_zone_MSGTYPE cmd_System_SetTimeAndZone

#define cmd_System_StartALl_FIELDLIST(X, a)

#define cmd_System_StartALl_CALLBACK NULL
#define cmd_System_StartALl_DEFAULT NULL

#define cmd_System_StopALl_FIELDLIST(X, a)

#define cmd_System_StopALl_CALLBACK NULL
#define cmd_System_StopALl_DEFAULT NULL

#define cmd_System_Reboot_FIELDLIST(X, a)

#define cmd_System_Reboot_CALLBACK NULL
#define cmd_System_Reboot_DEFAULT NULL

#define cmd_System_PowerOff_FIELDLIST(X, a)

#define cmd_System_PowerOff_CALLBACK NULL
#define cmd_System_PowerOff_DEFAULT NULL

#define cmd_System_ResetConfigs_FIELDLIST(X, a)

#define cmd_System_ResetConfigs_CALLBACK NULL
#define cmd_System_ResetConfigs_DEFAULT NULL

#define cmd_System_SaveFactoryDefaults_FIELDLIST(X, a)

#define cmd_System_SaveFactoryDefaults_CALLBACK NULL
#define cmd_System_SaveFactoryDefaults_DEFAULT NULL

#define cmd_System_WipeUserData_FIELDLIST(X, a)

#define cmd_System_WipeUserData_CALLBACK NULL
#define cmd_System_WipeUserData_DEFAULT NULL

#define cmd_System_StartRec_FIELDLIST(X, a)

#define cmd_System_StartRec_CALLBACK NULL
#define cmd_System_StartRec_DEFAULT NULL

#define cmd_System_StopRec_FIELDLIST(X, a)

#define cmd_System_StopRec_CALLBACK NULL
#define cmd_System_StopRec_DEFAULT NULL

#define cmd_System_MarkRecImportant_FIELDLIST(X, a)

#define cmd_System_MarkRecImportant_CALLBACK NULL
#define cmd_System_MarkRecImportant_DEFAULT NULL

#define cmd_System_UnmarkRecImportant_FIELDLIST(X, a)

#define cmd_System_UnmarkRecImportant_CALLBACK NULL
#define cmd_System_UnmarkRecImportant_DEFAULT NULL

#define cmd_System_EnterTransport_FIELDLIST(X, a)

#define cmd_System_EnterTransport_CALLBACK NULL
#define cmd_System_EnterTransport_DEFAULT NULL

#define cmd_System_EnableGeodesicMode_FIELDLIST(X, a)

#define cmd_System_EnableGeodesicMode_CALLBACK NULL
#define cmd_System_EnableGeodesicMode_DEFAULT NULL

#define cmd_System_DisableGeodesicMode_FIELDLIST(X, a)

#define cmd_System_DisableGeodesicMode_CALLBACK NULL
#define cmd_System_DisableGeodesicMode_DEFAULT NULL

#define cmd_System_SetLocalization_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, loc, 1)
#define cmd_System_SetLocalization_CALLBACK NULL
#define cmd_System_SetLocalization_DEFAULT NULL

#define cmd_System_StepYear_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, offset, 1)
#define cmd_System_StepYear_CALLBACK NULL
#define cmd_System_StepYear_DEFAULT NULL

#define cmd_System_StepMonth_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, offset, 1)
#define cmd_System_StepMonth_CALLBACK NULL
#define cmd_System_StepMonth_DEFAULT NULL

#define cmd_System_StepDay_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, offset, 1)
#define cmd_System_StepDay_CALLBACK NULL
#define cmd_System_StepDay_DEFAULT NULL

#define cmd_System_StepHour_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, offset, 1)
#define cmd_System_StepHour_CALLBACK NULL
#define cmd_System_StepHour_DEFAULT NULL

#define cmd_System_StepMinute_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, offset, 1)
#define cmd_System_StepMinute_CALLBACK NULL
#define cmd_System_StepMinute_DEFAULT NULL

#define cmd_System_StepSecond_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, offset, 1)
#define cmd_System_StepSecond_CALLBACK NULL
#define cmd_System_StepSecond_DEFAULT NULL

#define cmd_System_EnableManualTime_FIELDLIST(X, a)

#define cmd_System_EnableManualTime_CALLBACK NULL
#define cmd_System_EnableManualTime_DEFAULT NULL

#define cmd_System_DisableManualTime_FIELDLIST(X, a)

#define cmd_System_DisableManualTime_CALLBACK NULL
#define cmd_System_DisableManualTime_DEFAULT NULL

#define cmd_System_SetTimeZone_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, zone_id, 1)
#define cmd_System_SetTimeZone_CALLBACK NULL
#define cmd_System_SetTimeZone_DEFAULT NULL

#define cmd_System_StepTimeZone_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT32, offset, 1)
#define cmd_System_StepTimeZone_CALLBACK NULL
#define cmd_System_StepTimeZone_DEFAULT NULL

#define cmd_System_SetTimeAndZone_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, INT64, timestamp, 1)     \
  X(a, STATIC, SINGULAR, INT32, zone_id, 2)
#define cmd_System_SetTimeAndZone_CALLBACK NULL
#define cmd_System_SetTimeAndZone_DEFAULT NULL

  extern const pb_msgdesc_t cmd_System_Root_msg;
  extern const pb_msgdesc_t cmd_System_StartALl_msg;
  extern const pb_msgdesc_t cmd_System_StopALl_msg;
  extern const pb_msgdesc_t cmd_System_Reboot_msg;
  extern const pb_msgdesc_t cmd_System_PowerOff_msg;
  extern const pb_msgdesc_t cmd_System_ResetConfigs_msg;
  extern const pb_msgdesc_t cmd_System_SaveFactoryDefaults_msg;
  extern const pb_msgdesc_t cmd_System_WipeUserData_msg;
  extern const pb_msgdesc_t cmd_System_StartRec_msg;
  extern const pb_msgdesc_t cmd_System_StopRec_msg;
  extern const pb_msgdesc_t cmd_System_MarkRecImportant_msg;
  extern const pb_msgdesc_t cmd_System_UnmarkRecImportant_msg;
  extern const pb_msgdesc_t cmd_System_EnterTransport_msg;
  extern const pb_msgdesc_t cmd_System_EnableGeodesicMode_msg;
  extern const pb_msgdesc_t cmd_System_DisableGeodesicMode_msg;
  extern const pb_msgdesc_t cmd_System_SetLocalization_msg;
  extern const pb_msgdesc_t cmd_System_StepYear_msg;
  extern const pb_msgdesc_t cmd_System_StepMonth_msg;
  extern const pb_msgdesc_t cmd_System_StepDay_msg;
  extern const pb_msgdesc_t cmd_System_StepHour_msg;
  extern const pb_msgdesc_t cmd_System_StepMinute_msg;
  extern const pb_msgdesc_t cmd_System_StepSecond_msg;
  extern const pb_msgdesc_t cmd_System_EnableManualTime_msg;
  extern const pb_msgdesc_t cmd_System_DisableManualTime_msg;
  extern const pb_msgdesc_t cmd_System_SetTimeZone_msg;
  extern const pb_msgdesc_t cmd_System_StepTimeZone_msg;
  extern const pb_msgdesc_t cmd_System_SetTimeAndZone_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_System_Root_fields &cmd_System_Root_msg
#define cmd_System_StartALl_fields &cmd_System_StartALl_msg
#define cmd_System_StopALl_fields &cmd_System_StopALl_msg
#define cmd_System_Reboot_fields &cmd_System_Reboot_msg
#define cmd_System_PowerOff_fields &cmd_System_PowerOff_msg
#define cmd_System_ResetConfigs_fields &cmd_System_ResetConfigs_msg
#define cmd_System_SaveFactoryDefaults_fields \
  &cmd_System_SaveFactoryDefaults_msg
#define cmd_System_WipeUserData_fields &cmd_System_WipeUserData_msg
#define cmd_System_StartRec_fields &cmd_System_StartRec_msg
#define cmd_System_StopRec_fields &cmd_System_StopRec_msg
#define cmd_System_MarkRecImportant_fields &cmd_System_MarkRecImportant_msg
#define cmd_System_UnmarkRecImportant_fields &cmd_System_UnmarkRecImportant_msg
#define cmd_System_EnterTransport_fields &cmd_System_EnterTransport_msg
#define cmd_System_EnableGeodesicMode_fields &cmd_System_EnableGeodesicMode_msg
#define cmd_System_DisableGeodesicMode_fields \
  &cmd_System_DisableGeodesicMode_msg
#define cmd_System_SetLocalization_fields &cmd_System_SetLocalization_msg
#define cmd_System_StepYear_fields &cmd_System_StepYear_msg
#define cmd_System_StepMonth_fields &cmd_System_StepMonth_msg
#define cmd_System_StepDay_fields &cmd_System_StepDay_msg
#define cmd_System_StepHour_fields &cmd_System_StepHour_msg
#define cmd_System_StepMinute_fields &cmd_System_StepMinute_msg
#define cmd_System_StepSecond_fields &cmd_System_StepSecond_msg
#define cmd_System_EnableManualTime_fields &cmd_System_EnableManualTime_msg
#define cmd_System_DisableManualTime_fields &cmd_System_DisableManualTime_msg
#define cmd_System_SetTimeZone_fields &cmd_System_SetTimeZone_msg
#define cmd_System_StepTimeZone_fields &cmd_System_StepTimeZone_msg
#define cmd_System_SetTimeAndZone_fields &cmd_System_SetTimeAndZone_msg

/* Maximum encoded size of messages (where known) */
#define CMD_SYSTEM_JON_SHARED_CMD_SYSTEM_PB_H_MAX_SIZE cmd_System_Root_size
#define cmd_System_DisableGeodesicMode_size 0
#define cmd_System_DisableManualTime_size 0
#define cmd_System_EnableGeodesicMode_size 0
#define cmd_System_EnableManualTime_size 0
#define cmd_System_EnterTransport_size 0
#define cmd_System_MarkRecImportant_size 0
#define cmd_System_PowerOff_size 0
#define cmd_System_Reboot_size 0
#define cmd_System_ResetConfigs_size 0
#define cmd_System_Root_size 25
#define cmd_System_SaveFactoryDefaults_size 0
#define cmd_System_SetLocalization_size 2
#define cmd_System_SetTimeAndZone_size 22
#define cmd_System_SetTimeZone_size 11
#define cmd_System_StartALl_size 0
#define cmd_System_StartRec_size 0
#define cmd_System_StepDay_size 11
#define cmd_System_StepHour_size 11
#define cmd_System_StepMinute_size 11
#define cmd_System_StepMonth_size 11
#define cmd_System_StepSecond_size 11
#define cmd_System_StepTimeZone_size 11
#define cmd_System_StepYear_size 11
#define cmd_System_StopALl_size 0
#define cmd_System_StopRec_size 0
#define cmd_System_UnmarkRecImportant_size 0
#define cmd_System_WipeUserData_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
