/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_CMD_CV_JON_SHARED_CMD_CV_PB_H_INCLUDED
#define PB_CMD_CV_JON_SHARED_CMD_CV_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cmd_CV_VampireModeEnable
{
  char dummy_field;
} cmd_CV_VampireModeEnable;

typedef struct _cmd_CV_DumpStart
{
  char dummy_field;
} cmd_CV_DumpStart;

typedef struct _cmd_CV_DumpStop
{
  char dummy_field;
} cmd_CV_DumpStop;

typedef struct _cmd_CV_VampireModeDisable
{
  char dummy_field;
} cmd_CV_VampireModeDisable;

typedef struct _cmd_CV_StabilizationModeEnable
{
  char dummy_field;
} cmd_CV_StabilizationModeEnable;

typedef struct _cmd_CV_StabilizationModeDisable
{
  char dummy_field;
} cmd_CV_StabilizationModeDisable;

typedef struct _cmd_CV_RecognitionModeEnable
{
  char dummy_field;
} cmd_CV_RecognitionModeEnable;

typedef struct _cmd_CV_RecognitionModeDisable
{
  char dummy_field;
} cmd_CV_RecognitionModeDisable;

typedef struct _cmd_CV_SetAutoFocus
{
  ser_JonGuiDataVideoChannel channel;
  bool value;
} cmd_CV_SetAutoFocus;

typedef struct _cmd_CV_StartTrackNDC
{
  ser_JonGuiDataVideoChannel channel;
  double x;
  double y;
  /* TODO: Remove these fields after migration - now in Root message (fields
   * 6-8) */
  uint64_t frame_time;
  uint64_t state_time; /* System monotonic time from state when user performed
                          action */
} cmd_CV_StartTrackNDC;

typedef struct _cmd_CV_StopTrack
{
  char dummy_field;
} cmd_CV_StopTrack;

typedef struct _cmd_CV_Root
{
  pb_size_t which_cmd;
  union
  {
    cmd_CV_SetAutoFocus set_auto_focus;
    cmd_CV_StartTrackNDC start_track_ndc;
    cmd_CV_StopTrack stop_track;
    cmd_CV_VampireModeEnable vampire_mode_enable;
    cmd_CV_VampireModeDisable vampire_mode_disable;
    cmd_CV_StabilizationModeEnable stabilization_mode_enable;
    cmd_CV_StabilizationModeDisable stabilization_mode_disable;
    cmd_CV_DumpStart dump_start;
    cmd_CV_DumpStop dump_stop;
    cmd_CV_RecognitionModeEnable recognition_mode_enable;
    cmd_CV_RecognitionModeDisable recognition_mode_disable;
  } cmd;
} cmd_CV_Root;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define cmd_CV_Root_init_default       \
  {                                    \
    0,                                 \
    {                                  \
      cmd_CV_SetAutoFocus_init_default \
    }                                  \
  }
#define cmd_CV_VampireModeEnable_init_default { 0 }
#define cmd_CV_DumpStart_init_default { 0 }
#define cmd_CV_DumpStop_init_default { 0 }
#define cmd_CV_VampireModeDisable_init_default { 0 }
#define cmd_CV_StabilizationModeEnable_init_default { 0 }
#define cmd_CV_StabilizationModeDisable_init_default { 0 }
#define cmd_CV_RecognitionModeEnable_init_default { 0 }
#define cmd_CV_RecognitionModeDisable_init_default { 0 }
#define cmd_CV_SetAutoFocus_init_default { _ser_JonGuiDataVideoChannel_MIN, 0 }
#define cmd_CV_StartTrackNDC_init_default \
  { _ser_JonGuiDataVideoChannel_MIN, 0, 0, 0, 0 }
#define cmd_CV_StopTrack_init_default { 0 }
#define cmd_CV_Root_init_zero       \
  {                                 \
    0,                              \
    {                               \
      cmd_CV_SetAutoFocus_init_zero \
    }                               \
  }
#define cmd_CV_VampireModeEnable_init_zero { 0 }
#define cmd_CV_DumpStart_init_zero { 0 }
#define cmd_CV_DumpStop_init_zero { 0 }
#define cmd_CV_VampireModeDisable_init_zero { 0 }
#define cmd_CV_StabilizationModeEnable_init_zero { 0 }
#define cmd_CV_StabilizationModeDisable_init_zero { 0 }
#define cmd_CV_RecognitionModeEnable_init_zero { 0 }
#define cmd_CV_RecognitionModeDisable_init_zero { 0 }
#define cmd_CV_SetAutoFocus_init_zero { _ser_JonGuiDataVideoChannel_MIN, 0 }
#define cmd_CV_StartTrackNDC_init_zero \
  { _ser_JonGuiDataVideoChannel_MIN, 0, 0, 0, 0 }
#define cmd_CV_StopTrack_init_zero { 0 }

/* Field tags (for use in manual encoding/decoding) */
#define cmd_CV_SetAutoFocus_channel_tag 1
#define cmd_CV_SetAutoFocus_value_tag 2
#define cmd_CV_StartTrackNDC_channel_tag 1
#define cmd_CV_StartTrackNDC_x_tag 2
#define cmd_CV_StartTrackNDC_y_tag 3
#define cmd_CV_StartTrackNDC_frame_time_tag 4
#define cmd_CV_StartTrackNDC_state_time_tag 5
#define cmd_CV_Root_set_auto_focus_tag 1
#define cmd_CV_Root_start_track_ndc_tag 2
#define cmd_CV_Root_stop_track_tag 3
#define cmd_CV_Root_vampire_mode_enable_tag 4
#define cmd_CV_Root_vampire_mode_disable_tag 5
#define cmd_CV_Root_stabilization_mode_enable_tag 6
#define cmd_CV_Root_stabilization_mode_disable_tag 7
#define cmd_CV_Root_dump_start_tag 8
#define cmd_CV_Root_dump_stop_tag 9
#define cmd_CV_Root_recognition_mode_enable_tag 10
#define cmd_CV_Root_recognition_mode_disable_tag 11

/* Struct field encoding specification for nanopb */
#define cmd_CV_Root_FIELDLIST(X, a)                                            \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, set_auto_focus, cmd.set_auto_focus), 1)   \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, start_track_ndc, cmd.start_track_ndc), 2) \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, stop_track, cmd.stop_track), 3)           \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, vampire_mode_enable, cmd.vampire_mode_enable), 4)                    \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, vampire_mode_disable, cmd.vampire_mode_disable), 5)                  \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, stabilization_mode_enable, cmd.stabilization_mode_enable), 6)        \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, stabilization_mode_disable, cmd.stabilization_mode_disable), 7)      \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, dump_start, cmd.dump_start), 8)           \
  X(a, STATIC, ONEOF, MESSAGE, (cmd, dump_stop, cmd.dump_stop), 9)             \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, recognition_mode_enable, cmd.recognition_mode_enable), 10)           \
  X(a, STATIC, ONEOF, MESSAGE,                                                 \
    (cmd, recognition_mode_disable, cmd.recognition_mode_disable), 11)
#define cmd_CV_Root_CALLBACK NULL
#define cmd_CV_Root_DEFAULT NULL
#define cmd_CV_Root_cmd_set_auto_focus_MSGTYPE cmd_CV_SetAutoFocus
#define cmd_CV_Root_cmd_start_track_ndc_MSGTYPE cmd_CV_StartTrackNDC
#define cmd_CV_Root_cmd_stop_track_MSGTYPE cmd_CV_StopTrack
#define cmd_CV_Root_cmd_vampire_mode_enable_MSGTYPE cmd_CV_VampireModeEnable
#define cmd_CV_Root_cmd_vampire_mode_disable_MSGTYPE cmd_CV_VampireModeDisable
#define cmd_CV_Root_cmd_stabilization_mode_enable_MSGTYPE \
  cmd_CV_StabilizationModeEnable
#define cmd_CV_Root_cmd_stabilization_mode_disable_MSGTYPE \
  cmd_CV_StabilizationModeDisable
#define cmd_CV_Root_cmd_dump_start_MSGTYPE cmd_CV_DumpStart
#define cmd_CV_Root_cmd_dump_stop_MSGTYPE cmd_CV_DumpStop
#define cmd_CV_Root_cmd_recognition_mode_enable_MSGTYPE \
  cmd_CV_RecognitionModeEnable
#define cmd_CV_Root_cmd_recognition_mode_disable_MSGTYPE \
  cmd_CV_RecognitionModeDisable

#define cmd_CV_VampireModeEnable_FIELDLIST(X, a)

#define cmd_CV_VampireModeEnable_CALLBACK NULL
#define cmd_CV_VampireModeEnable_DEFAULT NULL

#define cmd_CV_DumpStart_FIELDLIST(X, a)

#define cmd_CV_DumpStart_CALLBACK NULL
#define cmd_CV_DumpStart_DEFAULT NULL

#define cmd_CV_DumpStop_FIELDLIST(X, a)

#define cmd_CV_DumpStop_CALLBACK NULL
#define cmd_CV_DumpStop_DEFAULT NULL

#define cmd_CV_VampireModeDisable_FIELDLIST(X, a)

#define cmd_CV_VampireModeDisable_CALLBACK NULL
#define cmd_CV_VampireModeDisable_DEFAULT NULL

#define cmd_CV_StabilizationModeEnable_FIELDLIST(X, a)

#define cmd_CV_StabilizationModeEnable_CALLBACK NULL
#define cmd_CV_StabilizationModeEnable_DEFAULT NULL

#define cmd_CV_StabilizationModeDisable_FIELDLIST(X, a)

#define cmd_CV_StabilizationModeDisable_CALLBACK NULL
#define cmd_CV_StabilizationModeDisable_DEFAULT NULL

#define cmd_CV_RecognitionModeEnable_FIELDLIST(X, a)

#define cmd_CV_RecognitionModeEnable_CALLBACK NULL
#define cmd_CV_RecognitionModeEnable_DEFAULT NULL

#define cmd_CV_RecognitionModeDisable_FIELDLIST(X, a)

#define cmd_CV_RecognitionModeDisable_CALLBACK NULL
#define cmd_CV_RecognitionModeDisable_DEFAULT NULL

#define cmd_CV_SetAutoFocus_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, channel, 1) \
  X(a, STATIC, SINGULAR, BOOL, value, 2)
#define cmd_CV_SetAutoFocus_CALLBACK NULL
#define cmd_CV_SetAutoFocus_DEFAULT NULL

#define cmd_CV_StartTrackNDC_FIELDLIST(X, a)    \
  X(a, STATIC, SINGULAR, UENUM, channel, 1)     \
  X(a, STATIC, SINGULAR, DOUBLE, x, 2)          \
  X(a, STATIC, SINGULAR, DOUBLE, y, 3)          \
  X(a, STATIC, SINGULAR, UINT64, frame_time, 4) \
  X(a, STATIC, SINGULAR, UINT64, state_time, 5)
#define cmd_CV_StartTrackNDC_CALLBACK NULL
#define cmd_CV_StartTrackNDC_DEFAULT NULL

#define cmd_CV_StopTrack_FIELDLIST(X, a)

#define cmd_CV_StopTrack_CALLBACK NULL
#define cmd_CV_StopTrack_DEFAULT NULL

  extern const pb_msgdesc_t cmd_CV_Root_msg;
  extern const pb_msgdesc_t cmd_CV_VampireModeEnable_msg;
  extern const pb_msgdesc_t cmd_CV_DumpStart_msg;
  extern const pb_msgdesc_t cmd_CV_DumpStop_msg;
  extern const pb_msgdesc_t cmd_CV_VampireModeDisable_msg;
  extern const pb_msgdesc_t cmd_CV_StabilizationModeEnable_msg;
  extern const pb_msgdesc_t cmd_CV_StabilizationModeDisable_msg;
  extern const pb_msgdesc_t cmd_CV_RecognitionModeEnable_msg;
  extern const pb_msgdesc_t cmd_CV_RecognitionModeDisable_msg;
  extern const pb_msgdesc_t cmd_CV_SetAutoFocus_msg;
  extern const pb_msgdesc_t cmd_CV_StartTrackNDC_msg;
  extern const pb_msgdesc_t cmd_CV_StopTrack_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_CV_Root_fields &cmd_CV_Root_msg
#define cmd_CV_VampireModeEnable_fields &cmd_CV_VampireModeEnable_msg
#define cmd_CV_DumpStart_fields &cmd_CV_DumpStart_msg
#define cmd_CV_DumpStop_fields &cmd_CV_DumpStop_msg
#define cmd_CV_VampireModeDisable_fields &cmd_CV_VampireModeDisable_msg
#define cmd_CV_StabilizationModeEnable_fields \
  &cmd_CV_StabilizationModeEnable_msg
#define cmd_CV_StabilizationModeDisable_fields \
  &cmd_CV_StabilizationModeDisable_msg
#define cmd_CV_RecognitionModeEnable_fields &cmd_CV_RecognitionModeEnable_msg
#define cmd_CV_RecognitionModeDisable_fields &cmd_CV_RecognitionModeDisable_msg
#define cmd_CV_SetAutoFocus_fields &cmd_CV_SetAutoFocus_msg
#define cmd_CV_StartTrackNDC_fields &cmd_CV_StartTrackNDC_msg
#define cmd_CV_StopTrack_fields &cmd_CV_StopTrack_msg

/* Maximum encoded size of messages (where known) */
#define CMD_CV_JON_SHARED_CMD_CV_PB_H_MAX_SIZE cmd_CV_Root_size
#define cmd_CV_DumpStart_size 0
#define cmd_CV_DumpStop_size 0
#define cmd_CV_RecognitionModeDisable_size 0
#define cmd_CV_RecognitionModeEnable_size 0
#define cmd_CV_Root_size 44
#define cmd_CV_SetAutoFocus_size 4
#define cmd_CV_StabilizationModeDisable_size 0
#define cmd_CV_StabilizationModeEnable_size 0
#define cmd_CV_StartTrackNDC_size 42
#define cmd_CV_StopTrack_size 0
#define cmd_CV_VampireModeDisable_size 0
#define cmd_CV_VampireModeEnable_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
