/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_JON_CAN_JON_CAN_STREAM_PB_H_INCLUDED
#define PB_JON_CAN_JON_CAN_STREAM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Single CAN/CAN-FD frame */
typedef struct _jon_can_CANFrame {
    uint64_t timestamp_us; /* Timestamp in microseconds */
    uint32_t can_id; /* Raw CAN ID */
    bool is_rx; /* true=received from device, false=sent to device */
    bool is_fd; /* true=CAN-FD, false=classic CAN */
    pb_callback_t data; /* Frame data (up to 8 bytes for CAN, up to 64 for CAN-FD) */
} jon_can_CANFrame;

/* Batch of CAN frames for efficient streaming */
typedef struct _jon_can_CANFrameBatch {
    pb_callback_t frames;
} jon_can_CANFrameBatch;

/* Connection confirmation message sent when WebSocket connects */
typedef struct _jon_can_CANStreamConnected {
    pb_callback_t streams; /* Discovered CAN stream IDs (e.g., "0x304", "0x510") */
} jon_can_CANStreamConnected;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define jon_can_CANFrame_init_default            {0, 0, 0, 0, {{NULL}, NULL}}
#define jon_can_CANFrameBatch_init_default       {{{NULL}, NULL}}
#define jon_can_CANStreamConnected_init_default  {{{NULL}, NULL}}
#define jon_can_CANFrame_init_zero               {0, 0, 0, 0, {{NULL}, NULL}}
#define jon_can_CANFrameBatch_init_zero          {{{NULL}, NULL}}
#define jon_can_CANStreamConnected_init_zero     {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define jon_can_CANFrame_timestamp_us_tag        1
#define jon_can_CANFrame_can_id_tag              2
#define jon_can_CANFrame_is_rx_tag               3
#define jon_can_CANFrame_is_fd_tag               4
#define jon_can_CANFrame_data_tag                5
#define jon_can_CANFrameBatch_frames_tag         1
#define jon_can_CANStreamConnected_streams_tag   1

/* Struct field encoding specification for nanopb */
#define jon_can_CANFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      1) \
X(a, STATIC,   SINGULAR, UINT32,   can_id,            2) \
X(a, STATIC,   SINGULAR, BOOL,     is_rx,             3) \
X(a, STATIC,   SINGULAR, BOOL,     is_fd,             4) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              5)
#define jon_can_CANFrame_CALLBACK pb_default_field_callback
#define jon_can_CANFrame_DEFAULT NULL

#define jon_can_CANFrameBatch_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  frames,            1)
#define jon_can_CANFrameBatch_CALLBACK pb_default_field_callback
#define jon_can_CANFrameBatch_DEFAULT NULL
#define jon_can_CANFrameBatch_frames_MSGTYPE jon_can_CANFrame

#define jon_can_CANStreamConnected_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   streams,           1)
#define jon_can_CANStreamConnected_CALLBACK pb_default_field_callback
#define jon_can_CANStreamConnected_DEFAULT NULL

extern const pb_msgdesc_t jon_can_CANFrame_msg;
extern const pb_msgdesc_t jon_can_CANFrameBatch_msg;
extern const pb_msgdesc_t jon_can_CANStreamConnected_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jon_can_CANFrame_fields &jon_can_CANFrame_msg
#define jon_can_CANFrameBatch_fields &jon_can_CANFrameBatch_msg
#define jon_can_CANStreamConnected_fields &jon_can_CANStreamConnected_msg

/* Maximum encoded size of messages (where known) */
/* jon_can_CANFrame_size depends on runtime parameters */
/* jon_can_CANFrameBatch_size depends on runtime parameters */
/* jon_can_CANStreamConnected_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
