/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_lrf_align.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_Lrf_calib_Root, cmd_Lrf_calib_Root, AUTO)


PB_BIND(cmd_Lrf_calib_Offsets, cmd_Lrf_calib_Offsets, AUTO)


PB_BIND(cmd_Lrf_calib_SetOffsets, cmd_Lrf_calib_SetOffsets, AUTO)


PB_BIND(cmd_Lrf_calib_ShiftOffsetsBy, cmd_Lrf_calib_ShiftOffsetsBy, AUTO)


PB_BIND(cmd_Lrf_calib_ResetOffsets, cmd_Lrf_calib_ResetOffsets, AUTO)


PB_BIND(cmd_Lrf_calib_SaveOffsets, cmd_Lrf_calib_SaveOffsets, AUTO)
