/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_Root, cmd_Root, AUTO)


PB_BIND(cmd_Ping, cmd_Ping, AUTO)


PB_BIND(cmd_Noop, cmd_Noop, AUTO)


PB_BIND(cmd_Frozen, cmd_Frozen, AUTO)
