/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_JON_VIDEO_JON_VIDEO_META_PB_H_INCLUDED
#define PB_JON_VIDEO_JON_VIDEO_META_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Types of errors that can occur during video metadata extraction */
typedef enum _jon_video_VideoErrorType {
    jon_video_VideoErrorType_VIDEO_ERROR_TYPE_UNSPECIFIED = 0,
    jon_video_VideoErrorType_VIDEO_ERROR_TYPE_FILE_NOT_FOUND = 1,
    jon_video_VideoErrorType_VIDEO_ERROR_TYPE_EMPTY_FILE = 2,
    jon_video_VideoErrorType_VIDEO_ERROR_TYPE_NO_MOOV = 3,
    jon_video_VideoErrorType_VIDEO_ERROR_TYPE_INVALID_MOOV = 4,
    jon_video_VideoErrorType_VIDEO_ERROR_TYPE_TRUNCATED = 5
} jon_video_VideoErrorType;

/* Struct definitions */
/* List of video UUIDs for explicit selection */
typedef struct _jon_video_VideoIdList {
    pb_callback_t uuids;
} jon_video_VideoIdList;

/* Time-based range query for selecting videos */
typedef struct _jon_video_VideoRangeQuery {
    uint64_t start_timestamp; /* Unix seconds */
    uint64_t end_timestamp; /* Unix seconds */
    pb_callback_t source_type; /* "day" or "heat" filter */
    bool has_limit;
    uint32_t limit;
    bool has_offset;
    uint32_t offset; /* Pagination offset */
} jon_video_VideoRangeQuery;

/* Request message for video metadata retrieval */
typedef struct _jon_video_VideoMetaRequest {
    pb_size_t which_query;
    union {
        jon_video_VideoRangeQuery range; /* Time-based range query */
        jon_video_VideoIdList ids; /* Explicit UUID list */
    } query;
} jon_video_VideoMetaRequest;

/* Response containing video metadata and any errors */
typedef struct _jon_video_VideoMetaResponse {
    pb_callback_t videos; /* Successfully processed videos */
    pb_callback_t errors; /* Errors for failed videos */
    uint32_t total_count; /* Total matching (before limit) */
    /* Shared encoding parameters (same for all videos in response) */
    uint32_t width; /* 1920 for full, 480 for mini */
    uint32_t height; /* 1080 for full, 270 for mini */
    pb_callback_t dsi; /* avcC decoder specific info (shared codec config) */
    uint32_t timescale; /* Media timescale from mdhd */
} jon_video_VideoMetaResponse;

/* MP4 sample table data extracted from MOOV */
typedef struct _jon_video_SampleTable {
    pb_callback_t sample_sizes; /* Frame sizes in bytes (stsz) */
    pb_callback_t chunk_offsets; /* Byte offsets in file (stco/co64) */
    pb_callback_t sample_times; /* Decoding timestamps (stts deltas) */
    pb_callback_t sync_samples; /* Keyframe indices, 1-based (stss) */
    pb_callback_t sample_to_chunk; /* Sample-to-chunk mapping (stsc) */
} jon_video_SampleTable;

/* Metadata for a single video including MOOV data
 Used by both /api/video/meta (full quality) and /api/video/meta-mini (preview quality) */
typedef struct _jon_video_VideoMeta {
    pb_callback_t uuid;
    int32_t session_id;
    uint64_t timestamp; /* Unix seconds */
    pb_callback_t storage_path; /* Directory path to video files */
    pb_callback_t source_type; /* "day" or "heat" */
    /* Per-video MOOV data */
    uint32_t frame_count;
    uint32_t duration_ms;
    /* Sample table for frame-accurate seeking and playback */
    bool has_sample_table;
    jon_video_SampleTable sample_table;
} jon_video_VideoMeta;

/* Sample-to-chunk box entry */
typedef struct _jon_video_SampleToChunk {
    uint32_t first_chunk;
    uint32_t samples_per_chunk;
    uint32_t sample_description_index;
} jon_video_SampleToChunk;

/* Error information for a video that failed processing */
typedef struct _jon_video_VideoError {
    pb_callback_t uuid;
    pb_callback_t storage_path;
    jon_video_VideoErrorType error_type;
    pb_callback_t error_message;
} jon_video_VideoError;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _jon_video_VideoErrorType_MIN jon_video_VideoErrorType_VIDEO_ERROR_TYPE_UNSPECIFIED
#define _jon_video_VideoErrorType_MAX jon_video_VideoErrorType_VIDEO_ERROR_TYPE_TRUNCATED
#define _jon_video_VideoErrorType_ARRAYSIZE ((jon_video_VideoErrorType)(jon_video_VideoErrorType_VIDEO_ERROR_TYPE_TRUNCATED+1))








#define jon_video_VideoError_error_type_ENUMTYPE jon_video_VideoErrorType


/* Initializer values for message structs */
#define jon_video_VideoMetaRequest_init_default  {0, {jon_video_VideoRangeQuery_init_default}}
#define jon_video_VideoIdList_init_default       {{{NULL}, NULL}}
#define jon_video_VideoRangeQuery_init_default   {0, 0, {{NULL}, NULL}, false, 0, false, 0}
#define jon_video_VideoMetaResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define jon_video_VideoMeta_init_default         {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, false, jon_video_SampleTable_init_default}
#define jon_video_SampleTable_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define jon_video_SampleToChunk_init_default     {0, 0, 0}
#define jon_video_VideoError_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, _jon_video_VideoErrorType_MIN, {{NULL}, NULL}}
#define jon_video_VideoMetaRequest_init_zero     {0, {jon_video_VideoRangeQuery_init_zero}}
#define jon_video_VideoIdList_init_zero          {{{NULL}, NULL}}
#define jon_video_VideoRangeQuery_init_zero      {0, 0, {{NULL}, NULL}, false, 0, false, 0}
#define jon_video_VideoMetaResponse_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define jon_video_VideoMeta_init_zero            {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, false, jon_video_SampleTable_init_zero}
#define jon_video_SampleTable_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define jon_video_SampleToChunk_init_zero        {0, 0, 0}
#define jon_video_VideoError_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, _jon_video_VideoErrorType_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define jon_video_VideoIdList_uuids_tag          1
#define jon_video_VideoRangeQuery_start_timestamp_tag 1
#define jon_video_VideoRangeQuery_end_timestamp_tag 2
#define jon_video_VideoRangeQuery_source_type_tag 3
#define jon_video_VideoRangeQuery_limit_tag      4
#define jon_video_VideoRangeQuery_offset_tag     5
#define jon_video_VideoMetaRequest_range_tag     1
#define jon_video_VideoMetaRequest_ids_tag       2
#define jon_video_VideoMetaResponse_videos_tag   1
#define jon_video_VideoMetaResponse_errors_tag   2
#define jon_video_VideoMetaResponse_total_count_tag 3
#define jon_video_VideoMetaResponse_width_tag    10
#define jon_video_VideoMetaResponse_height_tag   11
#define jon_video_VideoMetaResponse_dsi_tag      12
#define jon_video_VideoMetaResponse_timescale_tag 13
#define jon_video_SampleTable_sample_sizes_tag   1
#define jon_video_SampleTable_chunk_offsets_tag  2
#define jon_video_SampleTable_sample_times_tag   3
#define jon_video_SampleTable_sync_samples_tag   4
#define jon_video_SampleTable_sample_to_chunk_tag 5
#define jon_video_VideoMeta_uuid_tag             1
#define jon_video_VideoMeta_session_id_tag       2
#define jon_video_VideoMeta_timestamp_tag        3
#define jon_video_VideoMeta_storage_path_tag     4
#define jon_video_VideoMeta_source_type_tag      5
#define jon_video_VideoMeta_frame_count_tag      6
#define jon_video_VideoMeta_duration_ms_tag      7
#define jon_video_VideoMeta_sample_table_tag     12
#define jon_video_SampleToChunk_first_chunk_tag  1
#define jon_video_SampleToChunk_samples_per_chunk_tag 2
#define jon_video_SampleToChunk_sample_description_index_tag 3
#define jon_video_VideoError_uuid_tag            1
#define jon_video_VideoError_storage_path_tag    2
#define jon_video_VideoError_error_type_tag      3
#define jon_video_VideoError_error_message_tag   4

/* Struct field encoding specification for nanopb */
#define jon_video_VideoMetaRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (query,range,query.range),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (query,ids,query.ids),   2)
#define jon_video_VideoMetaRequest_CALLBACK NULL
#define jon_video_VideoMetaRequest_DEFAULT NULL
#define jon_video_VideoMetaRequest_query_range_MSGTYPE jon_video_VideoRangeQuery
#define jon_video_VideoMetaRequest_query_ids_MSGTYPE jon_video_VideoIdList

#define jon_video_VideoIdList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   uuids,             1)
#define jon_video_VideoIdList_CALLBACK pb_default_field_callback
#define jon_video_VideoIdList_DEFAULT NULL

#define jon_video_VideoRangeQuery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   start_timestamp,   1) \
X(a, STATIC,   SINGULAR, UINT64,   end_timestamp,     2) \
X(a, CALLBACK, OPTIONAL, STRING,   source_type,       3) \
X(a, STATIC,   OPTIONAL, UINT32,   limit,             4) \
X(a, STATIC,   OPTIONAL, UINT32,   offset,            5)
#define jon_video_VideoRangeQuery_CALLBACK pb_default_field_callback
#define jon_video_VideoRangeQuery_DEFAULT NULL

#define jon_video_VideoMetaResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  videos,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  errors,            2) \
X(a, STATIC,   SINGULAR, UINT32,   total_count,       3) \
X(a, STATIC,   SINGULAR, UINT32,   width,            10) \
X(a, STATIC,   SINGULAR, UINT32,   height,           11) \
X(a, CALLBACK, SINGULAR, BYTES,    dsi,              12) \
X(a, STATIC,   SINGULAR, UINT32,   timescale,        13)
#define jon_video_VideoMetaResponse_CALLBACK pb_default_field_callback
#define jon_video_VideoMetaResponse_DEFAULT NULL
#define jon_video_VideoMetaResponse_videos_MSGTYPE jon_video_VideoMeta
#define jon_video_VideoMetaResponse_errors_MSGTYPE jon_video_VideoError

#define jon_video_VideoMeta_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   uuid,              1) \
X(a, STATIC,   SINGULAR, INT32,    session_id,        2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3) \
X(a, CALLBACK, SINGULAR, STRING,   storage_path,      4) \
X(a, CALLBACK, SINGULAR, STRING,   source_type,       5) \
X(a, STATIC,   SINGULAR, UINT32,   frame_count,       6) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sample_table,     12)
#define jon_video_VideoMeta_CALLBACK pb_default_field_callback
#define jon_video_VideoMeta_DEFAULT NULL
#define jon_video_VideoMeta_sample_table_MSGTYPE jon_video_SampleTable

#define jon_video_SampleTable_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   sample_sizes,      1) \
X(a, CALLBACK, REPEATED, UINT64,   chunk_offsets,     2) \
X(a, CALLBACK, REPEATED, UINT32,   sample_times,      3) \
X(a, CALLBACK, REPEATED, UINT32,   sync_samples,      4) \
X(a, CALLBACK, REPEATED, MESSAGE,  sample_to_chunk,   5)
#define jon_video_SampleTable_CALLBACK pb_default_field_callback
#define jon_video_SampleTable_DEFAULT NULL
#define jon_video_SampleTable_sample_to_chunk_MSGTYPE jon_video_SampleToChunk

#define jon_video_SampleToChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   first_chunk,       1) \
X(a, STATIC,   SINGULAR, UINT32,   samples_per_chunk,   2) \
X(a, STATIC,   SINGULAR, UINT32,   sample_description_index,   3)
#define jon_video_SampleToChunk_CALLBACK NULL
#define jon_video_SampleToChunk_DEFAULT NULL

#define jon_video_VideoError_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   uuid,              1) \
X(a, CALLBACK, SINGULAR, STRING,   storage_path,      2) \
X(a, STATIC,   SINGULAR, UENUM,    error_type,        3) \
X(a, CALLBACK, SINGULAR, STRING,   error_message,     4)
#define jon_video_VideoError_CALLBACK pb_default_field_callback
#define jon_video_VideoError_DEFAULT NULL

extern const pb_msgdesc_t jon_video_VideoMetaRequest_msg;
extern const pb_msgdesc_t jon_video_VideoIdList_msg;
extern const pb_msgdesc_t jon_video_VideoRangeQuery_msg;
extern const pb_msgdesc_t jon_video_VideoMetaResponse_msg;
extern const pb_msgdesc_t jon_video_VideoMeta_msg;
extern const pb_msgdesc_t jon_video_SampleTable_msg;
extern const pb_msgdesc_t jon_video_SampleToChunk_msg;
extern const pb_msgdesc_t jon_video_VideoError_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jon_video_VideoMetaRequest_fields &jon_video_VideoMetaRequest_msg
#define jon_video_VideoIdList_fields &jon_video_VideoIdList_msg
#define jon_video_VideoRangeQuery_fields &jon_video_VideoRangeQuery_msg
#define jon_video_VideoMetaResponse_fields &jon_video_VideoMetaResponse_msg
#define jon_video_VideoMeta_fields &jon_video_VideoMeta_msg
#define jon_video_SampleTable_fields &jon_video_SampleTable_msg
#define jon_video_SampleToChunk_fields &jon_video_SampleToChunk_msg
#define jon_video_VideoError_fields &jon_video_VideoError_msg

/* Maximum encoded size of messages (where known) */
/* jon_video_VideoMetaRequest_size depends on runtime parameters */
/* jon_video_VideoIdList_size depends on runtime parameters */
/* jon_video_VideoRangeQuery_size depends on runtime parameters */
/* jon_video_VideoMetaResponse_size depends on runtime parameters */
/* jon_video_VideoMeta_size depends on runtime parameters */
/* jon_video_SampleTable_size depends on runtime parameters */
/* jon_video_VideoError_size depends on runtime parameters */
#define JON_VIDEO_JON_VIDEO_META_PB_H_MAX_SIZE   jon_video_SampleToChunk_size
#define jon_video_SampleToChunk_size             18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
