/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_SYSTEM_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_SYSTEM_PB_H_INCLUDED
#include <pb.h>
#include "jon_shared_data_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ser_JonGuiDataSystem {
    double cpu_temperature;
    double gpu_temperature;
    double gpu_load;
    double cpu_load;
    double power_consumption;
    ser_JonGuiDataSystemLocalizations loc;
    int32_t cur_video_rec_dir_year;
    int32_t cur_video_rec_dir_month;
    int32_t cur_video_rec_dir_day;
    int32_t cur_video_rec_dir_hour;
    int32_t cur_video_rec_dir_minute;
    int32_t cur_video_rec_dir_second;
    bool rec_enabled;
    bool important_rec_enabled;
    bool low_disk_space;
    bool no_disk_space;
    int32_t disk_space;
    bool tracking;
    bool vampire_mode;
    bool stabilization_mode;
    bool geodesic_mode;
    bool cv_dumping;
    bool recognition_mode;
    ser_JonGuiDataAccumulatorStateIdx accumulator_state;
    int32_t ext_bat_capacity;
    ser_JonGuiDataExtBatStatus ext_bat_status;
} ser_JonGuiDataSystem;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataSystem_init_default        {0, 0, 0, 0, 0, _ser_JonGuiDataSystemLocalizations_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _ser_JonGuiDataAccumulatorStateIdx_MIN, 0, _ser_JonGuiDataExtBatStatus_MIN}
#define ser_JonGuiDataSystem_init_zero           {0, 0, 0, 0, 0, _ser_JonGuiDataSystemLocalizations_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _ser_JonGuiDataAccumulatorStateIdx_MIN, 0, _ser_JonGuiDataExtBatStatus_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataSystem_cpu_temperature_tag 1
#define ser_JonGuiDataSystem_gpu_temperature_tag 2
#define ser_JonGuiDataSystem_gpu_load_tag        3
#define ser_JonGuiDataSystem_cpu_load_tag        4
#define ser_JonGuiDataSystem_power_consumption_tag 5
#define ser_JonGuiDataSystem_loc_tag             6
#define ser_JonGuiDataSystem_cur_video_rec_dir_year_tag 7
#define ser_JonGuiDataSystem_cur_video_rec_dir_month_tag 8
#define ser_JonGuiDataSystem_cur_video_rec_dir_day_tag 9
#define ser_JonGuiDataSystem_cur_video_rec_dir_hour_tag 10
#define ser_JonGuiDataSystem_cur_video_rec_dir_minute_tag 11
#define ser_JonGuiDataSystem_cur_video_rec_dir_second_tag 12
#define ser_JonGuiDataSystem_rec_enabled_tag     13
#define ser_JonGuiDataSystem_important_rec_enabled_tag 14
#define ser_JonGuiDataSystem_low_disk_space_tag  15
#define ser_JonGuiDataSystem_no_disk_space_tag   16
#define ser_JonGuiDataSystem_disk_space_tag      17
#define ser_JonGuiDataSystem_tracking_tag        18
#define ser_JonGuiDataSystem_vampire_mode_tag    19
#define ser_JonGuiDataSystem_stabilization_mode_tag 20
#define ser_JonGuiDataSystem_geodesic_mode_tag   21
#define ser_JonGuiDataSystem_cv_dumping_tag      22
#define ser_JonGuiDataSystem_recognition_mode_tag 23
#define ser_JonGuiDataSystem_accumulator_state_tag 24
#define ser_JonGuiDataSystem_ext_bat_capacity_tag 25
#define ser_JonGuiDataSystem_ext_bat_status_tag  26

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataSystem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   cpu_temperature,   1) \
X(a, STATIC,   SINGULAR, DOUBLE,   gpu_temperature,   2) \
X(a, STATIC,   SINGULAR, DOUBLE,   gpu_load,          3) \
X(a, STATIC,   SINGULAR, DOUBLE,   cpu_load,          4) \
X(a, STATIC,   SINGULAR, DOUBLE,   power_consumption,   5) \
X(a, STATIC,   SINGULAR, UENUM,    loc,               6) \
X(a, STATIC,   SINGULAR, INT32,    cur_video_rec_dir_year,   7) \
X(a, STATIC,   SINGULAR, INT32,    cur_video_rec_dir_month,   8) \
X(a, STATIC,   SINGULAR, INT32,    cur_video_rec_dir_day,   9) \
X(a, STATIC,   SINGULAR, INT32,    cur_video_rec_dir_hour,  10) \
X(a, STATIC,   SINGULAR, INT32,    cur_video_rec_dir_minute,  11) \
X(a, STATIC,   SINGULAR, INT32,    cur_video_rec_dir_second,  12) \
X(a, STATIC,   SINGULAR, BOOL,     rec_enabled,      13) \
X(a, STATIC,   SINGULAR, BOOL,     important_rec_enabled,  14) \
X(a, STATIC,   SINGULAR, BOOL,     low_disk_space,   15) \
X(a, STATIC,   SINGULAR, BOOL,     no_disk_space,    16) \
X(a, STATIC,   SINGULAR, INT32,    disk_space,       17) \
X(a, STATIC,   SINGULAR, BOOL,     tracking,         18) \
X(a, STATIC,   SINGULAR, BOOL,     vampire_mode,     19) \
X(a, STATIC,   SINGULAR, BOOL,     stabilization_mode,  20) \
X(a, STATIC,   SINGULAR, BOOL,     geodesic_mode,    21) \
X(a, STATIC,   SINGULAR, BOOL,     cv_dumping,       22) \
X(a, STATIC,   SINGULAR, BOOL,     recognition_mode,  23) \
X(a, STATIC,   SINGULAR, UENUM,    accumulator_state,  24) \
X(a, STATIC,   SINGULAR, INT32,    ext_bat_capacity,  25) \
X(a, STATIC,   SINGULAR, UENUM,    ext_bat_status,   26)
#define ser_JonGuiDataSystem_CALLBACK NULL
#define ser_JonGuiDataSystem_DEFAULT NULL

extern const pb_msgdesc_t ser_JonGuiDataSystem_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataSystem_fields &ser_JonGuiDataSystem_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_SYSTEM_PB_H_MAX_SIZE ser_JonGuiDataSystem_size
#define ser_JonGuiDataSystem_size                170

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
