/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_SER_JON_SHARED_DATA_CAMERA_DAY_PB_H_INCLUDED
#define PB_SER_JON_SHARED_DATA_CAMERA_DAY_PB_H_INCLUDED
#include "jon_shared_data_types.pb.h"

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ser_JonGuiDataCameraDay
{
  double focus_pos;
  double zoom_pos;
  double iris_pos;
  bool infrared_filter;
  int32_t zoom_table_pos;
  int32_t zoom_table_pos_max;
  ser_JonGuiDataFxModeDay fx_mode;
  bool auto_focus;
  bool auto_iris;
  double digital_zoom_level;
  double clahe_level;
  double horizontal_fov_degrees;
  double vertical_fov_degrees;
  bool is_started;
  bool auto_gain;
} ser_JonGuiDataCameraDay;


#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define ser_JonGuiDataCameraDay_init_default \
  { 0, 0, 0, 0, 0, 0, _ser_JonGuiDataFxModeDay_MIN, 0, 0, 0, 0, 0, 0, 0, 0 }
#define ser_JonGuiDataCameraDay_init_zero \
  { 0, 0, 0, 0, 0, 0, _ser_JonGuiDataFxModeDay_MIN, 0, 0, 0, 0, 0, 0, 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define ser_JonGuiDataCameraDay_focus_pos_tag 1
#define ser_JonGuiDataCameraDay_zoom_pos_tag 2
#define ser_JonGuiDataCameraDay_iris_pos_tag 3
#define ser_JonGuiDataCameraDay_infrared_filter_tag 4
#define ser_JonGuiDataCameraDay_zoom_table_pos_tag 5
#define ser_JonGuiDataCameraDay_zoom_table_pos_max_tag 6
#define ser_JonGuiDataCameraDay_fx_mode_tag 7
#define ser_JonGuiDataCameraDay_auto_focus_tag 8
#define ser_JonGuiDataCameraDay_auto_iris_tag 9
#define ser_JonGuiDataCameraDay_digital_zoom_level_tag 10
#define ser_JonGuiDataCameraDay_clahe_level_tag 11
#define ser_JonGuiDataCameraDay_horizontal_fov_degrees_tag 12
#define ser_JonGuiDataCameraDay_vertical_fov_degrees_tag 13
#define ser_JonGuiDataCameraDay_is_started_tag 14
#define ser_JonGuiDataCameraDay_auto_gain_tag 15

/* Struct field encoding specification for nanopb */
#define ser_JonGuiDataCameraDay_FIELDLIST(X, a)              \
  X(a, STATIC, SINGULAR, DOUBLE, focus_pos, 1)               \
  X(a, STATIC, SINGULAR, DOUBLE, zoom_pos, 2)                \
  X(a, STATIC, SINGULAR, DOUBLE, iris_pos, 3)                \
  X(a, STATIC, SINGULAR, BOOL, infrared_filter, 4)           \
  X(a, STATIC, SINGULAR, INT32, zoom_table_pos, 5)           \
  X(a, STATIC, SINGULAR, INT32, zoom_table_pos_max, 6)       \
  X(a, STATIC, SINGULAR, UENUM, fx_mode, 7)                  \
  X(a, STATIC, SINGULAR, BOOL, auto_focus, 8)                \
  X(a, STATIC, SINGULAR, BOOL, auto_iris, 9)                 \
  X(a, STATIC, SINGULAR, DOUBLE, digital_zoom_level, 10)     \
  X(a, STATIC, SINGULAR, DOUBLE, clahe_level, 11)            \
  X(a, STATIC, SINGULAR, DOUBLE, horizontal_fov_degrees, 12) \
  X(a, STATIC, SINGULAR, DOUBLE, vertical_fov_degrees, 13)   \
  X(a, STATIC, SINGULAR, BOOL, is_started, 14)               \
  X(a, STATIC, SINGULAR, BOOL, auto_gain, 15)
#define ser_JonGuiDataCameraDay_CALLBACK NULL
#define ser_JonGuiDataCameraDay_DEFAULT NULL

  extern const pb_msgdesc_t ser_JonGuiDataCameraDay_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ser_JonGuiDataCameraDay_fields &ser_JonGuiDataCameraDay_msg

/* Maximum encoded size of messages (where known) */
#define SER_JON_SHARED_DATA_CAMERA_DAY_PB_H_MAX_SIZE \
  ser_JonGuiDataCameraDay_size
#define ser_JonGuiDataCameraDay_size 97

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
