/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "jon_shared_cmd_lrf.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_Lrf_Root, cmd_Lrf_Root, AUTO)


PB_BIND(cmd_Lrf_GetMeteo, cmd_Lrf_GetMeteo, AUTO)


PB_BIND(cmd_Lrf_Start, cmd_Lrf_Start, AUTO)


PB_BIND(cmd_Lrf_Stop, cmd_Lrf_Stop, AUTO)


PB_BIND(cmd_Lrf_Measure, cmd_Lrf_Measure, AUTO)


PB_BIND(cmd_Lrf_ScanOn, cmd_Lrf_ScanOn, AUTO)


PB_BIND(cmd_Lrf_ScanOff, cmd_Lrf_ScanOff, AUTO)


PB_BIND(cmd_Lrf_RefineOff, cmd_Lrf_RefineOff, AUTO)


PB_BIND(cmd_Lrf_RefineOn, cmd_Lrf_RefineOn, AUTO)


PB_BIND(cmd_Lrf_TargetDesignatorOff, cmd_Lrf_TargetDesignatorOff, AUTO)


PB_BIND(cmd_Lrf_TargetDesignatorOnModeA, cmd_Lrf_TargetDesignatorOnModeA, AUTO)


PB_BIND(cmd_Lrf_TargetDesignatorOnModeB, cmd_Lrf_TargetDesignatorOnModeB, AUTO)


PB_BIND(cmd_Lrf_EnableFogMode, cmd_Lrf_EnableFogMode, AUTO)


PB_BIND(cmd_Lrf_DisableFogMode, cmd_Lrf_DisableFogMode, AUTO)


PB_BIND(cmd_Lrf_SetScanMode, cmd_Lrf_SetScanMode, AUTO)


PB_BIND(cmd_Lrf_NewSession, cmd_Lrf_NewSession, AUTO)



